/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
    UseSuspenseQueryOptions,
    UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import { customFetch } from ".././fetcher.ts";
import type {
    AuthResponse,
    ForgotPasswordRequest,
    GithubCallbackParams,
    GoogleCallbackParams,
    LoginRequest,
    MessageResponse,
    ProfileResponse,
    RegisterRequest,
    ResetPasswordRequest,
    UpdateProfileRequest,
    VerifyEmailParams,
} from "../model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
    query: T,
    queryKey: K,
): T & { queryKey: K } => {
    const result = { queryKey } as T & { queryKey: K };
    for (const key of Object.keys(query)) {
        // The explicit queryKey always wins, matching the previous
        // `{ ...query, queryKey }` spread where it was set last.
        if (key === "queryKey") continue;
        Object.defineProperty(result, key, {
            enumerable: true,
            configurable: true,
            get: () => (query as Record<string, unknown>)[key],
        });
    }
    return result;
};

export type forgotPasswordResponse200 = {
    data: MessageResponse;
    status: 200;
};

export type forgotPasswordResponseSuccess = forgotPasswordResponse200 & {
    headers: Headers;
};

export const getForgotPasswordUrl = () => {
    return `/api/auth/forgot-password`;
};

/**
 * @summary Request a password reset email
 */
export const forgotPassword = async (
    forgotPasswordRequest: ForgotPasswordRequest,
    options?: Parameters<typeof customFetch>[1],
): Promise<forgotPasswordResponseSuccess> => {
    return customFetch<forgotPasswordResponseSuccess>(getForgotPasswordUrl(), {
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(forgotPasswordRequest),
    });
};

export const getForgotPasswordMutationOptions = <
    TError = unknown,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof forgotPassword>>,
        TError,
        { data: ForgotPasswordRequest },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof forgotPassword>>,
    TError,
    { data: ForgotPasswordRequest },
    TContext
> => {
    const mutationKey = ["forgotPassword"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof forgotPassword>>,
        { data: ForgotPasswordRequest }
    > = (props) => {
        const { data } = props ?? {};

        return forgotPassword(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type ForgotPasswordMutationResult = NonNullable<
    Awaited<ReturnType<typeof forgotPassword>>
>;
export type ForgotPasswordMutationBody = ForgotPasswordRequest;
export type ForgotPasswordMutationError = unknown;

/**
 * @summary Request a password reset email
 */
export const useForgotPassword = <TError = unknown, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof forgotPassword>>,
            TError,
            { data: ForgotPasswordRequest },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof forgotPassword>>,
    TError,
    { data: ForgotPasswordRequest },
    TContext
> => {
    return useMutation(getForgotPasswordMutationOptions(options), queryClient);
};
export type githubLoginResponse302 = {
    data: void;
    status: 302;
};
export type githubLoginResponseError = githubLoginResponse302 & {
    headers: Headers;
};

export type githubLoginResponse = githubLoginResponseError;

export const getGithubLoginUrl = () => {
    return `/api/auth/github`;
};

/**
 * @summary Redirect to GitHub OAuth
 */
export const githubLogin = async (
    options?: Parameters<typeof customFetch>[1],
): Promise<githubLoginResponse> => {
    return customFetch<githubLoginResponse>(getGithubLoginUrl(), {
        ...options,
        method: "GET",
    });
};

export const getGithubLoginQueryKey = () => {
    return [`/api/auth/github`] as const;
};

export const getGithubLoginQueryOptions = <
    TData = Awaited<ReturnType<typeof githubLogin>>,
    TError = void,
>(options?: {
    query?: Partial<
        UseQueryOptions<Awaited<ReturnType<typeof githubLogin>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGithubLoginQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof githubLogin>>> = ({
        signal,
    }) => githubLogin({ signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof githubLogin>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GithubLoginQueryResult = NonNullable<
    Awaited<ReturnType<typeof githubLogin>>
>;
export type GithubLoginQueryError = void;

export function useGithubLogin<
    TData = Awaited<ReturnType<typeof githubLogin>>,
    TError = void,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof githubLogin>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof githubLogin>>,
                    TError,
                    Awaited<ReturnType<typeof githubLogin>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGithubLogin<
    TData = Awaited<ReturnType<typeof githubLogin>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof githubLogin>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof githubLogin>>,
                    TError,
                    Awaited<ReturnType<typeof githubLogin>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGithubLogin<
    TData = Awaited<ReturnType<typeof githubLogin>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof githubLogin>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Redirect to GitHub OAuth
 */

export function useGithubLogin<
    TData = Awaited<ReturnType<typeof githubLogin>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof githubLogin>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGithubLoginQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return withQueryKey(query, queryOptions.queryKey);
}

export const getGithubLoginSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof githubLogin>>,
    TError = void,
>(options?: {
    query?: Partial<
        UseSuspenseQueryOptions<
            Awaited<ReturnType<typeof githubLogin>>,
            TError,
            TData
        >
    >;
    request?: SecondParameter<typeof customFetch>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGithubLoginQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof githubLogin>>> = ({
        signal,
    }) => githubLogin({ signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof githubLogin>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GithubLoginSuspenseQueryResult = NonNullable<
    Awaited<ReturnType<typeof githubLogin>>
>;
export type GithubLoginSuspenseQueryError = void;

export function useGithubLoginSuspense<
    TData = Awaited<ReturnType<typeof githubLogin>>,
    TError = void,
>(
    options: {
        query: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof githubLogin>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGithubLoginSuspense<
    TData = Awaited<ReturnType<typeof githubLogin>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof githubLogin>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGithubLoginSuspense<
    TData = Awaited<ReturnType<typeof githubLogin>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof githubLogin>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Redirect to GitHub OAuth
 */

export function useGithubLoginSuspense<
    TData = Awaited<ReturnType<typeof githubLogin>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof githubLogin>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGithubLoginSuspenseQueryOptions(options);

    const query = useSuspenseQuery(
        queryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return withQueryKey(query, queryOptions.queryKey);
}

export type githubCallbackResponse302 = {
    data: void;
    status: 302;
};
export type githubCallbackResponseError = githubCallbackResponse302 & {
    headers: Headers;
};

export type githubCallbackResponse = githubCallbackResponseError;

export const getGithubCallbackUrl = (params?: GithubCallbackParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(
                key,
                value === null ? "null" : String(value),
            );
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/api/auth/github/callback?${stringifiedParams}`
        : `/api/auth/github/callback`;
};

/**
 * @summary Handle GitHub OAuth callback
 */
export const githubCallback = async (
    params?: GithubCallbackParams,
    options?: Parameters<typeof customFetch>[1],
): Promise<githubCallbackResponse> => {
    return customFetch<githubCallbackResponse>(getGithubCallbackUrl(params), {
        ...options,
        method: "GET",
    });
};

export const getGithubCallbackQueryKey = (params?: GithubCallbackParams) => {
    return [`/api/auth/github/callback`, ...(params ? [params] : [])] as const;
};

export const getGithubCallbackQueryOptions = <
    TData = Awaited<ReturnType<typeof githubCallback>>,
    TError = void,
>(
    params?: GithubCallbackParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof githubCallback>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getGithubCallbackQueryKey(params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof githubCallback>>
    > = ({ signal }) => githubCallback(params, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof githubCallback>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GithubCallbackQueryResult = NonNullable<
    Awaited<ReturnType<typeof githubCallback>>
>;
export type GithubCallbackQueryError = void;

export function useGithubCallback<
    TData = Awaited<ReturnType<typeof githubCallback>>,
    TError = void,
>(
    params: undefined | GithubCallbackParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof githubCallback>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof githubCallback>>,
                    TError,
                    Awaited<ReturnType<typeof githubCallback>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGithubCallback<
    TData = Awaited<ReturnType<typeof githubCallback>>,
    TError = void,
>(
    params?: GithubCallbackParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof githubCallback>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof githubCallback>>,
                    TError,
                    Awaited<ReturnType<typeof githubCallback>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGithubCallback<
    TData = Awaited<ReturnType<typeof githubCallback>>,
    TError = void,
>(
    params?: GithubCallbackParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof githubCallback>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Handle GitHub OAuth callback
 */

export function useGithubCallback<
    TData = Awaited<ReturnType<typeof githubCallback>>,
    TError = void,
>(
    params?: GithubCallbackParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof githubCallback>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGithubCallbackQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return withQueryKey(query, queryOptions.queryKey);
}

export const getGithubCallbackSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof githubCallback>>,
    TError = void,
>(
    params?: GithubCallbackParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof githubCallback>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getGithubCallbackQueryKey(params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof githubCallback>>
    > = ({ signal }) => githubCallback(params, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof githubCallback>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GithubCallbackSuspenseQueryResult = NonNullable<
    Awaited<ReturnType<typeof githubCallback>>
>;
export type GithubCallbackSuspenseQueryError = void;

export function useGithubCallbackSuspense<
    TData = Awaited<ReturnType<typeof githubCallback>>,
    TError = void,
>(
    params: undefined | GithubCallbackParams,
    options: {
        query: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof githubCallback>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGithubCallbackSuspense<
    TData = Awaited<ReturnType<typeof githubCallback>>,
    TError = void,
>(
    params?: GithubCallbackParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof githubCallback>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGithubCallbackSuspense<
    TData = Awaited<ReturnType<typeof githubCallback>>,
    TError = void,
>(
    params?: GithubCallbackParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof githubCallback>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Handle GitHub OAuth callback
 */

export function useGithubCallbackSuspense<
    TData = Awaited<ReturnType<typeof githubCallback>>,
    TError = void,
>(
    params?: GithubCallbackParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof githubCallback>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGithubCallbackSuspenseQueryOptions(params, options);

    const query = useSuspenseQuery(
        queryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return withQueryKey(query, queryOptions.queryKey);
}

export type googleLoginResponse302 = {
    data: void;
    status: 302;
};
export type googleLoginResponseError = googleLoginResponse302 & {
    headers: Headers;
};

export type googleLoginResponse = googleLoginResponseError;

export const getGoogleLoginUrl = () => {
    return `/api/auth/google`;
};

/**
 * @summary Redirect to Google OAuth
 */
export const googleLogin = async (
    options?: Parameters<typeof customFetch>[1],
): Promise<googleLoginResponse> => {
    return customFetch<googleLoginResponse>(getGoogleLoginUrl(), {
        ...options,
        method: "GET",
    });
};

export const getGoogleLoginQueryKey = () => {
    return [`/api/auth/google`] as const;
};

export const getGoogleLoginQueryOptions = <
    TData = Awaited<ReturnType<typeof googleLogin>>,
    TError = void,
>(options?: {
    query?: Partial<
        UseQueryOptions<Awaited<ReturnType<typeof googleLogin>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGoogleLoginQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof googleLogin>>> = ({
        signal,
    }) => googleLogin({ signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof googleLogin>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GoogleLoginQueryResult = NonNullable<
    Awaited<ReturnType<typeof googleLogin>>
>;
export type GoogleLoginQueryError = void;

export function useGoogleLogin<
    TData = Awaited<ReturnType<typeof googleLogin>>,
    TError = void,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof googleLogin>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof googleLogin>>,
                    TError,
                    Awaited<ReturnType<typeof googleLogin>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGoogleLogin<
    TData = Awaited<ReturnType<typeof googleLogin>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof googleLogin>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof googleLogin>>,
                    TError,
                    Awaited<ReturnType<typeof googleLogin>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGoogleLogin<
    TData = Awaited<ReturnType<typeof googleLogin>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof googleLogin>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Redirect to Google OAuth
 */

export function useGoogleLogin<
    TData = Awaited<ReturnType<typeof googleLogin>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof googleLogin>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGoogleLoginQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return withQueryKey(query, queryOptions.queryKey);
}

export const getGoogleLoginSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof googleLogin>>,
    TError = void,
>(options?: {
    query?: Partial<
        UseSuspenseQueryOptions<
            Awaited<ReturnType<typeof googleLogin>>,
            TError,
            TData
        >
    >;
    request?: SecondParameter<typeof customFetch>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGoogleLoginQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof googleLogin>>> = ({
        signal,
    }) => googleLogin({ signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof googleLogin>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GoogleLoginSuspenseQueryResult = NonNullable<
    Awaited<ReturnType<typeof googleLogin>>
>;
export type GoogleLoginSuspenseQueryError = void;

export function useGoogleLoginSuspense<
    TData = Awaited<ReturnType<typeof googleLogin>>,
    TError = void,
>(
    options: {
        query: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof googleLogin>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGoogleLoginSuspense<
    TData = Awaited<ReturnType<typeof googleLogin>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof googleLogin>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGoogleLoginSuspense<
    TData = Awaited<ReturnType<typeof googleLogin>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof googleLogin>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Redirect to Google OAuth
 */

export function useGoogleLoginSuspense<
    TData = Awaited<ReturnType<typeof googleLogin>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof googleLogin>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGoogleLoginSuspenseQueryOptions(options);

    const query = useSuspenseQuery(
        queryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return withQueryKey(query, queryOptions.queryKey);
}

export type googleCallbackResponse302 = {
    data: void;
    status: 302;
};
export type googleCallbackResponseError = googleCallbackResponse302 & {
    headers: Headers;
};

export type googleCallbackResponse = googleCallbackResponseError;

export const getGoogleCallbackUrl = (params?: GoogleCallbackParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(
                key,
                value === null ? "null" : String(value),
            );
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/api/auth/google/callback?${stringifiedParams}`
        : `/api/auth/google/callback`;
};

/**
 * @summary Handle Google OAuth callback
 */
export const googleCallback = async (
    params?: GoogleCallbackParams,
    options?: Parameters<typeof customFetch>[1],
): Promise<googleCallbackResponse> => {
    return customFetch<googleCallbackResponse>(getGoogleCallbackUrl(params), {
        ...options,
        method: "GET",
    });
};

export const getGoogleCallbackQueryKey = (params?: GoogleCallbackParams) => {
    return [`/api/auth/google/callback`, ...(params ? [params] : [])] as const;
};

export const getGoogleCallbackQueryOptions = <
    TData = Awaited<ReturnType<typeof googleCallback>>,
    TError = void,
>(
    params?: GoogleCallbackParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof googleCallback>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getGoogleCallbackQueryKey(params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof googleCallback>>
    > = ({ signal }) => googleCallback(params, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof googleCallback>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GoogleCallbackQueryResult = NonNullable<
    Awaited<ReturnType<typeof googleCallback>>
>;
export type GoogleCallbackQueryError = void;

export function useGoogleCallback<
    TData = Awaited<ReturnType<typeof googleCallback>>,
    TError = void,
>(
    params: undefined | GoogleCallbackParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof googleCallback>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof googleCallback>>,
                    TError,
                    Awaited<ReturnType<typeof googleCallback>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGoogleCallback<
    TData = Awaited<ReturnType<typeof googleCallback>>,
    TError = void,
>(
    params?: GoogleCallbackParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof googleCallback>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof googleCallback>>,
                    TError,
                    Awaited<ReturnType<typeof googleCallback>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGoogleCallback<
    TData = Awaited<ReturnType<typeof googleCallback>>,
    TError = void,
>(
    params?: GoogleCallbackParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof googleCallback>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Handle Google OAuth callback
 */

export function useGoogleCallback<
    TData = Awaited<ReturnType<typeof googleCallback>>,
    TError = void,
>(
    params?: GoogleCallbackParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof googleCallback>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGoogleCallbackQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return withQueryKey(query, queryOptions.queryKey);
}

export const getGoogleCallbackSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof googleCallback>>,
    TError = void,
>(
    params?: GoogleCallbackParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof googleCallback>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getGoogleCallbackQueryKey(params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof googleCallback>>
    > = ({ signal }) => googleCallback(params, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof googleCallback>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GoogleCallbackSuspenseQueryResult = NonNullable<
    Awaited<ReturnType<typeof googleCallback>>
>;
export type GoogleCallbackSuspenseQueryError = void;

export function useGoogleCallbackSuspense<
    TData = Awaited<ReturnType<typeof googleCallback>>,
    TError = void,
>(
    params: undefined | GoogleCallbackParams,
    options: {
        query: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof googleCallback>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGoogleCallbackSuspense<
    TData = Awaited<ReturnType<typeof googleCallback>>,
    TError = void,
>(
    params?: GoogleCallbackParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof googleCallback>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGoogleCallbackSuspense<
    TData = Awaited<ReturnType<typeof googleCallback>>,
    TError = void,
>(
    params?: GoogleCallbackParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof googleCallback>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Handle Google OAuth callback
 */

export function useGoogleCallbackSuspense<
    TData = Awaited<ReturnType<typeof googleCallback>>,
    TError = void,
>(
    params?: GoogleCallbackParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof googleCallback>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGoogleCallbackSuspenseQueryOptions(params, options);

    const query = useSuspenseQuery(
        queryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return withQueryKey(query, queryOptions.queryKey);
}

export type loginResponse200 = {
    data: AuthResponse;
    status: 200;
};

export type loginResponse400 = {
    data: void;
    status: 400;
};

export type loginResponse401 = {
    data: void;
    status: 401;
};

export type loginResponse403 = {
    data: void;
    status: 403;
};

export type loginResponseSuccess = loginResponse200 & {
    headers: Headers;
};
export type loginResponseError = (
    | loginResponse400
    | loginResponse401
    | loginResponse403
) & {
    headers: Headers;
};

export const getLoginUrl = () => {
    return `/api/auth/login`;
};

/**
 * @summary Log in with email and password
 */
export const login = async (
    loginRequest: LoginRequest,
    options?: Parameters<typeof customFetch>[1],
): Promise<loginResponseSuccess> => {
    return customFetch<loginResponseSuccess>(getLoginUrl(), {
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(loginRequest),
    });
};

export const getLoginMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof login>>,
        TError,
        { data: LoginRequest },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof login>>,
    TError,
    { data: LoginRequest },
    TContext
> => {
    const mutationKey = ["login"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof login>>,
        { data: LoginRequest }
    > = (props) => {
        const { data } = props ?? {};

        return login(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type LoginMutationResult = NonNullable<
    Awaited<ReturnType<typeof login>>
>;
export type LoginMutationBody = LoginRequest;
export type LoginMutationError = void;

/**
 * @summary Log in with email and password
 */
export const useLogin = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof login>>,
            TError,
            { data: LoginRequest },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof login>>,
    TError,
    { data: LoginRequest },
    TContext
> => {
    return useMutation(getLoginMutationOptions(options), queryClient);
};
export type logoutResponse200 = {
    data: MessageResponse;
    status: 200;
};

export type logoutResponseSuccess = logoutResponse200 & {
    headers: Headers;
};

export const getLogoutUrl = () => {
    return `/api/auth/logout`;
};

/**
 * @summary Log out (destroy session)
 */
export const logout = async (
    options?: Parameters<typeof customFetch>[1],
): Promise<logoutResponseSuccess> => {
    return customFetch<logoutResponseSuccess>(getLogoutUrl(), {
        ...options,
        method: "POST",
    });
};

export const getLogoutMutationOptions = <
    TError = unknown,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof logout>>,
        TError,
        void,
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof logout>>,
    TError,
    void,
    TContext
> => {
    const mutationKey = ["logout"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof logout>>,
        void
    > = () => {
        return logout(requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type LogoutMutationResult = NonNullable<
    Awaited<ReturnType<typeof logout>>
>;

export type LogoutMutationError = unknown;

/**
 * @summary Log out (destroy session)
 */
export const useLogout = <TError = unknown, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof logout>>,
            TError,
            void,
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof logout>>,
    TError,
    void,
    TContext
> => {
    return useMutation(getLogoutMutationOptions(options), queryClient);
};
export type meResponse200 = {
    data: AuthResponse;
    status: 200;
};

export type meResponse401 = {
    data: void;
    status: 401;
};

export type meResponseSuccess = meResponse200 & {
    headers: Headers;
};
export type meResponseError = meResponse401 & {
    headers: Headers;
};

export const getMeUrl = () => {
    return `/api/auth/me`;
};

/**
 * @summary Get current authenticated user
 */
export const me = async (
    options?: Parameters<typeof customFetch>[1],
): Promise<meResponseSuccess> => {
    return customFetch<meResponseSuccess>(getMeUrl(), {
        ...options,
        method: "GET",
    });
};

export const getMeQueryKey = () => {
    return [`/api/auth/me`] as const;
};

export const getMeQueryOptions = <
    TData = Awaited<ReturnType<typeof me>>,
    TError = void,
>(options?: {
    query?: Partial<
        UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getMeQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof me>>> = ({
        signal,
    }) => me({ signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof me>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MeQueryResult = NonNullable<Awaited<ReturnType<typeof me>>>;
export type MeQueryError = void;

export function useMe<TData = Awaited<ReturnType<typeof me>>, TError = void>(
    options: {
        query: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof me>>,
                    TError,
                    Awaited<ReturnType<typeof me>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMe<TData = Awaited<ReturnType<typeof me>>, TError = void>(
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof me>>,
                    TError,
                    Awaited<ReturnType<typeof me>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMe<TData = Awaited<ReturnType<typeof me>>, TError = void>(
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get current authenticated user
 */

export function useMe<TData = Awaited<ReturnType<typeof me>>, TError = void>(
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getMeQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return withQueryKey(query, queryOptions.queryKey);
}

export const getMeSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof me>>,
    TError = void,
>(options?: {
    query?: Partial<
        UseSuspenseQueryOptions<Awaited<ReturnType<typeof me>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getMeQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof me>>> = ({
        signal,
    }) => me({ signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof me>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MeSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof me>>>;
export type MeSuspenseQueryError = void;

export function useMeSuspense<
    TData = Awaited<ReturnType<typeof me>>,
    TError = void,
>(
    options: {
        query: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof me>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMeSuspense<
    TData = Awaited<ReturnType<typeof me>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof me>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMeSuspense<
    TData = Awaited<ReturnType<typeof me>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof me>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get current authenticated user
 */

export function useMeSuspense<
    TData = Awaited<ReturnType<typeof me>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof me>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getMeSuspenseQueryOptions(options);

    const query = useSuspenseQuery(
        queryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return withQueryKey(query, queryOptions.queryKey);
}

export type getProfileResponse200 = {
    data: ProfileResponse;
    status: 200;
};

export type getProfileResponse401 = {
    data: void;
    status: 401;
};

export type getProfileResponseSuccess = getProfileResponse200 & {
    headers: Headers;
};
export type getProfileResponseError = getProfileResponse401 & {
    headers: Headers;
};

export const getGetProfileUrl = () => {
    return `/api/auth/profile`;
};

/**
 * @summary Get current user's profile with linked providers
 */
export const getProfile = async (
    options?: Parameters<typeof customFetch>[1],
): Promise<getProfileResponseSuccess> => {
    return customFetch<getProfileResponseSuccess>(getGetProfileUrl(), {
        ...options,
        method: "GET",
    });
};

export const getGetProfileQueryKey = () => {
    return [`/api/auth/profile`] as const;
};

export const getGetProfileQueryOptions = <
    TData = Awaited<ReturnType<typeof getProfile>>,
    TError = void,
>(options?: {
    query?: Partial<
        UseQueryOptions<Awaited<ReturnType<typeof getProfile>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetProfileQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProfile>>> = ({
        signal,
    }) => getProfile({ signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getProfile>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProfileQueryResult = NonNullable<
    Awaited<ReturnType<typeof getProfile>>
>;
export type GetProfileQueryError = void;

export function useGetProfile<
    TData = Awaited<ReturnType<typeof getProfile>>,
    TError = void,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getProfile>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getProfile>>,
                    TError,
                    Awaited<ReturnType<typeof getProfile>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProfile<
    TData = Awaited<ReturnType<typeof getProfile>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getProfile>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getProfile>>,
                    TError,
                    Awaited<ReturnType<typeof getProfile>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProfile<
    TData = Awaited<ReturnType<typeof getProfile>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getProfile>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get current user's profile with linked providers
 */

export function useGetProfile<
    TData = Awaited<ReturnType<typeof getProfile>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getProfile>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetProfileQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return withQueryKey(query, queryOptions.queryKey);
}

export const getGetProfileSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof getProfile>>,
    TError = void,
>(options?: {
    query?: Partial<
        UseSuspenseQueryOptions<
            Awaited<ReturnType<typeof getProfile>>,
            TError,
            TData
        >
    >;
    request?: SecondParameter<typeof customFetch>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetProfileQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProfile>>> = ({
        signal,
    }) => getProfile({ signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getProfile>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProfileSuspenseQueryResult = NonNullable<
    Awaited<ReturnType<typeof getProfile>>
>;
export type GetProfileSuspenseQueryError = void;

export function useGetProfileSuspense<
    TData = Awaited<ReturnType<typeof getProfile>>,
    TError = void,
>(
    options: {
        query: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof getProfile>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProfileSuspense<
    TData = Awaited<ReturnType<typeof getProfile>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof getProfile>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProfileSuspense<
    TData = Awaited<ReturnType<typeof getProfile>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof getProfile>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get current user's profile with linked providers
 */

export function useGetProfileSuspense<
    TData = Awaited<ReturnType<typeof getProfile>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof getProfile>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetProfileSuspenseQueryOptions(options);

    const query = useSuspenseQuery(
        queryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return withQueryKey(query, queryOptions.queryKey);
}

export type updateProfileResponse200 = {
    data: MessageResponse;
    status: 200;
};

export type updateProfileResponse400 = {
    data: void;
    status: 400;
};

export type updateProfileResponse401 = {
    data: void;
    status: 401;
};

export type updateProfileResponse409 = {
    data: void;
    status: 409;
};

export type updateProfileResponseSuccess = updateProfileResponse200 & {
    headers: Headers;
};
export type updateProfileResponseError = (
    | updateProfileResponse400
    | updateProfileResponse401
    | updateProfileResponse409
) & {
    headers: Headers;
};

export const getUpdateProfileUrl = () => {
    return `/api/auth/profile`;
};

/**
 * @summary Update display name
 */
export const updateProfile = async (
    updateProfileRequest: UpdateProfileRequest,
    options?: Parameters<typeof customFetch>[1],
): Promise<updateProfileResponseSuccess> => {
    return customFetch<updateProfileResponseSuccess>(getUpdateProfileUrl(), {
        ...options,
        method: "PUT",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(updateProfileRequest),
    });
};

export const getUpdateProfileMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof updateProfile>>,
        TError,
        { data: UpdateProfileRequest },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof updateProfile>>,
    TError,
    { data: UpdateProfileRequest },
    TContext
> => {
    const mutationKey = ["updateProfile"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof updateProfile>>,
        { data: UpdateProfileRequest }
    > = (props) => {
        const { data } = props ?? {};

        return updateProfile(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type UpdateProfileMutationResult = NonNullable<
    Awaited<ReturnType<typeof updateProfile>>
>;
export type UpdateProfileMutationBody = UpdateProfileRequest;
export type UpdateProfileMutationError = void;

/**
 * @summary Update display name
 */
export const useUpdateProfile = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof updateProfile>>,
            TError,
            { data: UpdateProfileRequest },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof updateProfile>>,
    TError,
    { data: UpdateProfileRequest },
    TContext
> => {
    return useMutation(getUpdateProfileMutationOptions(options), queryClient);
};
export type registerResponse201 = {
    data: MessageResponse;
    status: 201;
};

export type registerResponse400 = {
    data: void;
    status: 400;
};

export type registerResponse503 = {
    data: void;
    status: 503;
};

export type registerResponseSuccess = registerResponse201 & {
    headers: Headers;
};
export type registerResponseError = (
    | registerResponse400
    | registerResponse503
) & {
    headers: Headers;
};

export const getRegisterUrl = () => {
    return `/api/auth/register`;
};

/**
 * @summary Register a new user with email and password
 */
export const register = async (
    registerRequest: RegisterRequest,
    options?: Parameters<typeof customFetch>[1],
): Promise<registerResponseSuccess> => {
    return customFetch<registerResponseSuccess>(getRegisterUrl(), {
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(registerRequest),
    });
};

export const getRegisterMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof register>>,
        TError,
        { data: RegisterRequest },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof register>>,
    TError,
    { data: RegisterRequest },
    TContext
> => {
    const mutationKey = ["register"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof register>>,
        { data: RegisterRequest }
    > = (props) => {
        const { data } = props ?? {};

        return register(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type RegisterMutationResult = NonNullable<
    Awaited<ReturnType<typeof register>>
>;
export type RegisterMutationBody = RegisterRequest;
export type RegisterMutationError = void;

/**
 * @summary Register a new user with email and password
 */
export const useRegister = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof register>>,
            TError,
            { data: RegisterRequest },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof register>>,
    TError,
    { data: RegisterRequest },
    TContext
> => {
    return useMutation(getRegisterMutationOptions(options), queryClient);
};
export type requestPasswordChangeResponse200 = {
    data: MessageResponse;
    status: 200;
};

export type requestPasswordChangeResponse400 = {
    data: void;
    status: 400;
};

export type requestPasswordChangeResponse401 = {
    data: void;
    status: 401;
};

export type requestPasswordChangeResponseSuccess =
    requestPasswordChangeResponse200 & {
        headers: Headers;
    };
export type requestPasswordChangeResponseError = (
    | requestPasswordChangeResponse400
    | requestPasswordChangeResponse401
) & {
    headers: Headers;
};

export const getRequestPasswordChangeUrl = () => {
    return `/api/auth/request-password-change`;
};

/**
 * @summary Request a password change email (for authenticated users)
 */
export const requestPasswordChange = async (
    options?: Parameters<typeof customFetch>[1],
): Promise<requestPasswordChangeResponseSuccess> => {
    return customFetch<requestPasswordChangeResponseSuccess>(
        getRequestPasswordChangeUrl(),
        {
            ...options,
            method: "POST",
        },
    );
};

export const getRequestPasswordChangeMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof requestPasswordChange>>,
        TError,
        void,
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof requestPasswordChange>>,
    TError,
    void,
    TContext
> => {
    const mutationKey = ["requestPasswordChange"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof requestPasswordChange>>,
        void
    > = () => {
        return requestPasswordChange(requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type RequestPasswordChangeMutationResult = NonNullable<
    Awaited<ReturnType<typeof requestPasswordChange>>
>;

export type RequestPasswordChangeMutationError = void;

/**
 * @summary Request a password change email (for authenticated users)
 */
export const useRequestPasswordChange = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof requestPasswordChange>>,
            TError,
            void,
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof requestPasswordChange>>,
    TError,
    void,
    TContext
> => {
    return useMutation(
        getRequestPasswordChangeMutationOptions(options),
        queryClient,
    );
};
export type resetPasswordResponse200 = {
    data: MessageResponse;
    status: 200;
};

export type resetPasswordResponse400 = {
    data: void;
    status: 400;
};

export type resetPasswordResponseSuccess = resetPasswordResponse200 & {
    headers: Headers;
};
export type resetPasswordResponseError = resetPasswordResponse400 & {
    headers: Headers;
};

export const getResetPasswordUrl = () => {
    return `/api/auth/reset-password`;
};

/**
 * @summary Reset password using a token
 */
export const resetPassword = async (
    resetPasswordRequest: ResetPasswordRequest,
    options?: Parameters<typeof customFetch>[1],
): Promise<resetPasswordResponseSuccess> => {
    return customFetch<resetPasswordResponseSuccess>(getResetPasswordUrl(), {
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(resetPasswordRequest),
    });
};

export const getResetPasswordMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof resetPassword>>,
        TError,
        { data: ResetPasswordRequest },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof resetPassword>>,
    TError,
    { data: ResetPasswordRequest },
    TContext
> => {
    const mutationKey = ["resetPassword"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof resetPassword>>,
        { data: ResetPasswordRequest }
    > = (props) => {
        const { data } = props ?? {};

        return resetPassword(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type ResetPasswordMutationResult = NonNullable<
    Awaited<ReturnType<typeof resetPassword>>
>;
export type ResetPasswordMutationBody = ResetPasswordRequest;
export type ResetPasswordMutationError = void;

/**
 * @summary Reset password using a token
 */
export const useResetPassword = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof resetPassword>>,
            TError,
            { data: ResetPasswordRequest },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof resetPassword>>,
    TError,
    { data: ResetPasswordRequest },
    TContext
> => {
    return useMutation(getResetPasswordMutationOptions(options), queryClient);
};
export type verifyEmailResponse302 = {
    data: void;
    status: 302;
};
export type verifyEmailResponseError = verifyEmailResponse302 & {
    headers: Headers;
};

export type verifyEmailResponse = verifyEmailResponseError;

export const getVerifyEmailUrl = (params: VerifyEmailParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(
                key,
                value === null ? "null" : String(value),
            );
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/api/auth/verify-email?${stringifiedParams}`
        : `/api/auth/verify-email`;
};

/**
 * @summary Verify email using a token
 */
export const verifyEmail = async (
    params: VerifyEmailParams,
    options?: Parameters<typeof customFetch>[1],
): Promise<verifyEmailResponse> => {
    return customFetch<verifyEmailResponse>(getVerifyEmailUrl(params), {
        ...options,
        method: "GET",
    });
};

export const getVerifyEmailQueryKey = (params?: VerifyEmailParams) => {
    return [`/api/auth/verify-email`, ...(params ? [params] : [])] as const;
};

export const getVerifyEmailQueryOptions = <
    TData = Awaited<ReturnType<typeof verifyEmail>>,
    TError = void,
>(
    params: VerifyEmailParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof verifyEmail>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getVerifyEmailQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof verifyEmail>>> = ({
        signal,
    }) => verifyEmail(params, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof verifyEmail>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type VerifyEmailQueryResult = NonNullable<
    Awaited<ReturnType<typeof verifyEmail>>
>;
export type VerifyEmailQueryError = void;

export function useVerifyEmail<
    TData = Awaited<ReturnType<typeof verifyEmail>>,
    TError = void,
>(
    params: VerifyEmailParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof verifyEmail>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof verifyEmail>>,
                    TError,
                    Awaited<ReturnType<typeof verifyEmail>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useVerifyEmail<
    TData = Awaited<ReturnType<typeof verifyEmail>>,
    TError = void,
>(
    params: VerifyEmailParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof verifyEmail>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof verifyEmail>>,
                    TError,
                    Awaited<ReturnType<typeof verifyEmail>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useVerifyEmail<
    TData = Awaited<ReturnType<typeof verifyEmail>>,
    TError = void,
>(
    params: VerifyEmailParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof verifyEmail>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Verify email using a token
 */

export function useVerifyEmail<
    TData = Awaited<ReturnType<typeof verifyEmail>>,
    TError = void,
>(
    params: VerifyEmailParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof verifyEmail>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getVerifyEmailQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return withQueryKey(query, queryOptions.queryKey);
}

export const getVerifyEmailSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof verifyEmail>>,
    TError = void,
>(
    params: VerifyEmailParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof verifyEmail>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getVerifyEmailQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof verifyEmail>>> = ({
        signal,
    }) => verifyEmail(params, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof verifyEmail>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type VerifyEmailSuspenseQueryResult = NonNullable<
    Awaited<ReturnType<typeof verifyEmail>>
>;
export type VerifyEmailSuspenseQueryError = void;

export function useVerifyEmailSuspense<
    TData = Awaited<ReturnType<typeof verifyEmail>>,
    TError = void,
>(
    params: VerifyEmailParams,
    options: {
        query: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof verifyEmail>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useVerifyEmailSuspense<
    TData = Awaited<ReturnType<typeof verifyEmail>>,
    TError = void,
>(
    params: VerifyEmailParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof verifyEmail>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useVerifyEmailSuspense<
    TData = Awaited<ReturnType<typeof verifyEmail>>,
    TError = void,
>(
    params: VerifyEmailParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof verifyEmail>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Verify email using a token
 */

export function useVerifyEmailSuspense<
    TData = Awaited<ReturnType<typeof verifyEmail>>,
    TError = void,
>(
    params: VerifyEmailParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof verifyEmail>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getVerifyEmailSuspenseQueryOptions(params, options);

    const query = useSuspenseQuery(
        queryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return withQueryKey(query, queryOptions.queryKey);
}
