/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */
import type { ReviewParticipant } from "./reviewParticipant.ts";

export interface ArticleReviewCommentResponse {
    /** @nullable */
    block_index?: number | null;
    body: string;
    created_at: string;
    id: string;
    /** @nullable */
    parent_id?: string | null;
    /** @nullable */
    quoted_text?: string | null;
    request_id: string;
    /** @nullable */
    resolved_at?: string | null;
    sender?: null | ReviewParticipant;
    /** @nullable */
    sentence_end?: number | null;
    /** @nullable */
    sentence_start?: number | null;
}
