/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */
import type { ArticleReviewCommentResponse } from "./articleReviewCommentResponse.ts";

export interface ArticleReviewCommentListResponse {
    comments: ArticleReviewCommentResponse[];
}
