/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

/**
 * A cheap change-detection stamp for the review page's polling: the
 * client treats the whole object as an opaque token and invalidates
 * its queries when any field changes. Counts alone would miss
 * un-resolving a comment; timestamps alone would miss deletions.
 */
export interface ArticleReviewActivityResponse {
    comments: number;
    messages: number;
    requests_updated_at: string;
    resolved_comments: number;
}
