/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export interface AssignReviewRequest {
    /**
     * Editor to assign, or null/omitted to unassign.
     * @nullable
     */
    assignee_id?: string | null;
}
