/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */
import type { CitationPart } from "./citationPart.ts";
import type { SentenceData } from "./sentenceData.ts";
import type { SourceContext } from "./sourceContext.ts";

export interface BatchSentenceResponseItem {
    book_slug: string;
    book_title: string;
    /**
     * Resolved citation parts (ordered by `cite_priority`). Empty = no
     * default citation system; the card falls back to `s. N`.
     */
    citation: CitationPart[];
    node_label: string;
    node_slug: string;
    /**
     * Label of the cited node's parent in the toc tree, when one
     * exists. For bibles this is the bible-book ("Romans"); for Milton
     * the work ("Paradise Lost"). Substituted into `{parent}` of a
     * citation template.
     * @nullable
     */
    parent_node_label?: string | null;
    sentences: SentenceData[];
    source?: null | SourceContext;
}
