/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export type BrowseSourcesParams = {
    /**
     * @nullable
     */
    q?: string | null;
    /**
     * @nullable
     */
    source_type?: string | null;
    /**
     * @nullable
     */
    created_by_me?: boolean | null;
    /**
     * @nullable
     */
    protected?: boolean | null;
    /**
     * @nullable
     */
    page?: number | null;
    /**
     * @nullable
     */
    per_page?: number | null;
};
