/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */
import type { SentenceResponse } from "./sentenceResponse.ts";

export interface ContentBlockResponse {
    block_type: string;
    /** @nullable */
    figure_number?: number | null;
    html: string;
    id: string;
    /** @nullable */
    original_html?: string | null;
    /** @nullable */
    paragraph_number?: number | null;
    position: number;
    sentences: SentenceResponse[];
}
