/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export interface CreateFeedbackRequest {
    body: string;
    /**
     * Optional. Full URL (path + query) the user was on when submitting.
     * @nullable
     */
    url?: string | null;
    /** @nullable */
    user_agent?: string | null;
    /** @nullable */
    viewport_h?: number | null;
    /** @nullable */
    viewport_w?: number | null;
}
