/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */
import type { ResourceScope } from "./resourceScope.ts";
import type { ResourceType } from "./resourceType.ts";
import type { SentenceKind } from "./sentenceKind.ts";
import type { VerbatimKind } from "./verbatimKind.ts";

export interface CreateResourceRequest {
    /** @nullable */
    admin_notes?: string | null;
    /** @nullable */
    editor_note?: string | null;
    /** @nullable */
    is_featured?: boolean | null;
    /** @nullable */
    quoted_text?: string | null;
    resource_type: ResourceType;
    scope?: null | ResourceScope;
    /** @nullable */
    sentence_end?: number | null;
    sentence_kind: SentenceKind;
    sentence_start: number;
    /** @nullable */
    source_id?: string | null;
    /** @nullable */
    source_location_freeform?: string | null;
    /** @nullable */
    source_page_end?: number | null;
    /** @nullable */
    source_page_start?: number | null;
    verbatim_kind?: null | VerbatimKind;
}
