/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

/**
 * `slug` is generated from the name at creation and immutable after —
 * it appears in shareable URLs (`/articles?topic_slug=…`).
 */
export interface CreateTopicRequest {
    name: string;
}
