/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export interface CreateCheckoutResponse {
    /** Pass to the Stripe Embedded Checkout React component. */
    client_secret: string;
}
