/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */
import type { ReviewVisibility } from "./reviewVisibility.ts";

export interface CreateCollegiumRequest {
    /** @nullable */
    description?: string | null;
    /** @nullable */
    is_private?: boolean | null;
    name: string;
    review_visibility?: null | ReviewVisibility;
}
