/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */
import type { ReviewIntent } from "./reviewIntent.ts";

export interface CreateReviewRequestRequest {
    /**
     * Review audience: a collegium the author belongs to, or absent for the
     * editorial team. Collegium reviews are feedback-only.
     * @nullable
     */
    collegium_id?: string | null;
    /**
     * `feedback` — the author wants comments; the reviewing side closes
     * the request as `resolved`. `publication` — a hand-off to the
     * editors: approving publishes the article (if still a draft) and
     * applies the `imprimatur` label.
     */
    intent: ReviewIntent;
    /**
     * Optional note posted as the first message in the article's
     * review channel.
     * @nullable
     */
    message?: string | null;
}
