/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */
import type { EditorialLabelResponse } from "./editorialLabelResponse.ts";

export interface EditorialLabelListResponse {
    labels: EditorialLabelResponse[];
}
