/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export type GetNodeParams = {
    /**
     * include original_text/original_html fields
     * @nullable
     */
    original?: boolean | null;
};
