/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export type GoogleCallbackParams = {
    /**
     * Authorization code
     */
    code?: string;
    /**
     * CSRF state
     */
    state?: string;
    /**
     * Provider-side error (e.g. user cancelled)
     */
    error?: string;
};
