/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export interface InviteTokenResponse {
    /** @nullable */
    invite_token?: string | null;
}
