/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export type JoinRequestDecision =
    (typeof JoinRequestDecision)[keyof typeof JoinRequestDecision];

export const JoinRequestDecision = {
    approved: "approved",
    rejected: "rejected",
} as const;
