/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export interface LinkSourcePersonRequest {
    person_id: string;
    /** @nullable */
    position?: number | null;
    role: string;
}
