/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export type ListAllQuotationsParams = {
    /**
     * @nullable
     */
    book_slug?: string | null;
    /**
     * @nullable
     */
    source_type?: string | null;
};
