/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export type ListArticleReferencesParams = {
    start: number;
    end: number;
    kind?: string;
    /**
     * @nullable
     */
    limit?: number | null;
    /**
     * @nullable
     */
    offset?: number | null;
};
