/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export type ListPublishedArticlesParams = {
    /**
     * @nullable
     */
    topic_slug?: string | null;
    /**
     * Filter the listing to articles bearing this editorial label slug
     * (e.g. `featured`, `high-quality`).
     * @nullable
     */
    label_slug?: string | null;
    /**
     * Case-insensitive contains-match on the article title.
     * @nullable
     */
    q?: string | null;
    /**
     * Case-insensitive contains-match on the author's display name or
     * handle.
     * @nullable
     */
    author?: string | null;
    /**
     * @nullable
     */
    page?: number | null;
    /**
     * @nullable
     */
    per_page?: number | null;
};
