/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export type ListArticleReviewQueueParams = {
    /**
     * `pending` (default) | `approved` | `declined` | `resolved` | `all`.
     * @nullable
     */
    filter?: string | null;
    /**
     * Filter by assignee: a reviewer's user id, or `unassigned`.
     * Absent = everyone.
     * @nullable
     */
    assignee?: string | null;
    /**
     * @nullable
     */
    page?: number | null;
    /**
     * @nullable
     */
    per_page?: number | null;
};
