/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export type ListResourceSubmissionsParams = {
    /**
     * Filter set: "pending" (default), "all", "approved", or "rejected".
     * @nullable
     */
    filter?: string | null;
    /**
     * @minimum 0
     * @nullable
     */
    page?: number | null;
    /**
     * @minimum 0
     * @nullable
     */
    per_page?: number | null;
};
