/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export type ListFeedbackParams = {
    /**
 * Filter set: "active" (todo + in_progress, default), "all", or a
specific status name ("todo", "in_progress", "done", "cancelled").
 * @nullable
 */
    filter?: string | null;
    /**
     * @minimum 0
     * @nullable
     */
    page?: number | null;
    /**
     * @minimum 0
     * @nullable
     */
    per_page?: number | null;
};
