/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */
import type { PassageArticleResponse } from "./passageArticleResponse.ts";

export interface PassageArticleListResponse {
    articles: PassageArticleResponse[];
    total: number;
}
