/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export interface PersonResponse {
    created_by: string;
    id: string;
    name: string;
    protected: boolean;
    /** @nullable */
    sort_name?: string | null;
}
