/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export interface ReferencedArticle {
    id: string;
    is_mine: boolean;
    slug: string;
    status: string;
    title: string;
}
