/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */
import type { ReferencedChildSource } from "./referencedChildSource.ts";

export interface ReferencedChildSources {
    count: number;
    items: ReferencedChildSource[];
}
