/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */
import type { ReferencedArticles } from "./referencedArticles.ts";
import type { ReferencedChildSources } from "./referencedChildSources.ts";
import type { ReferencedResources } from "./referencedResources.ts";

export interface ReferenceCheckResponse {
    articles: ReferencedArticles;
    child_sources: ReferencedChildSources;
    resources: ReferencedResources;
    /** Total count across all categories. */
    total: number;
}
