/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Membership removal result; `collegium_deleted` is true when the last
 * member left and the collegium was soft-deleted.
 */
export interface RemoveMemberResponse {
    collegium_deleted: boolean;
}
