/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

/**
 * A review request's lifecycle state. Stored as the Postgres enum
 * `article_review_request_status`.
 */
export type ReviewRequestStatus =
    (typeof ReviewRequestStatus)[keyof typeof ReviewRequestStatus];

export const ReviewRequestStatus = {
    pending: "pending",
    approved: "approved",
    declined: "declined",
    resolved: "resolved",
    withdrawn: "withdrawn",
} as const;
