/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */
import type { ReviewParticipant } from "./reviewParticipant.ts";

export interface ReviewerListResponse {
    reviewers: ReviewParticipant[];
}
