/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */
import type { CollegiumRole } from "./collegiumRole.ts";

/**
 * The reviewing collegium, for the review page header, links, and action
 * gating.
 */
export interface ReviewCollegiumMeta {
    id: string;
    /**
     * This round's visibility snapshot: true = all members review
     * (writing-collegium mode), false = stewards only (classroom mode).
     */
    member_visible: boolean;
    my_role?: null | CollegiumRole;
    name: string;
    slug: string;
}
