/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */
import type { FootnoteResponse } from "./footnoteResponse.ts";
import type { PageMarkerResponse } from "./pageMarkerResponse.ts";

export interface SentenceResponse {
    /**
     * Set only on a figure's anchor sentence — drives the `fig{N}` selection key.
     * @nullable
     */
    figure_number?: number | null;
    footnotes?: FootnoteResponse[];
    html: string;
    id: string;
    /** @nullable */
    original_html?: string | null;
    /** @nullable */
    original_text?: string | null;
    page_markers: PageMarkerResponse[];
    position: number;
    /**
     * 1-based index of the indented run within the paragraph (`+ ` enumerations),
     * or absent for normal flow. Consecutive same-`segment` sentences render as
     * one hanging-indent block.
     * @nullable
     */
    segment?: number | null;
    /** @nullable */
    sentence_number?: number | null;
    /** @nullable */
    source_sentence_end_id?: string | null;
    /** @nullable */
    source_sentence_start_id?: string | null;
    text: string;
}
