/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Series row for the manage page: public fields plus member counts of
 * every status (delete is refused while `article_count` is non-zero).
 */
export interface SeriesAdminResponse {
    /** Members of any status. */
    article_count: number;
    created_at: string;
    /** @nullable */
    description?: string | null;
    id: string;
    name: string;
    pinned: boolean;
    /** Members currently visible on public series surfaces. */
    published_count: number;
    slug: string;
    sort_order: number;
    updated_at: string;
}
