/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export interface SetUserRolesRequest {
    /**
     * The full desired set of *manageable* roles for the user (see
     * `MANAGEABLE_ROLES`). Paid tiers and the default `user` role are
     * left untouched; passing a non-manageable role is rejected.
     */
    roles: string[];
}
