/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */
import type { ParentSourceResponse } from "./parentSourceResponse.ts";
import type { SourcePersonResponse } from "./sourcePersonResponse.ts";

export interface SourceResponse {
    created_by: string;
    /** @nullable */
    doi?: string | null;
    /** @nullable */
    edition?: string | null;
    id: string;
    /** @nullable */
    isbn?: string[] | null;
    /** @nullable */
    journal_name?: string | null;
    /**
     * Year of the edition this text presents, when it differs from the
     * printing transcribed (CSL "original-date"). NULL = same as
     * `publication_year`.
     * @nullable
     */
    original_year?: number | null;
    /** @nullable */
    page_end?: number | null;
    /** @nullable */
    page_start?: number | null;
    parent?: null | ParentSourceResponse;
    persons: SourcePersonResponse[];
    protected: boolean;
    /** @nullable */
    publication_place?: string | null;
    /** @nullable */
    publication_year?: number | null;
    /** @nullable */
    publisher?: string | null;
    source_type: string;
    title: string;
    /** @nullable */
    title_display?: string | null;
    /** @nullable */
    translation_of_id?: string | null;
    /** @nullable */
    url?: string | null;
    /** @nullable */
    volume?: string | null;
}
