/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export interface SourceContext {
    book_slug: string;
    book_title: string;
    node_label: string;
    node_slug: string;
}
