/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */
import type { QuotationLimitsResponse } from "./quotationLimitsResponse.ts";
import type { UnifiedQuotationResponse } from "./unifiedQuotationResponse.ts";

export interface UnifiedQuotationListResponse {
    limits: QuotationLimitsResponse;
    quotations: UnifiedQuotationResponse[];
}
