/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export type UnifiedQuotationResponse =
    | {
          /**
     * For footnote-kind anchors: the body sentence number the footnote
  is attached to. None for body-kind anchors.
     * @nullable
     */
          anchor_main_sentence_number?: number | null;
          /** @nullable */
          anchor_sentence_end_number?: number | null;
          anchor_sentence_start_number: number;
          book_slug: string;
          book_title: string;
          created_at: string;
          /** @nullable */
          end_text_snippet?: string | null;
          /** See `QuotationWithContextResponse::has_source_view`. */
          has_source_view: boolean;
          id: string;
          node_label: string;
          node_slug: string;
          note_count: number;
          sentence_kind: string;
          source_type: "book";
          /** @nullable */
          start_text_snippet?: string | null;
          /**
           * See `QuotationWithContextResponse::translation_label`.
           * @nullable
           */
          translation_label?: string | null;
      }
    | {
          /** @nullable */
          article_id?: string | null;
          article_title: string;
          author_display_name: string;
          created_at: string;
          id: string;
          note_count: number;
          source_type: "article";
          text_snippet: string;
      };
