/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Renames the display name only; the slug never changes.
 */
export interface UpdateTopicRequest {
    name: string;
}
