apiVersion: v1
kind: Secret
metadata:
    name: assets-bucket
    namespace: scholia
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:6ngo9O7zaZyWOd4QJOj/Vmd9BAg=,iv:QmY3o/mOrHyoGDmZGM9U7xRi9TSSFhTAkosakVZHErk=,tag:cAsqmIT7Wa9vqByuc9BcWw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wphlPozB6I2BZud/elIzB3e4oS8mV8O6IxemeWmWP8kR2npLyJnbBQ==,iv:vzQWP9Dm/dn28z/z2ENvqOMlh9utqoLs+lNzknFaGe4=,tag:4E7YDNmrAp8l96kn2LkYzA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXR09ORlZaNkljbG1SZHZX
            eHJISFNsSFdCT0QwU2FmQlBhL0lybVRLU21rCklaM1MvNjlGVUpiN1VwcjZuaWkv
            R3JoMjVXOGhXWVluUzZVQllNZCt0aW8KLS0tIFFPU3RSbXBqdldRWkwvby9ackZp
            QVFLaG1TQnZ0dmVJaXpuU1d5M243aFEKV0KY9tJP6XGE30oOSH33jDAeWWnt5XSK
            GkW9zUZgFpaAeuHg9s+RLN+oY4NLcCEQgkyUZGmdoaFfpiGwwDOUEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a57wpmedhxjfpc7eggf639ktpwh66pyg0r5n72gavm3w0zrrv3qq8eesn6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-20T09:10:48Z"
    mac: ENC[AES256_GCM,data:iniBGlt9KgzF9ts1ZPrSOhQnVTG3/npRsp+B+3BskqCS7TnfN0azHKcTCyIj6RnRS56SQ1FU4fekT4rFYAzLvjLnu6dit3Pzbo4CRvHoaXV2tiFyCtvftSHw6uUREoHZ+ossF0pY8pnytyZzTyFauxiCNYTaPLH8ET7dva97U8w=,iv:xpVy+28GCWwoqOhcMZGqFcs5V/wvk2bqAab9nR2x3dw=,tag:gOObglIMkiR+CnyUrPmBzQ==,type:str]
    version: 3.13.0
