apiVersion: v1
kind: Secret
metadata:
    name: ntfy
    namespace: scholia
stringData:
    NTFY_URL: ENC[AES256_GCM,data:tyvN8MKdkvJD6+2qksQ9MXoPtjZJgB7AJSC+4GF/oq5e5ysuVatF,iv:+s7VPXPnWxMUkfMDC9TiT1CDVGPbAsr1YkBUEt5Qr6o=,tag:Ku+PWNWOaJoH5a5zV6txNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNS8yN2lTbnc1bmZ6N2Rm
            RVpEWC9JeGF2MG5kMThKUmpjb3pVY1lLYkZzCm5mSnkyQ0ZIYWIwaWRMU09mNzU4
            OFUrdy85eDBNWXF5SDBvaGM4a083bFUKLS0tIHlvY2NPelNMb2VVL0xFYW9mYzRE
            UDhDWVVkYmZLUmpMRTFPZnB2WHJrVWMKWwrqRf+ozi6hikrTlYxgmZfyIgyXkq5v
            Pa+0CjBifuNCNlsZqNQED3RwWLf20zoM7YB4MqjtOu7OMsqRpDnWZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a57wpmedhxjfpc7eggf639ktpwh66pyg0r5n72gavm3w0zrrv3qq8eesn6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T23:22:33Z"
    mac: ENC[AES256_GCM,data:MWgXEtAbZUX+0147EhTmtPl5Wf2a+3PJPPCDA115U9KFUdhPTN5RVSaNT8bi0Tacy6kVBYFKy1kvjmqYVRUyA2E7mvncLZlInFnoui3/S1Pup8BrHkcW1Ow9Hv67vNbHB+ov3Dk96lV4e205FQHoz1uV2rLpG3a6DQ0kVNQGPeM=,iv:yIRiwKl6g4EZEFzgL/h0C+qaUsYTOehsP0smWiSzFbE=,tag:TbRZ47wiSZq3fitxClslyw==,type:str]
    version: 3.13.0
