apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: scholia
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:pj6WBWP3IjE=,iv:xxVhxQtl5Hj4VrSoYSK1LceEkAPF4D4z+YuyIgYpf+A=,tag:Ipis1sxMm+QkyW2WsEmc5A==,type:str]
    password: ENC[AES256_GCM,data:LFD1IEHEAFVAZVqglKa9Ek9BiC3PC+jWWEFqcm/3TEX0u0bgaDU0R5Tasa4=,iv:QVBq9Vk9O363q/N7p5+22eK3ZhSCI4hrLYxyOQpW3Ik=,tag:gL/tHvs9ooLhnFbsJjNlGw==,type:str]
    database: ENC[AES256_GCM,data:WjEgTIIA228=,iv:7PPsQTDbsmJ1Hy2ZuF12ZCSvYi/f0GbvbbbNu4xBtB8=,tag:b/v5VzOPMVhAXca+ORcxvA==,type:str]
    app_db_password: ENC[AES256_GCM,data:6UiiLQRZalye7UQ0NjlyMIK8F8/pbaiTkW1jdz1N3cQjYD3goU2jSwj8BZHaSgM+,iv:PMuOhl5DC7aXUpDv6lpowvQEaQz5+JX6cyiTe+lsznI=,tag:IeE8De4zC8usUNZz+x5EmQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZ1NJNVdDNzB1bk15RHFw
            b3Y5RERSSVkxRDZRRlZDaWsxajViN3BTN2dJClRFcFZaUDRmbXJKeXZUcE9lQzBO
            UDVvcU0yeTE0a2o1VEp6R3g2azZyTWsKLS0tIDBqZGNiYndCMkxBc1RqdFNpektX
            MXd4Q09ndS9HdElXQk8zT29ramkxUW8KcjC/QXlDz77QwWo/pMJ3GUbNSwkkw7Sz
            PvOHbOpCquPezIBVv0PTRNKGmLbnRDrnAPr2+bs+fDknk6VLV632CQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a57wpmedhxjfpc7eggf639ktpwh66pyg0r5n72gavm3w0zrrv3qq8eesn6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T11:40:53Z"
    mac: ENC[AES256_GCM,data:IuR6ggRgyryyWEq75wwEI2xaA9DnxE4GexB+jpxDPr83SnEPTtKjGrB4zqKGY5ku1K/bGufYYe0t3Dp0ezzMuC9Q+UZpdmysI/8chWkFb2RpW0FPBVphfQiGc2pz8aSQBy7Q0WVPXlVZsOQuOgCsA6pQyPkP+7GaM855aatbQDo=,iv:dThjp7Ixn/goOjha0I/P3Zv8AUxtHOkR8tV4aPmJu0o=,tag:3R/sX1cgVGbL9hjqFxhP5g==,type:str]
    version: 3.13.0
