apiVersion: v1
kind: Secret
metadata:
    name: proxy-htpasswd
    namespace: scholia
type: Opaque
stringData:
    htpasswd: ENC[AES256_GCM,data:S6rMcnl8vWj78QPxKvnp7Sj7pCGPoF/uN2tXyETn4ua3LtvXdyEPlpc7F9LUPJaqikZNHIO5hNn4lWHWB63vKnD52WWV,iv:njidePiuZGtKpu/HLB/O+/yRkeaKw7f7cHax3UPVCO4=,tag:dDnC9zoAAsdsQNTUIYxzwg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNFNSOE9vY3c4VUJmTXUy
            aVd4TS9RNjZwa1BieXQ3d2hKNHNjeW1sY0hZCkJuTWxIcUFyN25hcGlwcElzK2FW
            eTVwQmY1anJUYkd2UVRXMmJCcURoMlUKLS0tIDZCOFVDdnJwOXBMQ0RObDh2Ui9D
            VnRsSm1mVFdsd29PM1Q5ZkdQakJ3czgK2v7MZapEithivCVXV+PD6skWna3eBuSi
            oNmafiSTEmcEPVtY+4qqGi6HNB+MS+PDuKXCSsVdhgossnt4eWyjgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a57wpmedhxjfpc7eggf639ktpwh66pyg0r5n72gavm3w0zrrv3qq8eesn6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T12:46:17Z"
    mac: ENC[AES256_GCM,data:UaX8jSlEeJcEPEp3oflhIvcHMrA9S5sz4268N+u+ch/8dDL6HaWQD1tkbXaQktDauk4z2BL6XLatqu+BRTndcOk7KWL1IotAJwkj7Fr24ZS5reF854N45ienOz5hNzUy+3UVGGzk2rmMrBbe/C1YjuzZpWAfFzdUHgo0aw0Ah8U=,iv:CtI3k3b0x0LhWjoN6avN92V1TbeWoVk71MfeIHsuJSU=,tag:jgZuylpE4CHwOMv9REjefg==,type:str]
    version: 3.13.0
