apiVersion: v1
kind: Secret
metadata:
    name: turnstile
    namespace: scholia
stringData:
    TURNSTILE_SECRET_KEY: ENC[AES256_GCM,data:3MTk7svS3caaKuI7cahdKQMtzRB9xbiFtc7IDuvCfV5WFyo=,iv:J+Jk8qJqBOwtzt9aqsPERPW1ylyJZn/WUWPI7pBULz0=,tag:8QfyJ5eWSV5sPh1p4SJ4vA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSlJhMmRvSGxaSWpKa3lC
            cXh3T09CT1dwRFEwejNNeDltU0I3TlpOZjEwCnNYVVVhcnRnK21tZnY0V1NrQnJV
            MXpvT09idHExdENEZG1qQlJVT2s0SWsKLS0tIG03d3JiK2k3RmJRcjBNbzQyL0tZ
            V0phUmpOR003WFUwTGIyRWMwaXRQMDQKUXdXMJHMkPt/vJhV++MjX5dYtW/t0iXT
            MmSqg7wl67rUvTCeGM6+8GHvY4HrKiKEWLnNfvCFm9nRooILrlFr3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a57wpmedhxjfpc7eggf639ktpwh66pyg0r5n72gavm3w0zrrv3qq8eesn6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T15:40:24Z"
    mac: ENC[AES256_GCM,data:EleVlY6GUkB+Xp9Hv4JgO8EuxjSOz1br/Lft2ncCJDR3q6miA3gEflqzTx376bySJA7nl7Fd/NHHeIagFxkdjCGbVr67herfIzmAQiS6Xh8hf/4TDOsxCXZ3av0lQXBHgW3Y/3ANTYRgIXJgVgpHivnL9Kq/PaqCbvR5H2RMzYI=,iv:QYdXulC8UvptpXFzJ3gObL4TIDBKGv6xMtsMIwFVPRA=,tag:oYIDiMrwgDsUv1ay7d5pIA==,type:str]
    version: 3.13.0
