//! Authoritative TOC for the Wissenschaft der Logik (hegel2) — the work as
//! modern scholarship reads it: GW 21 (1832 Seyn), GW 11 pp. 233–409 (1813
//! Wesen), GW 12 pp. 5–253 (1816 Begriff).
//!
//! One entry per content node, in document order, transcribed from the
//! printed GW tables of contents (all levels; Inhaltsanzeigen and the
//! Nachlass Beilagen excluded), arranged under the work's two Theile. Labels
//! keep the GW orthography (`Seyn`, `zweyten`); all-caps structural heads are
//! case-normalized. `slug` derives from the label, with a counter suffix
//! where labels repeat (the many Anmerkungen).
//!
//! Depths form a strict tree — every node's parent sits exactly one level up.
//! The book itself is the implicit depth-0 root, created by the importer.

pub struct TocEntry {
    /// 1-based document position, also the `NNN` filename prefix.
    pub position: u16,
    pub depth: u16,
    /// The GW volume.page the node starts on ("21.68"). `None` for the two
    /// Theil containers, which open on unpaged title matter.
    pub page: Option<&'static str>,
    pub slug: &'static str,
    pub label: &'static str,
    /// `true` where the printed GW TOC brackets the heading as editorially
    /// supplied (only "A. [Seyn]", GW 21.68).
    pub supplied_heading: bool,
}

const TOC: &[TocEntry] = &[
    TocEntry {
        position: 1,
        depth: 1,
        page: None,
        slug: "erster_theil_die_objective_logik",
        label: "Erster Theil. Die objective Logik",
        supplied_heading: false,
    },
    TocEntry {
        position: 2,
        depth: 2,
        page: Some("21.5"),
        slug: "vorrede_zur_ersten_ausgabe",
        label: "Vorrede zur ersten Ausgabe",
        supplied_heading: false,
    },
    TocEntry {
        position: 3,
        depth: 2,
        page: Some("21.10"),
        slug: "vorrede_zur_zweyten_ausgabe",
        label: "Vorrede zur zweyten Ausgabe",
        supplied_heading: false,
    },
    TocEntry {
        position: 4,
        depth: 2,
        page: Some("21.27"),
        slug: "einleitung",
        label: "Einleitung",
        supplied_heading: false,
    },
    TocEntry {
        position: 5,
        depth: 3,
        page: Some("21.27"),
        slug: "allgemeiner_begriff_der_logik",
        label: "Allgemeiner Begriff der Logik",
        supplied_heading: false,
    },
    TocEntry {
        position: 6,
        depth: 3,
        page: Some("21.44"),
        slug: "allgemeine_eintheilung_der_logik",
        label: "Allgemeine Eintheilung der Logik",
        supplied_heading: false,
    },
    TocEntry {
        position: 7,
        depth: 2,
        page: Some("21.51"),
        slug: "erstes_buch_die_lehre_vom_seyn",
        label: "Erstes Buch. Die Lehre vom Seyn",
        supplied_heading: false,
    },
    TocEntry {
        position: 8,
        depth: 3,
        page: Some("21.53"),
        slug: "womit_muss_der_anfang_der_wissenschaft_gemacht_werden",
        label: "Womit muß der Anfang der Wissenschaft gemacht werden?",
        supplied_heading: false,
    },
    TocEntry {
        position: 9,
        depth: 3,
        page: Some("21.66"),
        slug: "allgemeine_eintheilung_des_seyns",
        label: "Allgemeine Eintheilung des Seyns",
        supplied_heading: false,
    },
    TocEntry {
        position: 10,
        depth: 3,
        page: Some("21.68"),
        slug: "erster_abschnitt_bestimmtheit_qualitaet",
        label: "Erster Abschnitt. Bestimmtheit (Qualität)",
        supplied_heading: false,
    },
    TocEntry {
        position: 11,
        depth: 4,
        page: Some("21.68"),
        slug: "erstes_kapitel_seyn",
        label: "Erstes Kapitel. Seyn",
        supplied_heading: false,
    },
    TocEntry {
        position: 12,
        depth: 5,
        page: Some("21.68"),
        slug: "a_seyn",
        label: "A. Seyn",
        supplied_heading: true,
    },
    TocEntry {
        position: 13,
        depth: 5,
        page: Some("21.69"),
        slug: "b_nichts",
        label: "B. Nichts",
        supplied_heading: false,
    },
    TocEntry {
        position: 14,
        depth: 5,
        page: Some("21.69"),
        slug: "c_werden",
        label: "C. Werden",
        supplied_heading: false,
    },
    TocEntry {
        position: 15,
        depth: 6,
        page: Some("21.69"),
        slug: "1_einheit_des_seyns_und_nichts",
        label: "1. Einheit des Seyns und Nichts",
        supplied_heading: false,
    },
    TocEntry {
        position: 16,
        depth: 7,
        page: Some("21.70"),
        slug: "anmerkung_1",
        label: "Anmerkung 1",
        supplied_heading: false,
    },
    TocEntry {
        position: 17,
        depth: 7,
        page: Some("21.77"),
        slug: "anmerkung_2",
        label: "Anmerkung 2",
        supplied_heading: false,
    },
    TocEntry {
        position: 18,
        depth: 7,
        page: Some("21.80"),
        slug: "anmerkung_3",
        label: "Anmerkung 3",
        supplied_heading: false,
    },
    TocEntry {
        position: 19,
        depth: 7,
        page: Some("21.90"),
        slug: "anmerkung_4",
        label: "Anmerkung 4",
        supplied_heading: false,
    },
    TocEntry {
        position: 20,
        depth: 6,
        page: Some("21.92"),
        slug: "2_momente_des_werdens",
        label: "2. Momente des Werdens",
        supplied_heading: false,
    },
    TocEntry {
        position: 21,
        depth: 6,
        page: Some("21.93"),
        slug: "3_aufheben_des_werdens",
        label: "3. Aufheben des Werdens",
        supplied_heading: false,
    },
    TocEntry {
        position: 22,
        depth: 7,
        page: Some("21.94"),
        slug: "anmerkung",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 23,
        depth: 4,
        page: Some("21.96"),
        slug: "zweytes_kapitel_das_daseyn",
        label: "Zweytes Kapitel. Das Daseyn",
        supplied_heading: false,
    },
    TocEntry {
        position: 24,
        depth: 5,
        page: Some("21.96"),
        slug: "a_daseyn_als_solches",
        label: "A. Daseyn als solches",
        supplied_heading: false,
    },
    TocEntry {
        position: 25,
        depth: 6,
        page: Some("21.97"),
        slug: "a_daseyn_ueberhaupt",
        label: "a. Daseyn überhaupt",
        supplied_heading: false,
    },
    TocEntry {
        position: 26,
        depth: 6,
        page: Some("21.98"),
        slug: "b_qualitaet",
        label: "b. Qualität",
        supplied_heading: false,
    },
    TocEntry {
        position: 27,
        depth: 7,
        page: Some("21.99"),
        slug: "anmerkung_5",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 28,
        depth: 6,
        page: Some("21.102"),
        slug: "c_etwas",
        label: "c. Etwas",
        supplied_heading: false,
    },
    TocEntry {
        position: 29,
        depth: 5,
        page: Some("21.104"),
        slug: "b_die_endlichkeit",
        label: "B. Die Endlichkeit",
        supplied_heading: false,
    },
    TocEntry {
        position: 30,
        depth: 6,
        page: Some("21.105"),
        slug: "a_etwas_und_ein_anderes",
        label: "a. Etwas und ein Anderes",
        supplied_heading: false,
    },
    TocEntry {
        position: 31,
        depth: 6,
        page: Some("21.110"),
        slug: "b_bestimmung_beschaffenheit_und_grenze",
        label: "b. Bestimmung, Beschaffenheit und Grenze",
        supplied_heading: false,
    },
    TocEntry {
        position: 32,
        depth: 6,
        page: Some("21.116"),
        slug: "c_die_endlichkeit",
        label: "c. Die Endlichkeit",
        supplied_heading: false,
    },
    TocEntry {
        position: 33,
        depth: 7,
        page: Some("21.117"),
        slug: "alpha_die_unmittelbarkeit_der_endlichkeit",
        label: "α. Die Unmittelbarkeit der Endlichkeit",
        supplied_heading: false,
    },
    TocEntry {
        position: 34,
        depth: 7,
        page: Some("21.118"),
        slug: "beta_die_schranke_und_das_sollen",
        label: "β. Die Schranke und das Sollen",
        supplied_heading: false,
    },
    TocEntry {
        position: 35,
        depth: 8,
        page: Some("21.120"),
        slug: "anmerkung_6",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 36,
        depth: 7,
        page: Some("21.123"),
        slug: "gamma_uebergang_des_endlichen_in_das_unendliche",
        label: "γ. Uebergang des Endlichen in das Unendliche",
        supplied_heading: false,
    },
    TocEntry {
        position: 37,
        depth: 5,
        page: Some("21.124"),
        slug: "c_die_unendlichkeit",
        label: "C. Die Unendlichkeit",
        supplied_heading: false,
    },
    TocEntry {
        position: 38,
        depth: 6,
        page: Some("21.125"),
        slug: "a_das_unendliche_ueberhaupt",
        label: "a. Das Unendliche überhaupt",
        supplied_heading: false,
    },
    TocEntry {
        position: 39,
        depth: 6,
        page: Some("21.126"),
        slug: "b_wechselbestimmung_des_endlichen_und_unendlichen",
        label: "b. Wechselbestimmung des Endlichen und Unendlichen",
        supplied_heading: false,
    },
    TocEntry {
        position: 40,
        depth: 6,
        page: Some("21.130"),
        slug: "c_die_affirmative_unendlichkeit",
        label: "c. Die affirmative Unendlichkeit",
        supplied_heading: false,
    },
    TocEntry {
        position: 41,
        depth: 5,
        page: Some("21.137"),
        slug: "der_uebergang",
        label: "Der Uebergang",
        supplied_heading: false,
    },
    TocEntry {
        position: 42,
        depth: 6,
        page: Some("21.137"),
        slug: "anmerkung_1_2",
        label: "Anmerkung 1",
        supplied_heading: false,
    },
    TocEntry {
        position: 43,
        depth: 6,
        page: Some("21.142"),
        slug: "anmerkung_2_2",
        label: "Anmerkung 2",
        supplied_heading: false,
    },
    TocEntry {
        position: 44,
        depth: 4,
        page: Some("21.144"),
        slug: "drittes_kapitel_das_fuersichseyn",
        label: "Drittes Kapitel. Das Fürsichseyn",
        supplied_heading: false,
    },
    TocEntry {
        position: 45,
        depth: 5,
        page: Some("21.145"),
        slug: "a_das_fuersichseyn_als_solches",
        label: "A. Das Fürsichseyn als solches",
        supplied_heading: false,
    },
    TocEntry {
        position: 46,
        depth: 6,
        page: Some("21.146"),
        slug: "a_daseyn_und_fuersichseyn",
        label: "a. Daseyn und Fürsichseyn",
        supplied_heading: false,
    },
    TocEntry {
        position: 47,
        depth: 6,
        page: Some("21.146"),
        slug: "b_seyn_fuer_eines",
        label: "b. Seyn-für-eines",
        supplied_heading: false,
    },
    TocEntry {
        position: 48,
        depth: 7,
        page: Some("21.147"),
        slug: "anmerkung_7",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 49,
        depth: 6,
        page: Some("21.150"),
        slug: "c_eins",
        label: "c. Eins",
        supplied_heading: false,
    },
    TocEntry {
        position: 50,
        depth: 5,
        page: Some("21.151"),
        slug: "b_eins_und_vieles",
        label: "B. Eins und Vieles",
        supplied_heading: false,
    },
    TocEntry {
        position: 51,
        depth: 6,
        page: Some("21.152"),
        slug: "a_das_eins_an_ihm_selbst",
        label: "a. Das Eins an ihm selbst",
        supplied_heading: false,
    },
    TocEntry {
        position: 52,
        depth: 6,
        page: Some("21.153"),
        slug: "b_das_eins_und_das_leere",
        label: "b. Das Eins und das Leere",
        supplied_heading: false,
    },
    TocEntry {
        position: 53,
        depth: 7,
        page: Some("21.153"),
        slug: "anmerkung_8",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 54,
        depth: 6,
        page: Some("21.155"),
        slug: "c_viele_eins_repulsion",
        label: "c. Viele Eins. Repulsion",
        supplied_heading: false,
    },
    TocEntry {
        position: 55,
        depth: 7,
        page: Some("21.157"),
        slug: "anmerkung_9",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 56,
        depth: 5,
        page: Some("21.158"),
        slug: "c_repulsion_und_attraction",
        label: "C. Repulsion und Attraction",
        supplied_heading: false,
    },
    TocEntry {
        position: 57,
        depth: 6,
        page: Some("21.158"),
        slug: "a_ausschliessen_des_eins",
        label: "a. Ausschließen des Eins",
        supplied_heading: false,
    },
    TocEntry {
        position: 58,
        depth: 7,
        page: Some("21.160"),
        slug: "anmerkung_10",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 59,
        depth: 6,
        page: Some("21.161"),
        slug: "b_das_eine_eins_der_attraction",
        label: "b. Das Eine Eins der Attraction",
        supplied_heading: false,
    },
    TocEntry {
        position: 60,
        depth: 6,
        page: Some("21.162"),
        slug: "c_die_beziehung_der_repulsion_und_attraction",
        label: "c. Die Beziehung der Repulsion und Attraction",
        supplied_heading: false,
    },
    TocEntry {
        position: 61,
        depth: 7,
        page: Some("21.166"),
        slug: "anmerkung_11",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 62,
        depth: 3,
        page: Some("21.173"),
        slug: "zweyter_abschnitt_die_groesse_quantitaet",
        label: "Zweyter Abschnitt. Die Größe (Quantität)",
        supplied_heading: false,
    },
    TocEntry {
        position: 63,
        depth: 4,
        page: Some("21.174"),
        slug: "anmerkung_12",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 64,
        depth: 4,
        page: Some("21.176"),
        slug: "erstes_kapitel_die_quantitaet",
        label: "Erstes Kapitel. Die Quantität",
        supplied_heading: false,
    },
    TocEntry {
        position: 65,
        depth: 5,
        page: Some("21.176"),
        slug: "a_die_reine_quantitaet",
        label: "A. Die reine Quantität",
        supplied_heading: false,
    },
    TocEntry {
        position: 66,
        depth: 6,
        page: Some("21.177"),
        slug: "anmerkung_1_3",
        label: "Anmerkung 1",
        supplied_heading: false,
    },
    TocEntry {
        position: 67,
        depth: 6,
        page: Some("21.179"),
        slug: "anmerkung_2_3",
        label: "Anmerkung 2",
        supplied_heading: false,
    },
    TocEntry {
        position: 68,
        depth: 5,
        page: Some("21.189"),
        slug: "b_continuirliche_und_discrete_groesse",
        label: "B. Continuirliche und discrete Größe",
        supplied_heading: false,
    },
    TocEntry {
        position: 69,
        depth: 6,
        page: Some("21.190"),
        slug: "anmerkung_13",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 70,
        depth: 5,
        page: Some("21.191"),
        slug: "c_begrenzung_der_quantitaet",
        label: "C. Begrenzung der Quantität",
        supplied_heading: false,
    },
    TocEntry {
        position: 71,
        depth: 4,
        page: Some("21.193"),
        slug: "zweytes_kapitel_quantum",
        label: "Zweytes Kapitel. Quantum",
        supplied_heading: false,
    },
    TocEntry {
        position: 72,
        depth: 5,
        page: Some("21.193"),
        slug: "a_die_zahl",
        label: "A. Die Zahl",
        supplied_heading: false,
    },
    TocEntry {
        position: 73,
        depth: 6,
        page: Some("21.196"),
        slug: "anmerkung_1_4",
        label: "Anmerkung 1",
        supplied_heading: false,
    },
    TocEntry {
        position: 74,
        depth: 6,
        page: Some("21.203"),
        slug: "anmerkung_2_4",
        label: "Anmerkung 2",
        supplied_heading: false,
    },
    TocEntry {
        position: 75,
        depth: 5,
        page: Some("21.208"),
        slug: "b_extensives_und_intensives_quantum",
        label: "B. Extensives und intensives Quantum",
        supplied_heading: false,
    },
    TocEntry {
        position: 76,
        depth: 6,
        page: Some("21.208"),
        slug: "a_unterschied_derselben",
        label: "a. Unterschied derselben",
        supplied_heading: false,
    },
    TocEntry {
        position: 77,
        depth: 6,
        page: Some("21.212"),
        slug: "b_identitaet_der_extensiven_und_intensiven_groesse",
        label: "b. Identität der extensiven und intensiven Größe",
        supplied_heading: false,
    },
    TocEntry {
        position: 78,
        depth: 7,
        page: Some("21.214"),
        slug: "anmerkung_1_5",
        label: "Anmerkung 1",
        supplied_heading: false,
    },
    TocEntry {
        position: 79,
        depth: 7,
        page: Some("21.216"),
        slug: "anmerkung_2_5",
        label: "Anmerkung 2",
        supplied_heading: false,
    },
    TocEntry {
        position: 80,
        depth: 6,
        page: Some("21.217"),
        slug: "c_die_veraenderung_des_quantums",
        label: "c. Die Veränderung des Quantums",
        supplied_heading: false,
    },
    TocEntry {
        position: 81,
        depth: 5,
        page: Some("21.218"),
        slug: "c_die_quantitative_unendlichkeit",
        label: "C. Die quantitative Unendlichkeit",
        supplied_heading: false,
    },
    TocEntry {
        position: 82,
        depth: 6,
        page: Some("21.218"),
        slug: "a_begriff_derselben",
        label: "a. Begriff derselben",
        supplied_heading: false,
    },
    TocEntry {
        position: 83,
        depth: 6,
        page: Some("21.220"),
        slug: "b_der_quantitative_unendliche_progress",
        label: "b. Der quantitative unendliche Progreß",
        supplied_heading: false,
    },
    TocEntry {
        position: 84,
        depth: 7,
        page: Some("21.222"),
        slug: "anmerkung_1_6",
        label: "Anmerkung 1",
        supplied_heading: false,
    },
    TocEntry {
        position: 85,
        depth: 7,
        page: Some("21.228"),
        slug: "anmerkung_2_6",
        label: "Anmerkung 2",
        supplied_heading: false,
    },
    TocEntry {
        position: 86,
        depth: 6,
        page: Some("21.233"),
        slug: "c_die_unendlichkeit_des_quantums",
        label: "c. Die Unendlichkeit des Quantums",
        supplied_heading: false,
    },
    TocEntry {
        position: 87,
        depth: 7,
        page: Some("21.236"),
        slug: "anmerkung_1_die_begriffsbestimmtheit_des_mathematischen_unendlichen",
        label: "Anmerkung 1. Die Begriffsbestimmtheit des mathematischen Unendlichen",
        supplied_heading: false,
    },
    TocEntry {
        position: 88,
        depth: 7,
        page: Some("21.273"),
        slug: "anmerkung_2_der_zweck_des_differentialcalculs_aus_seiner_anwendung_abgeleitet",
        label: "Anmerkung 2. Der Zweck des Differentialcalculs aus seiner Anwendung abgeleitet",
        supplied_heading: false,
    },
    TocEntry {
        position: 89,
        depth: 7,
        page: Some("21.299"),
        slug: "anmerkung_3_noch_andere_mit_der_qualitativen_groessenbestimmtheit_zusammenhaengende_formen",
        label: "Anmerkung 3. Noch andere mit der qualitativen Grössenbestimmtheit zusammenhängende Formen",
        supplied_heading: false,
    },
    TocEntry {
        position: 90,
        depth: 4,
        page: Some("21.310"),
        slug: "drittes_kapitel_das_quantitative_verhaeltniss",
        label: "Drittes Kapitel. Das quantitative Verhältniß",
        supplied_heading: false,
    },
    TocEntry {
        position: 91,
        depth: 5,
        page: Some("21.311"),
        slug: "a_das_directe_verhaeltniss",
        label: "A. Das directe Verhältniß",
        supplied_heading: false,
    },
    TocEntry {
        position: 92,
        depth: 5,
        page: Some("21.314"),
        slug: "b_das_umgekehrte_verhaeltniss",
        label: "B. Das umgekehrte Verhältniß",
        supplied_heading: false,
    },
    TocEntry {
        position: 93,
        depth: 5,
        page: Some("21.318"),
        slug: "c_potenzenverhaeltniss",
        label: "C. Potenzenverhältniß",
        supplied_heading: false,
    },
    TocEntry {
        position: 94,
        depth: 6,
        page: Some("21.321"),
        slug: "anmerkung_14",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 95,
        depth: 3,
        page: Some("21.323"),
        slug: "dritter_abschnitt_das_maass",
        label: "Dritter Abschnitt. Das Maass",
        supplied_heading: false,
    },
    TocEntry {
        position: 96,
        depth: 4,
        page: Some("21.329"),
        slug: "erstes_kapitel_die_specifische_quantitaet",
        label: "Erstes Kapitel. Die specifische Quantität",
        supplied_heading: false,
    },
    TocEntry {
        position: 97,
        depth: 5,
        page: Some("21.329"),
        slug: "a_das_specifische_quantum",
        label: "A. Das specifische Quantum",
        supplied_heading: false,
    },
    TocEntry {
        position: 98,
        depth: 5,
        page: Some("21.333"),
        slug: "b_specificirendes_maass",
        label: "B. Specificirendes Maaß",
        supplied_heading: false,
    },
    TocEntry {
        position: 99,
        depth: 6,
        page: Some("21.333"),
        slug: "a_die_regel",
        label: "a. Die Regel",
        supplied_heading: false,
    },
    TocEntry {
        position: 100,
        depth: 6,
        page: Some("21.333"),
        slug: "b_das_specificirende_maass",
        label: "b. Das specificirende Maaß",
        supplied_heading: false,
    },
    TocEntry {
        position: 101,
        depth: 7,
        page: Some("21.335"),
        slug: "anmerkung_15",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 102,
        depth: 6,
        page: Some("21.336"),
        slug: "c_verhaeltniss_beyder_seiten_als_qualitaeten",
        label: "c. Verhältniß beyder Seiten als Qualitäten",
        supplied_heading: false,
    },
    TocEntry {
        position: 103,
        depth: 7,
        page: Some("21.339"),
        slug: "anmerkung_16",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 104,
        depth: 5,
        page: Some("21.341"),
        slug: "c_das_fuersichseyn_im_maasse",
        label: "C. Das Fürsichseyn im Maaße",
        supplied_heading: false,
    },
    TocEntry {
        position: 105,
        depth: 4,
        page: Some("21.345"),
        slug: "zweytes_kapitel_das_reale_maass",
        label: "Zweytes Kapitel. Das reale Maaß",
        supplied_heading: false,
    },
    TocEntry {
        position: 106,
        depth: 5,
        page: Some("21.346"),
        slug: "a_das_verhaeltniss_selbststaendiger_maasse",
        label: "A. Das Verhältniß selbstständiger Maaße",
        supplied_heading: false,
    },
    TocEntry {
        position: 107,
        depth: 6,
        page: Some("21.347"),
        slug: "a_verbindung_zweyer_maasse",
        label: "a. Verbindung zweyer Maaße",
        supplied_heading: false,
    },
    TocEntry {
        position: 108,
        depth: 6,
        page: Some("21.348"),
        slug: "b_das_maass_als_reihe_von_maassverhaeltnissen",
        label: "b. Das Maaß als Reihe von Maaßverhältnißen",
        supplied_heading: false,
    },
    TocEntry {
        position: 109,
        depth: 6,
        page: Some("21.352"),
        slug: "c_wahlverwandtschaft",
        label: "c. Wahlverwandtschaft",
        supplied_heading: false,
    },
    TocEntry {
        position: 110,
        depth: 7,
        page: Some("21.354"),
        slug: "anmerkung_17",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 111,
        depth: 5,
        page: Some("21.364"),
        slug: "b_knotenlinie_von_maassverhaeltnissen",
        label: "B. Knotenlinie von Maaßverhältnißen",
        supplied_heading: false,
    },
    TocEntry {
        position: 112,
        depth: 6,
        page: Some("21.366"),
        slug: "anmerkung_18",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 113,
        depth: 5,
        page: Some("21.369"),
        slug: "c_das_maasslose",
        label: "C. Das Maaßlose",
        supplied_heading: false,
    },
    TocEntry {
        position: 114,
        depth: 4,
        page: Some("21.373"),
        slug: "drittes_kapitel_das_werden_des_wesens",
        label: "Drittes Kapitel. Das Werden des Wesens",
        supplied_heading: false,
    },
    TocEntry {
        position: 115,
        depth: 5,
        page: Some("21.373"),
        slug: "a_die_absolute_indifferenz",
        label: "A. Die absolute Indifferenz",
        supplied_heading: false,
    },
    TocEntry {
        position: 116,
        depth: 5,
        page: Some("21.374"),
        slug: "b_die_indifferenz_als_umgekehrtes_verhaeltniss_ihrer_factoren",
        label: "B. Die Indifferenz als umgekehrtes Verhältniß ihrer Factoren",
        supplied_heading: false,
    },
    TocEntry {
        position: 117,
        depth: 6,
        page: Some("21.377"),
        slug: "anmerkung_19",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 118,
        depth: 5,
        page: Some("21.381"),
        slug: "c_uebergang_in_das_wesen",
        label: "C. Uebergang in das Wesen",
        supplied_heading: false,
    },
    TocEntry {
        position: 119,
        depth: 2,
        // The 1813 half-title (GW 11.233) and Inhaltsanzeige are excluded
        // apparatus; the Buch's content opens at its body heading, 11.241.
        page: Some("11.241"),
        slug: "zweytes_buch_die_lehre_vom_wesen",
        label: "Zweytes Buch. Die Lehre vom Wesen",
        supplied_heading: false,
    },
    TocEntry {
        position: 120,
        depth: 3,
        page: Some("11.244"),
        slug: "erster_abschnitt_das_wesen_als_reflexion_in_ihm_selbst",
        label: "Erster Abschnitt. Das Wesen als Reflexion in ihm selbst",
        supplied_heading: false,
    },
    TocEntry {
        position: 121,
        depth: 4,
        page: Some("11.244"),
        slug: "erstes_kapitel_der_schein",
        label: "Erstes Kapitel. Der Schein",
        supplied_heading: false,
    },
    TocEntry {
        position: 122,
        depth: 5,
        page: Some("11.245"),
        slug: "a_das_wesentliche_und_das_unwesentliche",
        label: "A. Das Wesentliche und das Unwesentliche",
        supplied_heading: false,
    },
    TocEntry {
        position: 123,
        depth: 5,
        page: Some("11.246"),
        slug: "b_der_schein",
        label: "B. Der Schein",
        supplied_heading: false,
    },
    TocEntry {
        position: 124,
        depth: 5,
        page: Some("11.249"),
        slug: "c_die_reflexion",
        label: "C. Die Reflexion",
        supplied_heading: false,
    },
    TocEntry {
        position: 125,
        depth: 6,
        page: Some("11.250"),
        slug: "1_die_setzende_reflexion",
        label: "1. Die setzende Reflexion",
        supplied_heading: false,
    },
    TocEntry {
        position: 126,
        depth: 6,
        page: Some("11.252"),
        slug: "2_die_aeussere_reflexion",
        label: "2. Die äussere Reflexion",
        supplied_heading: false,
    },
    TocEntry {
        position: 127,
        depth: 7,
        page: Some("11.254"),
        slug: "anmerkung_20",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 128,
        depth: 6,
        page: Some("11.255"),
        slug: "3_bestimmende_reflexion",
        label: "3. Bestimmende Reflexion",
        supplied_heading: false,
    },
    TocEntry {
        position: 129,
        depth: 4,
        page: Some("11.258"),
        slug: "zweytes_kapitel_die_wesenheiten_oder_die_reflexions_bestimmungen",
        label: "Zweytes Kapitel. Die Wesenheiten oder die Reflexions-Bestimmungen",
        supplied_heading: false,
    },
    TocEntry {
        position: 130,
        depth: 5,
        page: Some("11.258"),
        slug: "anmerkung_21",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 131,
        depth: 5,
        page: Some("11.260"),
        slug: "a_die_identitaet",
        label: "A. Die Identität",
        supplied_heading: false,
    },
    TocEntry {
        position: 132,
        depth: 6,
        page: Some("11.261"),
        slug: "anmerkung_1_7",
        label: "Anmerkung 1",
        supplied_heading: false,
    },
    TocEntry {
        position: 133,
        depth: 6,
        page: Some("11.262"),
        slug: "anmerkung_2_7",
        label: "Anmerkung 2",
        supplied_heading: false,
    },
    TocEntry {
        position: 134,
        depth: 5,
        page: Some("11.265"),
        slug: "b_der_unterschied",
        label: "B. Der Unterschied",
        supplied_heading: false,
    },
    TocEntry {
        position: 135,
        depth: 6,
        page: Some("11.265"),
        slug: "1_der_absolute_unterschied",
        label: "1. Der absolute Unterschied",
        supplied_heading: false,
    },
    TocEntry {
        position: 136,
        depth: 6,
        page: Some("11.267"),
        slug: "2_die_verschiedenheit",
        label: "2. Die Verschiedenheit",
        supplied_heading: false,
    },
    TocEntry {
        position: 137,
        depth: 7,
        page: Some("11.270"),
        slug: "anmerkung_22",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 138,
        depth: 6,
        page: Some("11.272"),
        slug: "3_der_gegensatz",
        label: "3. Der Gegensatz",
        supplied_heading: false,
    },
    TocEntry {
        position: 139,
        depth: 7,
        page: Some("11.275"),
        slug: "anmerkung_23",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 140,
        depth: 5,
        page: Some("11.279"),
        slug: "c_der_widerspruch",
        label: "C. Der Widerspruch",
        supplied_heading: false,
    },
    TocEntry {
        position: 141,
        depth: 6,
        page: Some("11.283"),
        slug: "anmerkung_1_8",
        label: "Anmerkung 1",
        supplied_heading: false,
    },
    TocEntry {
        position: 142,
        depth: 6,
        page: Some("11.285"),
        slug: "anmerkung_2_8",
        label: "Anmerkung 2",
        supplied_heading: false,
    },
    TocEntry {
        position: 143,
        depth: 6,
        page: Some("11.286"),
        slug: "anmerkung_3_2",
        label: "Anmerkung 3",
        supplied_heading: false,
    },
    TocEntry {
        position: 144,
        depth: 4,
        page: Some("11.291"),
        slug: "drittes_kapitel_der_grund",
        label: "Drittes Kapitel. Der Grund",
        supplied_heading: false,
    },
    TocEntry {
        position: 145,
        depth: 5,
        page: Some("11.293"),
        slug: "anmerkung_24",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 146,
        depth: 5,
        page: Some("11.294"),
        slug: "a_der_absolute_grund",
        label: "A. Der absolute Grund",
        supplied_heading: false,
    },
    TocEntry {
        position: 147,
        depth: 6,
        page: Some("11.294"),
        slug: "a_form_und_wesen",
        label: "a. Form und Wesen",
        supplied_heading: false,
    },
    TocEntry {
        position: 148,
        depth: 6,
        page: Some("11.297"),
        slug: "b_form_und_materie",
        label: "b. Form und Materie",
        supplied_heading: false,
    },
    TocEntry {
        position: 149,
        depth: 6,
        page: Some("11.301"),
        slug: "c_form_und_inhalt",
        label: "c. Form und Inhalt",
        supplied_heading: false,
    },
    TocEntry {
        position: 150,
        depth: 5,
        page: Some("11.302"),
        slug: "b_der_bestimmte_grund",
        label: "B. Der bestimmte Grund",
        supplied_heading: false,
    },
    TocEntry {
        position: 151,
        depth: 6,
        page: Some("11.302"),
        slug: "a_der_formelle_grund",
        label: "a. Der formelle Grund",
        supplied_heading: false,
    },
    TocEntry {
        position: 152,
        depth: 7,
        page: Some("11.304"),
        slug: "anmerkung_25",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 153,
        depth: 6,
        page: Some("11.307"),
        slug: "b_der_reale_grund",
        label: "b. Der reale Grund",
        supplied_heading: false,
    },
    TocEntry {
        position: 154,
        depth: 7,
        page: Some("11.309"),
        slug: "anmerkung_26",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 155,
        depth: 6,
        page: Some("11.312"),
        slug: "c_der_vollstaendige_grund",
        label: "c. Der vollständige Grund",
        supplied_heading: false,
    },
    TocEntry {
        position: 156,
        depth: 5,
        page: Some("11.314"),
        slug: "c_die_bedingung",
        label: "C. Die Bedingung",
        supplied_heading: false,
    },
    TocEntry {
        position: 157,
        depth: 6,
        page: Some("11.314"),
        slug: "a_das_relativ_unbedingte",
        label: "a. Das relativ Unbedingte",
        supplied_heading: false,
    },
    TocEntry {
        position: 158,
        depth: 6,
        page: Some("11.316"),
        slug: "b_das_absolute_unbedingte",
        label: "b. Das absolute Unbedingte",
        supplied_heading: false,
    },
    TocEntry {
        position: 159,
        depth: 6,
        page: Some("11.319"),
        slug: "c_hervorgang_der_sache_in_die_existenz",
        label: "c. Hervorgang der Sache in die Existenz",
        supplied_heading: false,
    },
    TocEntry {
        position: 160,
        depth: 3,
        page: Some("11.323"),
        slug: "zweyter_abschnitt_die_erscheinung",
        label: "Zweyter Abschnitt. Die Erscheinung",
        supplied_heading: false,
    },
    TocEntry {
        position: 161,
        depth: 4,
        page: Some("11.324"),
        slug: "erstes_kapitel_die_existenz",
        label: "Erstes Kapitel. Die Existenz",
        supplied_heading: false,
    },
    TocEntry {
        position: 162,
        depth: 5,
        page: Some("11.327"),
        slug: "a_das_ding_und_seine_eigenschaften",
        label: "A. Das Ding und seine Eigenschaften",
        supplied_heading: false,
    },
    TocEntry {
        position: 163,
        depth: 6,
        page: Some("11.327"),
        slug: "a_ding_an_sich_und_existenz",
        label: "a. Ding an sich und Existenz",
        supplied_heading: false,
    },
    TocEntry {
        position: 164,
        depth: 6,
        page: Some("11.330"),
        slug: "b_die_eigenschaft",
        label: "b. Die Eigenschaft",
        supplied_heading: false,
    },
    TocEntry {
        position: 165,
        depth: 7,
        page: Some("11.331"),
        slug: "anmerkung_27",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 166,
        depth: 6,
        page: Some("11.332"),
        slug: "c_die_wechselwirkung_der_dinge",
        label: "c. Die Wechselwirkung der Dinge",
        supplied_heading: false,
    },
    TocEntry {
        position: 167,
        depth: 5,
        page: Some("11.334"),
        slug: "b_das_bestehen_des_dings_aus_materien",
        label: "B. Das Bestehen des Dings aus Materien",
        supplied_heading: false,
    },
    TocEntry {
        position: 168,
        depth: 5,
        page: Some("11.336"),
        slug: "c_die_aufloesung_des_dinges",
        label: "C. Die Auflösung des Dinges",
        supplied_heading: false,
    },
    TocEntry {
        position: 169,
        depth: 6,
        page: Some("11.337"),
        slug: "anmerkung_28",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 170,
        depth: 4,
        page: Some("11.341"),
        slug: "zweytes_kapitel_die_erscheinung",
        label: "Zweytes Kapitel. Die Erscheinung",
        supplied_heading: false,
    },
    TocEntry {
        position: 171,
        depth: 5,
        page: Some("11.342"),
        slug: "a_das_gesetz_der_erscheinung",
        label: "A. Das Gesetz der Erscheinung",
        supplied_heading: false,
    },
    TocEntry {
        position: 172,
        depth: 5,
        page: Some("11.347"),
        slug: "b_die_erscheinende_und_die_an_sich_seyende_welt",
        label: "B. Die erscheinende und die an-sich-seyende Welt",
        supplied_heading: false,
    },
    TocEntry {
        position: 173,
        depth: 5,
        page: Some("11.351"),
        slug: "c_aufloesung_der_erscheinung",
        label: "C. Auflösung der Erscheinung",
        supplied_heading: false,
    },
    TocEntry {
        position: 174,
        depth: 4,
        page: Some("11.353"),
        slug: "drittes_kapitel_das_wesentliche_verhaeltniss",
        label: "Drittes Kapitel. Das wesentliche Verhältniß",
        supplied_heading: false,
    },
    TocEntry {
        position: 175,
        depth: 5,
        page: Some("11.354"),
        slug: "a_das_verhaeltniss_des_ganzen_und_der_theile",
        label: "A. Das Verhältniß des Ganzen und der Theile",
        supplied_heading: false,
    },
    TocEntry {
        position: 176,
        depth: 6,
        page: Some("11.358"),
        slug: "anmerkung_29",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 177,
        depth: 5,
        page: Some("11.359"),
        slug: "b_das_verhaeltniss_der_kraft_und_ihrer_aeusserung",
        label: "B. Das Verhältniß der Kraft und ihrer Aeusserung",
        supplied_heading: false,
    },
    TocEntry {
        position: 178,
        depth: 6,
        page: Some("11.360"),
        slug: "a_das_bedingtseyn_der_kraft",
        label: "a. Das Bedingtseyn der Kraft",
        supplied_heading: false,
    },
    TocEntry {
        position: 179,
        depth: 6,
        page: Some("11.362"),
        slug: "b_die_sollicitation_der_kraft",
        label: "b. Die Sollicitation der Kraft",
        supplied_heading: false,
    },
    TocEntry {
        position: 180,
        depth: 6,
        page: Some("11.364"),
        slug: "c_die_unendlichkeit_der_kraft",
        label: "c. Die Unendlichkeit der Kraft",
        supplied_heading: false,
    },
    TocEntry {
        position: 181,
        depth: 5,
        page: Some("11.364"),
        slug: "c_verhaeltniss_des_aeussern_und_innern",
        label: "C. Verhältniß des Aeussern und Innern",
        supplied_heading: false,
    },
    TocEntry {
        position: 182,
        depth: 6,
        page: Some("11.366"),
        slug: "anmerkung_30",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 183,
        depth: 3,
        page: Some("11.369"),
        slug: "dritter_abschnitt_die_wirklichkeit",
        label: "Dritter Abschnitt. Die Wirklichkeit",
        supplied_heading: false,
    },
    TocEntry {
        position: 184,
        depth: 4,
        page: Some("11.370"),
        slug: "erstes_kapitel_das_absolute",
        label: "Erstes Kapitel. Das Absolute",
        supplied_heading: false,
    },
    TocEntry {
        position: 185,
        depth: 5,
        page: Some("11.370"),
        slug: "a_die_auslegung_des_absoluten",
        label: "A. Die Auslegung des Absoluten",
        supplied_heading: false,
    },
    TocEntry {
        position: 186,
        depth: 5,
        page: Some("11.373"),
        slug: "b_das_absolute_attribut",
        label: "B. Das absolute Attribut",
        supplied_heading: false,
    },
    TocEntry {
        position: 187,
        depth: 5,
        page: Some("11.374"),
        slug: "c_der_modus_des_absoluten",
        label: "C. Der Modus des Absoluten",
        supplied_heading: false,
    },
    TocEntry {
        position: 188,
        depth: 6,
        page: Some("11.376"),
        slug: "anmerkung_31",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 189,
        depth: 4,
        page: Some("11.380"),
        slug: "zweytes_kapitel_die_wirklichkeit",
        label: "Zweytes Kapitel. Die Wirklichkeit",
        supplied_heading: false,
    },
    TocEntry {
        position: 190,
        depth: 5,
        page: Some("11.381"),
        slug: "a_zufaelligkeit_oder_formelle_wirklichkeit_moeglichkeit_und_nothwendigkeit",
        label: "A. Zufälligkeit oder formelle Wirklichkeit, Möglichkeit und Nothwendigkeit",
        supplied_heading: false,
    },
    TocEntry {
        position: 191,
        depth: 5,
        page: Some("11.385"),
        slug: "b_relative_nothwendigkeit_oder_reale_wirklichkeit_moeglichkeit_und_nothwendigkeit",
        label: "B. Relative Nothwendigkeit oder reale Wirklichkeit, Möglichkeit und Nothwendigkeit",
        supplied_heading: false,
    },
    TocEntry {
        position: 192,
        depth: 5,
        page: Some("11.389"),
        slug: "c_absolute_nothwendigkeit",
        label: "C. Absolute Nothwendigkeit",
        supplied_heading: false,
    },
    TocEntry {
        position: 193,
        depth: 4,
        page: Some("11.393"),
        slug: "drittes_kapitel_das_absolute_verhaeltniss",
        label: "Drittes Kapitel. Das absolute Verhältniß",
        supplied_heading: false,
    },
    TocEntry {
        position: 194,
        depth: 5,
        page: Some("11.394"),
        slug: "a_das_verhaeltniss_der_substantialitaet",
        label: "A. Das Verhältniß der Substantialität",
        supplied_heading: false,
    },
    TocEntry {
        position: 195,
        depth: 5,
        page: Some("11.396"),
        slug: "b_das_causalitaetsverhaeltniss",
        label: "B. Das Causalitätsverhältniß",
        supplied_heading: false,
    },
    TocEntry {
        position: 196,
        depth: 6,
        page: Some("11.397"),
        slug: "a_die_formelle_causalitaet",
        label: "a. Die formelle Causalität",
        supplied_heading: false,
    },
    TocEntry {
        position: 197,
        depth: 6,
        page: Some("11.398"),
        slug: "b_das_bestimmte_causalitaetsverhaeltniss",
        label: "b. Das bestimmte Causalitätsverhältniß",
        supplied_heading: false,
    },
    TocEntry {
        position: 198,
        depth: 6,
        page: Some("11.404"),
        slug: "c_wirkung_und_gegenwirkung",
        label: "c. Wirkung und Gegenwirkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 199,
        depth: 5,
        page: Some("11.407"),
        slug: "c_die_wechselwirkung",
        label: "C. Die Wechselwirkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 200,
        depth: 1,
        page: None,
        slug: "zweyter_theil_die_subjective_logik_oder_die_lehre_vom_begriff",
        label: "Zweyter Theil. Die subjective Logik oder die Lehre vom Begriff",
        supplied_heading: false,
    },
    TocEntry {
        position: 201,
        depth: 2,
        page: Some("12.5"),
        slug: "vorbericht",
        label: "Vorbericht",
        supplied_heading: false,
    },
    TocEntry {
        position: 202,
        depth: 2,
        page: Some("12.11"),
        slug: "vom_begriff_im_allgemeinen",
        label: "Vom Begriff im allgemeinen",
        supplied_heading: false,
    },
    TocEntry {
        position: 203,
        depth: 2,
        page: Some("12.29"),
        slug: "eintheilung",
        label: "Eintheilung",
        supplied_heading: false,
    },
    TocEntry {
        position: 204,
        depth: 2,
        page: Some("12.31"),
        slug: "erster_abschnitt_die_subjectivitaet",
        label: "Erster Abschnitt. Die Subjectivität",
        supplied_heading: false,
    },
    TocEntry {
        position: 205,
        depth: 3,
        page: Some("12.32"),
        slug: "erstes_kapitel_der_begriff",
        label: "Erstes Kapitel. Der Begriff",
        supplied_heading: false,
    },
    TocEntry {
        position: 206,
        depth: 4,
        page: Some("12.33"),
        slug: "a_der_allgemeine_begriff",
        label: "A) Der allgemeine Begriff",
        supplied_heading: false,
    },
    TocEntry {
        position: 207,
        depth: 4,
        page: Some("12.37"),
        slug: "b_der_besondere_begriff",
        label: "B) Der besondere Begriff",
        supplied_heading: false,
    },
    TocEntry {
        position: 208,
        depth: 5,
        page: Some("12.43"),
        slug: "anmerkung_32",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 209,
        depth: 4,
        page: Some("12.49"),
        slug: "c_das_einzelne",
        label: "C) Das Einzelne",
        supplied_heading: false,
    },
    TocEntry {
        position: 210,
        depth: 3,
        page: Some("12.53"),
        slug: "zweytes_kapitel_das_urtheil",
        label: "Zweytes Kapitel. Das Urtheil",
        supplied_heading: false,
    },
    TocEntry {
        position: 211,
        depth: 4,
        page: Some("12.59"),
        slug: "a_das_urtheil_des_daseyns",
        label: "A. Das Urtheil des Daseyns",
        supplied_heading: false,
    },
    TocEntry {
        position: 212,
        depth: 5,
        page: Some("12.60"),
        slug: "a_das_positive_urtheil",
        label: "a. Das positive Urtheil",
        supplied_heading: false,
    },
    TocEntry {
        position: 213,
        depth: 5,
        page: Some("12.64"),
        slug: "b_negatives_urtheil",
        label: "b. Negatives Urtheil",
        supplied_heading: false,
    },
    TocEntry {
        position: 214,
        depth: 5,
        page: Some("12.69"),
        slug: "c_unendliches_urtheil",
        label: "c. Unendliches Urtheil",
        supplied_heading: false,
    },
    TocEntry {
        position: 215,
        depth: 4,
        page: Some("12.71"),
        slug: "b_das_urtheil_der_reflexion",
        label: "B. Das Urtheil der Reflexion",
        supplied_heading: false,
    },
    TocEntry {
        position: 216,
        depth: 5,
        page: Some("12.72"),
        slug: "a_das_singulaere_urtheil",
        label: "a. Das singuläre Urtheil",
        supplied_heading: false,
    },
    TocEntry {
        position: 217,
        depth: 5,
        page: Some("12.73"),
        slug: "b_das_particulaere_urtheil",
        label: "b. Das particuläre Urtheil",
        supplied_heading: false,
    },
    TocEntry {
        position: 218,
        depth: 5,
        page: Some("12.74"),
        slug: "c_das_universelle_urtheil",
        label: "c. Das universelle Urtheil",
        supplied_heading: false,
    },
    TocEntry {
        position: 219,
        depth: 4,
        page: Some("12.77"),
        slug: "c_das_urtheil_der_nothwendigkeit",
        label: "C. Das Urtheil der Nothwendigkeit",
        supplied_heading: false,
    },
    TocEntry {
        position: 220,
        depth: 5,
        page: Some("12.77"),
        slug: "a_das_kategorische_urtheil",
        label: "a. Das kategorische Urtheil",
        supplied_heading: false,
    },
    TocEntry {
        position: 221,
        depth: 5,
        page: Some("12.79"),
        slug: "b_das_hypothetische_urtheil",
        label: "b. Das hypothetische Urtheil",
        supplied_heading: false,
    },
    TocEntry {
        position: 222,
        depth: 5,
        page: Some("12.80"),
        slug: "c_das_disjunctive_urtheil",
        label: "c. Das disjunctive Urtheil",
        supplied_heading: false,
    },
    TocEntry {
        position: 223,
        depth: 4,
        page: Some("12.84"),
        slug: "d_das_urtheil_des_begriffs",
        label: "D. Das Urtheil des Begriffs",
        supplied_heading: false,
    },
    TocEntry {
        position: 224,
        depth: 5,
        page: Some("12.85"),
        slug: "a_das_assertorische_urtheil",
        label: "a. Das assertorische Urtheil",
        supplied_heading: false,
    },
    TocEntry {
        position: 225,
        depth: 5,
        page: Some("12.86"),
        slug: "b_das_problematische_urtheil",
        label: "b. Das problematische Urtheil",
        supplied_heading: false,
    },
    TocEntry {
        position: 226,
        depth: 5,
        page: Some("12.87"),
        slug: "c_das_apodiktische_urtheil",
        label: "c. Das apodiktische Urtheil",
        supplied_heading: false,
    },
    TocEntry {
        position: 227,
        depth: 3,
        page: Some("12.90"),
        slug: "drittes_kapitel_der_schluss",
        label: "Drittes Kapitel. Der Schluß",
        supplied_heading: false,
    },
    TocEntry {
        position: 228,
        depth: 4,
        page: Some("12.92"),
        slug: "a_der_schluss_des_daseyns",
        label: "A. Der Schluß des Daseyns",
        supplied_heading: false,
    },
    TocEntry {
        position: 229,
        depth: 5,
        page: Some("12.93"),
        slug: "a_erste_figur_des_schlusses",
        label: "a. Erste Figur des Schlusses",
        supplied_heading: false,
    },
    TocEntry {
        position: 230,
        depth: 5,
        page: Some("12.99"),
        slug: "b_die_zweyte_figur_b_e_a",
        label: "b. Die zweyte Figur: B-E-A",
        supplied_heading: false,
    },
    TocEntry {
        position: 231,
        depth: 5,
        page: Some("12.102"),
        slug: "c_die_dritte_figur_e_a_b",
        label: "c. Die dritte Figur: E-A-B",
        supplied_heading: false,
    },
    TocEntry {
        position: 232,
        depth: 5,
        page: Some("12.104"),
        slug: "d_die_vierte_figur_a_a_a_oder_der_mathematische_schluss",
        label: "d. Die vierte Figur: A-A-A oder der mathematische Schluß",
        supplied_heading: false,
    },
    TocEntry {
        position: 233,
        depth: 6,
        page: Some("12.106"),
        slug: "anmerkung_33",
        label: "Anmerkung",
        supplied_heading: false,
    },
    TocEntry {
        position: 234,
        depth: 4,
        page: Some("12.110"),
        slug: "b_der_schluss_der_reflexion",
        label: "B. Der Schluß der Reflexion",
        supplied_heading: false,
    },
    TocEntry {
        position: 235,
        depth: 5,
        page: Some("12.111"),
        slug: "a_schluss_der_allheit",
        label: "a. Schluß der Allheit",
        supplied_heading: false,
    },
    TocEntry {
        position: 236,
        depth: 5,
        page: Some("12.113"),
        slug: "b_schluss_der_induction",
        label: "b. Schluß der Induction",
        supplied_heading: false,
    },
    TocEntry {
        position: 237,
        depth: 5,
        page: Some("12.115"),
        slug: "c_der_schluss_der_analogie",
        label: "c. Der Schluß der Analogie",
        supplied_heading: false,
    },
    TocEntry {
        position: 238,
        depth: 4,
        page: Some("12.118"),
        slug: "c_der_schluss_der_nothwendigkeit",
        label: "C. Der Schluß der Nothwendigkeit",
        supplied_heading: false,
    },
    TocEntry {
        position: 239,
        depth: 5,
        page: Some("12.119"),
        slug: "a_der_kategorische_schluss",
        label: "a. Der kategorische Schluß",
        supplied_heading: false,
    },
    TocEntry {
        position: 240,
        depth: 5,
        page: Some("12.121"),
        slug: "b_der_hypothetische_schluss",
        label: "b. Der hypothetische Schluß",
        supplied_heading: false,
    },
    TocEntry {
        position: 241,
        depth: 5,
        page: Some("12.123"),
        slug: "c_der_disjunctive_schluss",
        label: "c. Der disjunctive Schluß",
        supplied_heading: false,
    },
    TocEntry {
        position: 242,
        depth: 2,
        page: Some("12.127"),
        slug: "zweyter_abschnitt_die_objectivitaet",
        label: "Zweyter Abschnitt. Die Objectivität",
        supplied_heading: false,
    },
    TocEntry {
        position: 243,
        depth: 3,
        page: Some("12.133"),
        slug: "erstes_kapitel_der_mechanismus",
        label: "Erstes Kapitel. Der Mechanismus",
        supplied_heading: false,
    },
    TocEntry {
        position: 244,
        depth: 4,
        page: Some("12.133"),
        slug: "a_das_mechanische_object",
        label: "A. Das mechanische Object",
        supplied_heading: false,
    },
    TocEntry {
        position: 245,
        depth: 4,
        page: Some("12.136"),
        slug: "b_der_mechanische_process",
        label: "B. Der mechanische Proceß",
        supplied_heading: false,
    },
    TocEntry {
        position: 246,
        depth: 5,
        page: Some("12.137"),
        slug: "a_der_formale_mechanische_process",
        label: "a. Der formale mechanische Proceß",
        supplied_heading: false,
    },
    TocEntry {
        position: 247,
        depth: 5,
        page: Some("12.140"),
        slug: "b_der_reale_mechanische_process",
        label: "b. Der reale mechanische Proceß",
        supplied_heading: false,
    },
    TocEntry {
        position: 248,
        depth: 5,
        page: Some("12.142"),
        slug: "c_das_product_des_mechanischen_processes",
        label: "c. Das Product des mechanischen Processes",
        supplied_heading: false,
    },
    TocEntry {
        position: 249,
        depth: 4,
        page: Some("12.143"),
        slug: "c_der_absolute_mechanismus",
        label: "C. Der absolute Mechanismus",
        supplied_heading: false,
    },
    TocEntry {
        position: 250,
        depth: 5,
        page: Some("12.143"),
        slug: "a_das_centrum",
        label: "a. Das Centrum",
        supplied_heading: false,
    },
    TocEntry {
        position: 251,
        depth: 5,
        page: Some("12.145"),
        slug: "b_das_gesetz",
        label: "b. Das Gesetz",
        supplied_heading: false,
    },
    TocEntry {
        position: 252,
        depth: 5,
        page: Some("12.146"),
        slug: "c_uebergang_des_mechanismus",
        label: "c. Uebergang des Mechanismus",
        supplied_heading: false,
    },
    TocEntry {
        position: 253,
        depth: 3,
        page: Some("12.148"),
        slug: "zweytes_kapitel_der_chemismus",
        label: "Zweytes Kapitel. Der Chemismus",
        supplied_heading: false,
    },
    TocEntry {
        position: 254,
        depth: 4,
        page: Some("12.148"),
        slug: "a_das_chemische_object",
        label: "A. Das chemische Object",
        supplied_heading: false,
    },
    TocEntry {
        position: 255,
        depth: 4,
        page: Some("12.149"),
        slug: "b_der_process",
        label: "B. Der Proceß",
        supplied_heading: false,
    },
    TocEntry {
        position: 256,
        depth: 4,
        page: Some("12.152"),
        slug: "c_uebergang_des_chemismus",
        label: "C. Uebergang des Chemismus",
        supplied_heading: false,
    },
    TocEntry {
        position: 257,
        depth: 3,
        page: Some("12.154"),
        slug: "drittes_kapitel_teleologie",
        label: "Drittes Kapitel. Teleologie",
        supplied_heading: false,
    },
    TocEntry {
        position: 258,
        depth: 4,
        page: Some("12.160"),
        slug: "a_der_subjective_zweck",
        label: "A. Der subjective Zweck",
        supplied_heading: false,
    },
    TocEntry {
        position: 259,
        depth: 4,
        page: Some("12.162"),
        slug: "b_das_mittel",
        label: "B. Das Mittel",
        supplied_heading: false,
    },
    TocEntry {
        position: 260,
        depth: 4,
        page: Some("12.165"),
        slug: "c_der_ausgefuehrte_zweck",
        label: "C. Der ausgeführte Zweck",
        supplied_heading: false,
    },
    TocEntry {
        position: 261,
        depth: 2,
        page: Some("12.173"),
        slug: "dritter_abschnitt_die_idee",
        label: "Dritter Abschnitt. Die Idee",
        supplied_heading: false,
    },
    TocEntry {
        position: 262,
        depth: 3,
        page: Some("12.179"),
        slug: "erstes_kapitel_das_leben",
        label: "Erstes Kapitel. Das Leben",
        supplied_heading: false,
    },
    TocEntry {
        position: 263,
        depth: 4,
        page: Some("12.182"),
        slug: "a_das_lebendige_individuum",
        label: "A. Das lebendige Individuum",
        supplied_heading: false,
    },
    TocEntry {
        position: 264,
        depth: 4,
        page: Some("12.187"),
        slug: "b_der_lebens_process",
        label: "B. Der Lebens-Proceß",
        supplied_heading: false,
    },
    TocEntry {
        position: 265,
        depth: 4,
        page: Some("12.189"),
        slug: "c_die_gattung",
        label: "C. Die Gattung",
        supplied_heading: false,
    },
    TocEntry {
        position: 266,
        depth: 3,
        page: Some("12.192"),
        slug: "zweytes_kapitel_die_idee_des_erkennens",
        label: "Zweytes Kapitel. Die Idee des Erkennens",
        supplied_heading: false,
    },
    TocEntry {
        position: 267,
        depth: 4,
        page: Some("12.199"),
        slug: "a_die_idee_des_wahren",
        label: "A. Die Idee des Wahren",
        supplied_heading: false,
    },
    TocEntry {
        position: 268,
        depth: 5,
        page: Some("12.202"),
        slug: "a_das_analytische_erkennen",
        label: "a. Das analytische Erkennen",
        supplied_heading: false,
    },
    TocEntry {
        position: 269,
        depth: 5,
        page: Some("12.209"),
        slug: "b_das_synthetische_erkennen",
        label: "b. Das synthetische Erkennen",
        supplied_heading: false,
    },
    TocEntry {
        position: 270,
        depth: 6,
        page: Some("12.210"),
        slug: "1_die_definition",
        label: "1. Die Definition",
        supplied_heading: false,
    },
    TocEntry {
        position: 271,
        depth: 6,
        page: Some("12.215"),
        slug: "2_die_eintheilung",
        label: "2. Die Eintheilung",
        supplied_heading: false,
    },
    TocEntry {
        position: 272,
        depth: 6,
        page: Some("12.220"),
        slug: "3_der_lehrsatz",
        label: "3. Der Lehrsatz",
        supplied_heading: false,
    },
    TocEntry {
        position: 273,
        depth: 4,
        page: Some("12.231"),
        slug: "b_die_idee_des_guten",
        label: "B. Die Idee des Guten",
        supplied_heading: false,
    },
    TocEntry {
        position: 274,
        depth: 3,
        page: Some("12.236"),
        slug: "drittes_kapitel_die_absolute_idee",
        label: "Drittes Kapitel. Die absolute Idee",
        supplied_heading: false,
    },
];

pub fn entries() -> &'static [TocEntry] {
    TOC
}

pub fn toc_len() -> usize {
    TOC.len()
}

pub fn flat_toc_entries() -> Vec<crate::FlatTocEntry> {
    TOC.iter()
        .enumerate()
        .map(|(i, e)| {
            (
                i,
                e.page.map(str::to_string),
                e.depth,
                e.label,
                Some(e.slug),
            )
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn positions_are_contiguous() {
        for (i, e) in TOC.iter().enumerate() {
            assert_eq!(e.position as usize, i + 1);
        }
    }

    #[test]
    fn slugs_are_unique() {
        let set: HashSet<&str> = TOC.iter().map(|e| e.slug).collect();
        assert_eq!(set.len(), TOC.len());
    }

    #[test]
    fn depths_form_a_strict_tree() {
        let mut stack: Vec<u16> = Vec::new();
        for e in TOC {
            while stack.last().is_some_and(|&d| d >= e.depth) {
                stack.pop();
            }
            let expected = stack.last().map_or(1, |&d| d + 1);
            assert_eq!(e.depth, expected, "depth jump at {}", e.slug);
            stack.push(e.depth);
        }
    }

    #[test]
    fn pages_ascend_within_each_volume_run() {
        // Document order visits GW 21, then GW 11 (Wesen), then GW 12 —
        // pages ascend within each volume's contiguous run.
        let mut prev: Option<(u16, u16)> = None;
        for e in TOC {
            let Some(p) = e.page else { continue };
            let (vol, page) = p.split_once('.').expect("vol.page");
            let key: (u16, u16) = (vol.parse().unwrap(), page.parse().unwrap());
            if let Some((pv, pp)) = prev
                && pv == key.0
            {
                assert!(key.1 >= pp, "page regression at {}: {p}", e.slug);
            }
            prev = Some(key);
        }
    }

    #[test]
    fn only_the_supplied_seyn_heading_is_flagged() {
        let flagged: Vec<&str> = TOC
            .iter()
            .filter(|e| e.supplied_heading)
            .map(|e| e.slug)
            .collect();
        assert_eq!(flagged, ["a_seyn"]);
    }

    #[test]
    fn the_two_theil_containers_are_the_only_unpaged_nodes() {
        let unpaged: Vec<&str> = TOC
            .iter()
            .filter(|e| e.page.is_none())
            .map(|e| e.slug)
            .collect();
        assert_eq!(
            unpaged,
            [
                "erster_theil_die_objective_logik",
                "zweyter_theil_die_subjective_logik_oder_die_lehre_vom_begriff",
            ]
        );
    }
}
