//! Modernized-orthography TOC labels for the Wissenschaft der Logik, one per
//! `toc` entry, in document order — the hegel1 `toc_mod` pattern.
//!
//! Structural fields (position, depth, page, slug, supplied_heading) are
//! `toc`'s; only the label text re-spells (`Seyn→Sein`, `Theil→Teil`,
//! `Verhältniß→Verhältnis`, `c→k` in Latinate words, post-1996 ß/ss), so a
//! file's front-matter label in `md_modernized/` matches its entry here byte
//! for byte. Orthography only — word forms and word order stay Hegel's.

/// Modernized labels, one per `toc` entry, in document order.
pub const MODERNIZED_LABELS: &[&str] = &[
    "Erster Teil. Die objektive Logik",
    "Vorrede zur ersten Ausgabe",
    "Vorrede zur zweiten Ausgabe",
    "Einleitung",
    "Allgemeiner Begriff der Logik",
    "Allgemeine Einteilung der Logik",
    "Erstes Buch. Die Lehre vom Sein",
    "Womit muss der Anfang der Wissenschaft gemacht werden?",
    "Allgemeine Einteilung des Seins",
    "Erster Abschnitt. Bestimmtheit (Qualität)",
    "Erstes Kapitel. Sein",
    "A. Sein",
    "B. Nichts",
    "C. Werden",
    "1. Einheit des Seins und Nichts",
    "Anmerkung 1",
    "Anmerkung 2",
    "Anmerkung 3",
    "Anmerkung 4",
    "2. Momente des Werdens",
    "3. Aufheben des Werdens",
    "Anmerkung",
    "Zweites Kapitel. Das Dasein",
    "A. Dasein als solches",
    "a. Dasein überhaupt",
    "b. Qualität",
    "Anmerkung",
    "c. Etwas",
    "B. Die Endlichkeit",
    "a. Etwas und ein Anderes",
    "b. Bestimmung, Beschaffenheit und Grenze",
    "c. Die Endlichkeit",
    "α. Die Unmittelbarkeit der Endlichkeit",
    "β. Die Schranke und das Sollen",
    "Anmerkung",
    "γ. Übergang des Endlichen in das Unendliche",
    "C. Die Unendlichkeit",
    "a. Das Unendliche überhaupt",
    "b. Wechselbestimmung des Endlichen und Unendlichen",
    "c. Die affirmative Unendlichkeit",
    "Der Übergang",
    "Anmerkung 1",
    "Anmerkung 2",
    "Drittes Kapitel. Das Fürsichsein",
    "A. Das Fürsichsein als solches",
    "a. Dasein und Fürsichsein",
    "b. Sein-für-eines",
    "Anmerkung",
    "c. Eins",
    "B. Eins und Vieles",
    "a. Das Eins an ihm selbst",
    "b. Das Eins und das Leere",
    "Anmerkung",
    "c. Viele Eins. Repulsion",
    "Anmerkung",
    "C. Repulsion und Attraktion",
    "a. Ausschließen des Eins",
    "Anmerkung",
    "b. Das Eine Eins der Attraktion",
    "c. Die Beziehung der Repulsion und Attraktion",
    "Anmerkung",
    "Zweiter Abschnitt. Die Größe (Quantität)",
    "Anmerkung",
    "Erstes Kapitel. Die Quantität",
    "A. Die reine Quantität",
    "Anmerkung 1",
    "Anmerkung 2",
    "B. Kontinuierliche und diskrete Größe",
    "Anmerkung",
    "C. Begrenzung der Quantität",
    "Zweites Kapitel. Quantum",
    "A. Die Zahl",
    "Anmerkung 1",
    "Anmerkung 2",
    "B. Extensives und intensives Quantum",
    "a. Unterschied derselben",
    "b. Identität der extensiven und intensiven Größe",
    "Anmerkung 1",
    "Anmerkung 2",
    "c. Die Veränderung des Quantums",
    "C. Die quantitative Unendlichkeit",
    "a. Begriff derselben",
    "b. Der quantitative unendliche Progress",
    "Anmerkung 1",
    "Anmerkung 2",
    "c. Die Unendlichkeit des Quantums",
    "Anmerkung 1. Die Begriffsbestimmtheit des mathematischen Unendlichen",
    "Anmerkung 2. Der Zweck des Differentialkalküls aus seiner Anwendung abgeleitet",
    "Anmerkung 3. Noch andere mit der qualitativen Größenbestimmtheit zusammenhängende Formen",
    "Drittes Kapitel. Das quantitative Verhältnis",
    "A. Das direkte Verhältnis",
    "B. Das umgekehrte Verhältnis",
    "C. Potenzenverhältnis",
    "Anmerkung",
    "Dritter Abschnitt. Das Maß",
    "Erstes Kapitel. Die spezifische Quantität",
    "A. Das spezifische Quantum",
    "B. Spezifizierendes Maß",
    "a. Die Regel",
    "b. Das spezifizierende Maß",
    "Anmerkung",
    "c. Verhältnis beider Seiten als Qualitäten",
    "Anmerkung",
    "C. Das Fürsichsein im Maße",
    "Zweites Kapitel. Das reale Maß",
    "A. Das Verhältnis selbstständiger Maße",
    "a. Verbindung zweier Maße",
    "b. Das Maß als Reihe von Maßverhältnissen",
    "c. Wahlverwandtschaft",
    "Anmerkung",
    "B. Knotenlinie von Maßverhältnissen",
    "Anmerkung",
    "C. Das Maßlose",
    "Drittes Kapitel. Das Werden des Wesens",
    "A. Die absolute Indifferenz",
    "B. Die Indifferenz als umgekehrtes Verhältnis ihrer Faktoren",
    "Anmerkung",
    "C. Übergang in das Wesen",
    "Zweites Buch. Die Lehre vom Wesen",
    "Erster Abschnitt. Das Wesen als Reflexion in ihm selbst",
    "Erstes Kapitel. Der Schein",
    "A. Das Wesentliche und das Unwesentliche",
    "B. Der Schein",
    "C. Die Reflexion",
    "1. Die setzende Reflexion",
    "2. Die äußere Reflexion",
    "Anmerkung",
    "3. Bestimmende Reflexion",
    "Zweites Kapitel. Die Wesenheiten oder die Reflexions-Bestimmungen",
    "Anmerkung",
    "A. Die Identität",
    "Anmerkung 1",
    "Anmerkung 2",
    "B. Der Unterschied",
    "1. Der absolute Unterschied",
    "2. Die Verschiedenheit",
    "Anmerkung",
    "3. Der Gegensatz",
    "Anmerkung",
    "C. Der Widerspruch",
    "Anmerkung 1",
    "Anmerkung 2",
    "Anmerkung 3",
    "Drittes Kapitel. Der Grund",
    "Anmerkung",
    "A. Der absolute Grund",
    "a. Form und Wesen",
    "b. Form und Materie",
    "c. Form und Inhalt",
    "B. Der bestimmte Grund",
    "a. Der formelle Grund",
    "Anmerkung",
    "b. Der reale Grund",
    "Anmerkung",
    "c. Der vollständige Grund",
    "C. Die Bedingung",
    "a. Das relativ Unbedingte",
    "b. Das absolute Unbedingte",
    "c. Hervorgang der Sache in die Existenz",
    "Zweiter Abschnitt. Die Erscheinung",
    "Erstes Kapitel. Die Existenz",
    "A. Das Ding und seine Eigenschaften",
    "a. Ding an sich und Existenz",
    "b. Die Eigenschaft",
    "Anmerkung",
    "c. Die Wechselwirkung der Dinge",
    "B. Das Bestehen des Dings aus Materien",
    "C. Die Auflösung des Dinges",
    "Anmerkung",
    "Zweites Kapitel. Die Erscheinung",
    "A. Das Gesetz der Erscheinung",
    "B. Die erscheinende und die an-sich-seiende Welt",
    "C. Auflösung der Erscheinung",
    "Drittes Kapitel. Das wesentliche Verhältnis",
    "A. Das Verhältnis des Ganzen und der Teile",
    "Anmerkung",
    "B. Das Verhältnis der Kraft und ihrer Äußerung",
    "a. Das Bedingtsein der Kraft",
    "b. Die Sollizitation der Kraft",
    "c. Die Unendlichkeit der Kraft",
    "C. Verhältnis des Äußern und Innern",
    "Anmerkung",
    "Dritter Abschnitt. Die Wirklichkeit",
    "Erstes Kapitel. Das Absolute",
    "A. Die Auslegung des Absoluten",
    "B. Das absolute Attribut",
    "C. Der Modus des Absoluten",
    "Anmerkung",
    "Zweites Kapitel. Die Wirklichkeit",
    "A. Zufälligkeit oder formelle Wirklichkeit, Möglichkeit und Notwendigkeit",
    "B. Relative Notwendigkeit oder reale Wirklichkeit, Möglichkeit und Notwendigkeit",
    "C. Absolute Notwendigkeit",
    "Drittes Kapitel. Das absolute Verhältnis",
    "A. Das Verhältnis der Substantialität",
    "B. Das Kausalitätsverhältnis",
    "a. Die formelle Kausalität",
    "b. Das bestimmte Kausalitätsverhältnis",
    "c. Wirkung und Gegenwirkung",
    "C. Die Wechselwirkung",
    "Zweiter Teil. Die subjektive Logik oder die Lehre vom Begriff",
    "Vorbericht",
    "Vom Begriff im allgemeinen",
    "Einteilung",
    "Erster Abschnitt. Die Subjektivität",
    "Erstes Kapitel. Der Begriff",
    "A) Der allgemeine Begriff",
    "B) Der besondere Begriff",
    "Anmerkung",
    "C) Das Einzelne",
    "Zweites Kapitel. Das Urteil",
    "A. Das Urteil des Daseins",
    "a. Das positive Urteil",
    "b. Negatives Urteil",
    "c. Unendliches Urteil",
    "B. Das Urteil der Reflexion",
    "a. Das singuläre Urteil",
    "b. Das partikuläre Urteil",
    "c. Das universelle Urteil",
    "C. Das Urteil der Notwendigkeit",
    "a. Das kategorische Urteil",
    "b. Das hypothetische Urteil",
    "c. Das disjunktive Urteil",
    "D. Das Urteil des Begriffs",
    "a. Das assertorische Urteil",
    "b. Das problematische Urteil",
    "c. Das apodiktische Urteil",
    "Drittes Kapitel. Der Schluss",
    "A. Der Schluss des Daseins",
    "a. Erste Figur des Schlusses",
    "b. Die zweite Figur: B-E-A",
    "c. Die dritte Figur: E-A-B",
    "d. Die vierte Figur: A-A-A oder der mathematische Schluss",
    "Anmerkung",
    "B. Der Schluss der Reflexion",
    "a. Schluss der Allheit",
    "b. Schluss der Induktion",
    "c. Der Schluss der Analogie",
    "C. Der Schluss der Notwendigkeit",
    "a. Der kategorische Schluss",
    "b. Der hypothetische Schluss",
    "c. Der disjunktive Schluss",
    "Zweiter Abschnitt. Die Objektivität",
    "Erstes Kapitel. Der Mechanismus",
    "A. Das mechanische Objekt",
    "B. Der mechanische Prozess",
    "a. Der formale mechanische Prozess",
    "b. Der reale mechanische Prozess",
    "c. Das Produkt des mechanischen Prozesses",
    "C. Der absolute Mechanismus",
    "a. Das Centrum",
    "b. Das Gesetz",
    "c. Übergang des Mechanismus",
    "Zweites Kapitel. Der Chemismus",
    "A. Das chemische Objekt",
    "B. Der Prozess",
    "C. Übergang des Chemismus",
    "Drittes Kapitel. Teleologie",
    "A. Der subjektive Zweck",
    "B. Das Mittel",
    "C. Der ausgeführte Zweck",
    "Dritter Abschnitt. Die Idee",
    "Erstes Kapitel. Das Leben",
    "A. Das lebendige Individuum",
    "B. Der Lebens-Prozess",
    "C. Die Gattung",
    "Zweites Kapitel. Die Idee des Erkennens",
    "A. Die Idee des Wahren",
    "a. Das analytische Erkennen",
    "b. Das synthetische Erkennen",
    "1. Die Definition",
    "2. Die Einteilung",
    "3. Der Lehrsatz",
    "B. Die Idee des Guten",
    "Drittes Kapitel. Die absolute Idee",
];

pub fn flat_toc_entries() -> Vec<crate::FlatTocEntry> {
    super::toc::entries()
        .iter()
        .enumerate()
        .map(|(i, e)| {
            (
                i,
                e.page.map(str::to_string),
                e.depth,
                MODERNIZED_LABELS[i],
                Some(e.slug),
            )
        })
        .collect()
}

pub fn label(index: usize) -> &'static str {
    MODERNIZED_LABELS[index]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn one_label_per_toc_entry() {
        assert_eq!(MODERNIZED_LABELS.len(), super::super::toc::toc_len());
    }

    #[test]
    fn no_pre_reform_spellings_survive() {
        for l in MODERNIZED_LABELS {
            for bad in [
                "Seyn", "seyn", "Theil", "theil", "Urtheil", "ßt", "Maass", "Maaß",
            ] {
                assert!(!l.contains(bad), "unmodernized {bad:?} in {l:?}");
            }
        }
    }
}
