/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
    UseSuspenseQueryOptions,
    UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import { customFetch } from ".././fetcher";
import type {
    CreateResourceRequest,
    ListResourcesParams,
    ResourceListResponse,
    UpdateResourceRequest,
} from "../model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary List resources for a sentence range (public)
 */
export type listResourcesResponse200 = {
    data: ResourceListResponse;
    status: 200;
};

export type listResourcesResponse404 = {
    data: void;
    status: 404;
};

export type listResourcesResponseSuccess = listResourcesResponse200 & {
    headers: Headers;
};
export type listResourcesResponseError = listResourcesResponse404 & {
    headers: Headers;
};

export const getListResourcesUrl = (
    slug: string,
    params: ListResourcesParams,
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(
                key,
                value === null ? "null" : value.toString(),
            );
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/api/books/${slug}/resources?${stringifiedParams}`
        : `/api/books/${slug}/resources`;
};

export const listResources = async (
    slug: string,
    params: ListResourcesParams,
    options?: RequestInit,
): Promise<listResourcesResponseSuccess> => {
    return customFetch<listResourcesResponseSuccess>(
        getListResourcesUrl(slug, params),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getListResourcesQueryKey = (
    slug: string,
    params?: ListResourcesParams,
) => {
    return [
        `/api/books/${slug}/resources`,
        ...(params ? [params] : []),
    ] as const;
};

export const getListResourcesQueryOptions = <
    TData = Awaited<ReturnType<typeof listResources>>,
    TError = void,
>(
    slug: string,
    params: ListResourcesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listResources>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getListResourcesQueryKey(slug, params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listResources>>> = ({
        signal,
    }) => listResources(slug, params, { signal, ...requestOptions });

    return {
        queryKey,
        queryFn,
        enabled: !!slug,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof listResources>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListResourcesQueryResult = NonNullable<
    Awaited<ReturnType<typeof listResources>>
>;
export type ListResourcesQueryError = void;

export function useListResources<
    TData = Awaited<ReturnType<typeof listResources>>,
    TError = void,
>(
    slug: string,
    params: ListResourcesParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listResources>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listResources>>,
                    TError,
                    Awaited<ReturnType<typeof listResources>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListResources<
    TData = Awaited<ReturnType<typeof listResources>>,
    TError = void,
>(
    slug: string,
    params: ListResourcesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listResources>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listResources>>,
                    TError,
                    Awaited<ReturnType<typeof listResources>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListResources<
    TData = Awaited<ReturnType<typeof listResources>>,
    TError = void,
>(
    slug: string,
    params: ListResourcesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listResources>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List resources for a sentence range (public)
 */

export function useListResources<
    TData = Awaited<ReturnType<typeof listResources>>,
    TError = void,
>(
    slug: string,
    params: ListResourcesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listResources>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListResourcesQueryOptions(slug, params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}

export const getListResourcesSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof listResources>>,
    TError = void,
>(
    slug: string,
    params: ListResourcesParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listResources>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getListResourcesQueryKey(slug, params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listResources>>> = ({
        signal,
    }) => listResources(slug, params, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listResources>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListResourcesSuspenseQueryResult = NonNullable<
    Awaited<ReturnType<typeof listResources>>
>;
export type ListResourcesSuspenseQueryError = void;

export function useListResourcesSuspense<
    TData = Awaited<ReturnType<typeof listResources>>,
    TError = void,
>(
    slug: string,
    params: ListResourcesParams,
    options: {
        query: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listResources>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListResourcesSuspense<
    TData = Awaited<ReturnType<typeof listResources>>,
    TError = void,
>(
    slug: string,
    params: ListResourcesParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listResources>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListResourcesSuspense<
    TData = Awaited<ReturnType<typeof listResources>>,
    TError = void,
>(
    slug: string,
    params: ListResourcesParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listResources>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List resources for a sentence range (public)
 */

export function useListResourcesSuspense<
    TData = Awaited<ReturnType<typeof listResources>>,
    TError = void,
>(
    slug: string,
    params: ListResourcesParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listResources>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListResourcesSuspenseQueryOptions(
        slug,
        params,
        options,
    );

    const query = useSuspenseQuery(
        queryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a new resource (editor only)
 */
export type createResourceResponse200 = {
    data: ResourceListResponse;
    status: 200;
};

export type createResourceResponse400 = {
    data: void;
    status: 400;
};

export type createResourceResponse401 = {
    data: void;
    status: 401;
};

export type createResourceResponse403 = {
    data: void;
    status: 403;
};

export type createResourceResponseSuccess = createResourceResponse200 & {
    headers: Headers;
};
export type createResourceResponseError = (
    | createResourceResponse400
    | createResourceResponse401
    | createResourceResponse403
) & {
    headers: Headers;
};

export const getCreateResourceUrl = (slug: string) => {
    return `/api/books/${slug}/resources`;
};

export const createResource = async (
    slug: string,
    createResourceRequest: CreateResourceRequest,
    options?: RequestInit,
): Promise<createResourceResponseSuccess> => {
    return customFetch<createResourceResponseSuccess>(
        getCreateResourceUrl(slug),
        {
            ...options,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(createResourceRequest),
        },
    );
};

export const getCreateResourceMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof createResource>>,
        TError,
        { slug: string; data: CreateResourceRequest },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof createResource>>,
    TError,
    { slug: string; data: CreateResourceRequest },
    TContext
> => {
    const mutationKey = ["createResource"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof createResource>>,
        { slug: string; data: CreateResourceRequest }
    > = (props) => {
        const { slug, data } = props ?? {};

        return createResource(slug, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type CreateResourceMutationResult = NonNullable<
    Awaited<ReturnType<typeof createResource>>
>;
export type CreateResourceMutationBody = CreateResourceRequest;
export type CreateResourceMutationError = void;

/**
 * @summary Create a new resource (editor only)
 */
export const useCreateResource = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof createResource>>,
            TError,
            { slug: string; data: CreateResourceRequest },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof createResource>>,
    TError,
    { slug: string; data: CreateResourceRequest },
    TContext
> => {
    return useMutation(getCreateResourceMutationOptions(options), queryClient);
};
/**
 * @summary Update an existing resource (editor only)
 */
export type updateResourceResponse200 = {
    data: void;
    status: 200;
};

export type updateResourceResponse400 = {
    data: void;
    status: 400;
};

export type updateResourceResponse401 = {
    data: void;
    status: 401;
};

export type updateResourceResponse403 = {
    data: void;
    status: 403;
};

export type updateResourceResponse404 = {
    data: void;
    status: 404;
};

export type updateResourceResponseSuccess = updateResourceResponse200 & {
    headers: Headers;
};
export type updateResourceResponseError = (
    | updateResourceResponse400
    | updateResourceResponse401
    | updateResourceResponse403
    | updateResourceResponse404
) & {
    headers: Headers;
};

export const getUpdateResourceUrl = (slug: string, id: string) => {
    return `/api/books/${slug}/resources/${id}`;
};

export const updateResource = async (
    slug: string,
    id: string,
    updateResourceRequest: UpdateResourceRequest,
    options?: RequestInit,
): Promise<updateResourceResponseSuccess> => {
    return customFetch<updateResourceResponseSuccess>(
        getUpdateResourceUrl(slug, id),
        {
            ...options,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(updateResourceRequest),
        },
    );
};

export const getUpdateResourceMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof updateResource>>,
        TError,
        { slug: string; id: string; data: UpdateResourceRequest },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof updateResource>>,
    TError,
    { slug: string; id: string; data: UpdateResourceRequest },
    TContext
> => {
    const mutationKey = ["updateResource"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof updateResource>>,
        { slug: string; id: string; data: UpdateResourceRequest }
    > = (props) => {
        const { slug, id, data } = props ?? {};

        return updateResource(slug, id, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type UpdateResourceMutationResult = NonNullable<
    Awaited<ReturnType<typeof updateResource>>
>;
export type UpdateResourceMutationBody = UpdateResourceRequest;
export type UpdateResourceMutationError = void;

/**
 * @summary Update an existing resource (editor only)
 */
export const useUpdateResource = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof updateResource>>,
            TError,
            { slug: string; id: string; data: UpdateResourceRequest },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof updateResource>>,
    TError,
    { slug: string; id: string; data: UpdateResourceRequest },
    TContext
> => {
    return useMutation(getUpdateResourceMutationOptions(options), queryClient);
};
/**
 * @summary Soft-delete a resource (editor only)
 */
export type deleteResourceResponse200 = {
    data: void;
    status: 200;
};

export type deleteResourceResponse401 = {
    data: void;
    status: 401;
};

export type deleteResourceResponse403 = {
    data: void;
    status: 403;
};

export type deleteResourceResponse404 = {
    data: void;
    status: 404;
};

export type deleteResourceResponseSuccess = deleteResourceResponse200 & {
    headers: Headers;
};
export type deleteResourceResponseError = (
    | deleteResourceResponse401
    | deleteResourceResponse403
    | deleteResourceResponse404
) & {
    headers: Headers;
};

export const getDeleteResourceUrl = (slug: string, id: string) => {
    return `/api/books/${slug}/resources/${id}`;
};

export const deleteResource = async (
    slug: string,
    id: string,
    options?: RequestInit,
): Promise<deleteResourceResponseSuccess> => {
    return customFetch<deleteResourceResponseSuccess>(
        getDeleteResourceUrl(slug, id),
        {
            ...options,
            method: "DELETE",
        },
    );
};

export const getDeleteResourceMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof deleteResource>>,
        TError,
        { slug: string; id: string },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof deleteResource>>,
    TError,
    { slug: string; id: string },
    TContext
> => {
    const mutationKey = ["deleteResource"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof deleteResource>>,
        { slug: string; id: string }
    > = (props) => {
        const { slug, id } = props ?? {};

        return deleteResource(slug, id, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type DeleteResourceMutationResult = NonNullable<
    Awaited<ReturnType<typeof deleteResource>>
>;

export type DeleteResourceMutationError = void;

/**
 * @summary Soft-delete a resource (editor only)
 */
export const useDeleteResource = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof deleteResource>>,
            TError,
            { slug: string; id: string },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof deleteResource>>,
    TError,
    { slug: string; id: string },
    TContext
> => {
    return useMutation(getDeleteResourceMutationOptions(options), queryClient);
};
