/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
    UseSuspenseQueryOptions,
    UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import { customFetch } from ".././fetcher";
import type {
    CreateTopicRequest,
    TopicAdminListResponse,
    TopicAdminResponse,
    UpdateTopicRequest,
} from "../model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type adminListTopicsResponse200 = {
    data: TopicAdminListResponse;
    status: 200;
};

export type adminListTopicsResponse403 = {
    data: void;
    status: 403;
};

export type adminListTopicsResponseSuccess = adminListTopicsResponse200 & {
    headers: Headers;
};
export type adminListTopicsResponseError = adminListTopicsResponse403 & {
    headers: Headers;
};

export const getAdminListTopicsUrl = () => {
    return `/api/admin/topics`;
};

/**
 * @summary List topics with per-topic article usage counts
 */
export const adminListTopics = async (
    options?: RequestInit,
): Promise<adminListTopicsResponseSuccess> => {
    return customFetch<adminListTopicsResponseSuccess>(
        getAdminListTopicsUrl(),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getAdminListTopicsQueryKey = () => {
    return [`/api/admin/topics`] as const;
};

export const getAdminListTopicsQueryOptions = <
    TData = Awaited<ReturnType<typeof adminListTopics>>,
    TError = void,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof adminListTopics>>,
            TError,
            TData
        >
    >;
    request?: SecondParameter<typeof customFetch>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getAdminListTopicsQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof adminListTopics>>
    > = ({ signal }) => adminListTopics({ signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof adminListTopics>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminListTopicsQueryResult = NonNullable<
    Awaited<ReturnType<typeof adminListTopics>>
>;
export type AdminListTopicsQueryError = void;

export function useAdminListTopics<
    TData = Awaited<ReturnType<typeof adminListTopics>>,
    TError = void,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminListTopics>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminListTopics>>,
                    TError,
                    Awaited<ReturnType<typeof adminListTopics>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminListTopics<
    TData = Awaited<ReturnType<typeof adminListTopics>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminListTopics>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof adminListTopics>>,
                    TError,
                    Awaited<ReturnType<typeof adminListTopics>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminListTopics<
    TData = Awaited<ReturnType<typeof adminListTopics>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminListTopics>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List topics with per-topic article usage counts
 */

export function useAdminListTopics<
    TData = Awaited<ReturnType<typeof adminListTopics>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof adminListTopics>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getAdminListTopicsQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}

export const getAdminListTopicsSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof adminListTopics>>,
    TError = void,
>(options?: {
    query?: Partial<
        UseSuspenseQueryOptions<
            Awaited<ReturnType<typeof adminListTopics>>,
            TError,
            TData
        >
    >;
    request?: SecondParameter<typeof customFetch>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getAdminListTopicsQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof adminListTopics>>
    > = ({ signal }) => adminListTopics({ signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof adminListTopics>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminListTopicsSuspenseQueryResult = NonNullable<
    Awaited<ReturnType<typeof adminListTopics>>
>;
export type AdminListTopicsSuspenseQueryError = void;

export function useAdminListTopicsSuspense<
    TData = Awaited<ReturnType<typeof adminListTopics>>,
    TError = void,
>(
    options: {
        query: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof adminListTopics>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminListTopicsSuspense<
    TData = Awaited<ReturnType<typeof adminListTopics>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof adminListTopics>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAdminListTopicsSuspense<
    TData = Awaited<ReturnType<typeof adminListTopics>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof adminListTopics>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List topics with per-topic article usage counts
 */

export function useAdminListTopicsSuspense<
    TData = Awaited<ReturnType<typeof adminListTopics>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof adminListTopics>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getAdminListTopicsSuspenseQueryOptions(options);

    const query = useSuspenseQuery(
        queryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return { ...query, queryKey: queryOptions.queryKey };
}

export type createTopicResponse200 = {
    data: TopicAdminResponse;
    status: 200;
};

export type createTopicResponse400 = {
    data: void;
    status: 400;
};

export type createTopicResponse403 = {
    data: void;
    status: 403;
};

export type createTopicResponseSuccess = createTopicResponse200 & {
    headers: Headers;
};
export type createTopicResponseError = (
    | createTopicResponse400
    | createTopicResponse403
) & {
    headers: Headers;
};

export const getCreateTopicUrl = () => {
    return `/api/admin/topics`;
};

/**
 * @summary Create a topic; the slug is generated from the name and immutable
 */
export const createTopic = async (
    createTopicRequest: CreateTopicRequest,
    options?: RequestInit,
): Promise<createTopicResponseSuccess> => {
    return customFetch<createTopicResponseSuccess>(getCreateTopicUrl(), {
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(createTopicRequest),
    });
};

export const getCreateTopicMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof createTopic>>,
        TError,
        { data: CreateTopicRequest },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof createTopic>>,
    TError,
    { data: CreateTopicRequest },
    TContext
> => {
    const mutationKey = ["createTopic"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof createTopic>>,
        { data: CreateTopicRequest }
    > = (props) => {
        const { data } = props ?? {};

        return createTopic(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type CreateTopicMutationResult = NonNullable<
    Awaited<ReturnType<typeof createTopic>>
>;
export type CreateTopicMutationBody = CreateTopicRequest;
export type CreateTopicMutationError = void;

/**
 * @summary Create a topic; the slug is generated from the name and immutable
 */
export const useCreateTopic = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof createTopic>>,
            TError,
            { data: CreateTopicRequest },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof createTopic>>,
    TError,
    { data: CreateTopicRequest },
    TContext
> => {
    return useMutation(getCreateTopicMutationOptions(options), queryClient);
};
export type deleteTopicResponse200 = {
    data: void;
    status: 200;
};

export type deleteTopicResponse400 = {
    data: void;
    status: 400;
};

export type deleteTopicResponse403 = {
    data: void;
    status: 403;
};

export type deleteTopicResponse404 = {
    data: void;
    status: 404;
};

export type deleteTopicResponseSuccess = deleteTopicResponse200 & {
    headers: Headers;
};
export type deleteTopicResponseError = (
    | deleteTopicResponse400
    | deleteTopicResponse403
    | deleteTopicResponse404
) & {
    headers: Headers;
};

export const getDeleteTopicUrl = (id: string) => {
    return `/api/admin/topics/${id}`;
};

/**
 * @summary Delete a topic; refused while any article still uses it
 */
export const deleteTopic = async (
    id: string,
    options?: RequestInit,
): Promise<deleteTopicResponseSuccess> => {
    return customFetch<deleteTopicResponseSuccess>(getDeleteTopicUrl(id), {
        ...options,
        method: "DELETE",
    });
};

export const getDeleteTopicMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof deleteTopic>>,
        TError,
        { id: string },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof deleteTopic>>,
    TError,
    { id: string },
    TContext
> => {
    const mutationKey = ["deleteTopic"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof deleteTopic>>,
        { id: string }
    > = (props) => {
        const { id } = props ?? {};

        return deleteTopic(id, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type DeleteTopicMutationResult = NonNullable<
    Awaited<ReturnType<typeof deleteTopic>>
>;

export type DeleteTopicMutationError = void;

/**
 * @summary Delete a topic; refused while any article still uses it
 */
export const useDeleteTopic = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof deleteTopic>>,
            TError,
            { id: string },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof deleteTopic>>,
    TError,
    { id: string },
    TContext
> => {
    return useMutation(getDeleteTopicMutationOptions(options), queryClient);
};
export type updateTopicResponse200 = {
    data: TopicAdminResponse;
    status: 200;
};

export type updateTopicResponse400 = {
    data: void;
    status: 400;
};

export type updateTopicResponse403 = {
    data: void;
    status: 403;
};

export type updateTopicResponse404 = {
    data: void;
    status: 404;
};

export type updateTopicResponseSuccess = updateTopicResponse200 & {
    headers: Headers;
};
export type updateTopicResponseError = (
    | updateTopicResponse400
    | updateTopicResponse403
    | updateTopicResponse404
) & {
    headers: Headers;
};

export const getUpdateTopicUrl = (id: string) => {
    return `/api/admin/topics/${id}`;
};

/**
 * @summary Rename a topic (display name only; slug never changes)
 */
export const updateTopic = async (
    id: string,
    updateTopicRequest: UpdateTopicRequest,
    options?: RequestInit,
): Promise<updateTopicResponseSuccess> => {
    return customFetch<updateTopicResponseSuccess>(getUpdateTopicUrl(id), {
        ...options,
        method: "PATCH",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(updateTopicRequest),
    });
};

export const getUpdateTopicMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof updateTopic>>,
        TError,
        { id: string; data: UpdateTopicRequest },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof updateTopic>>,
    TError,
    { id: string; data: UpdateTopicRequest },
    TContext
> => {
    const mutationKey = ["updateTopic"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof updateTopic>>,
        { id: string; data: UpdateTopicRequest }
    > = (props) => {
        const { id, data } = props ?? {};

        return updateTopic(id, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type UpdateTopicMutationResult = NonNullable<
    Awaited<ReturnType<typeof updateTopic>>
>;
export type UpdateTopicMutationBody = UpdateTopicRequest;
export type UpdateTopicMutationError = void;

/**
 * @summary Rename a topic (display name only; slug never changes)
 */
export const useUpdateTopic = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof updateTopic>>,
            TError,
            { id: string; data: UpdateTopicRequest },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof updateTopic>>,
    TError,
    { id: string; data: UpdateTopicRequest },
    TContext
> => {
    return useMutation(getUpdateTopicMutationOptions(options), queryClient);
};
