/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
    UseSuspenseQueryOptions,
    UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import { customFetch } from ".././fetcher.ts";
import type {
    CollegiumDetailResponse,
    CreateCollegiumRequest,
    DecideJoinRequestRequest,
    DiscoverCollegiaParams,
    DiscoverCollegiaResponse,
    InviteTokenResponse,
    JoinByTokenResponse,
    JoinRequestListResponse,
    MyCollegiaResponse,
    RemoveMemberResponse,
    UpdateCollegiumRequest,
    UpdateMemberRequest,
} from "../model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
    query: T,
    queryKey: K,
): T & { queryKey: K } => {
    const result = { queryKey } as T & { queryKey: K };
    for (const key of Object.keys(query)) {
        // The explicit queryKey always wins, matching the previous
        // `{ ...query, queryKey }` spread where it was set last.
        if (key === "queryKey") continue;
        Object.defineProperty(result, key, {
            enumerable: true,
            configurable: true,
            get: () => (query as Record<string, unknown>)[key],
        });
    }
    return result;
};

export type discoverCollegiaResponse200 = {
    data: DiscoverCollegiaResponse;
    status: 200;
};

export type discoverCollegiaResponse401 = {
    data: void;
    status: 401;
};

export type discoverCollegiaResponseSuccess = discoverCollegiaResponse200 & {
    headers: Headers;
};
export type discoverCollegiaResponseError = discoverCollegiaResponse401 & {
    headers: Headers;
};

export const getDiscoverCollegiaUrl = (params?: DiscoverCollegiaParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(
                key,
                value === null ? "null" : String(value),
            );
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/api/collegia?${stringifiedParams}`
        : `/api/collegia`;
};

/**
 * @summary Browse public collegia (Discover)
 */
export const discoverCollegia = async (
    params?: DiscoverCollegiaParams,
    options?: Parameters<typeof customFetch>[1],
): Promise<discoverCollegiaResponseSuccess> => {
    return customFetch<discoverCollegiaResponseSuccess>(
        getDiscoverCollegiaUrl(params),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getDiscoverCollegiaQueryKey = (
    params?: DiscoverCollegiaParams,
) => {
    return [`/api/collegia`, ...(params ? [params] : [])] as const;
};

export const getDiscoverCollegiaQueryOptions = <
    TData = Awaited<ReturnType<typeof discoverCollegia>>,
    TError = void,
>(
    params?: DiscoverCollegiaParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof discoverCollegia>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getDiscoverCollegiaQueryKey(params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof discoverCollegia>>
    > = ({ signal }) => discoverCollegia(params, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof discoverCollegia>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DiscoverCollegiaQueryResult = NonNullable<
    Awaited<ReturnType<typeof discoverCollegia>>
>;
export type DiscoverCollegiaQueryError = void;

export function useDiscoverCollegia<
    TData = Awaited<ReturnType<typeof discoverCollegia>>,
    TError = void,
>(
    params: undefined | DiscoverCollegiaParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof discoverCollegia>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof discoverCollegia>>,
                    TError,
                    Awaited<ReturnType<typeof discoverCollegia>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDiscoverCollegia<
    TData = Awaited<ReturnType<typeof discoverCollegia>>,
    TError = void,
>(
    params?: DiscoverCollegiaParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof discoverCollegia>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof discoverCollegia>>,
                    TError,
                    Awaited<ReturnType<typeof discoverCollegia>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDiscoverCollegia<
    TData = Awaited<ReturnType<typeof discoverCollegia>>,
    TError = void,
>(
    params?: DiscoverCollegiaParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof discoverCollegia>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Browse public collegia (Discover)
 */

export function useDiscoverCollegia<
    TData = Awaited<ReturnType<typeof discoverCollegia>>,
    TError = void,
>(
    params?: DiscoverCollegiaParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof discoverCollegia>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getDiscoverCollegiaQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return withQueryKey(query, queryOptions.queryKey);
}

export const getDiscoverCollegiaSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof discoverCollegia>>,
    TError = void,
>(
    params?: DiscoverCollegiaParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof discoverCollegia>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getDiscoverCollegiaQueryKey(params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof discoverCollegia>>
    > = ({ signal }) => discoverCollegia(params, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof discoverCollegia>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DiscoverCollegiaSuspenseQueryResult = NonNullable<
    Awaited<ReturnType<typeof discoverCollegia>>
>;
export type DiscoverCollegiaSuspenseQueryError = void;

export function useDiscoverCollegiaSuspense<
    TData = Awaited<ReturnType<typeof discoverCollegia>>,
    TError = void,
>(
    params: undefined | DiscoverCollegiaParams,
    options: {
        query: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof discoverCollegia>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDiscoverCollegiaSuspense<
    TData = Awaited<ReturnType<typeof discoverCollegia>>,
    TError = void,
>(
    params?: DiscoverCollegiaParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof discoverCollegia>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDiscoverCollegiaSuspense<
    TData = Awaited<ReturnType<typeof discoverCollegia>>,
    TError = void,
>(
    params?: DiscoverCollegiaParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof discoverCollegia>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Browse public collegia (Discover)
 */

export function useDiscoverCollegiaSuspense<
    TData = Awaited<ReturnType<typeof discoverCollegia>>,
    TError = void,
>(
    params?: DiscoverCollegiaParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof discoverCollegia>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getDiscoverCollegiaSuspenseQueryOptions(
        params,
        options,
    );

    const query = useSuspenseQuery(
        queryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return withQueryKey(query, queryOptions.queryKey);
}

export type createCollegiumResponse200 = {
    data: CollegiumDetailResponse;
    status: 200;
};

export type createCollegiumResponse400 = {
    data: void;
    status: 400;
};

export type createCollegiumResponse401 = {
    data: void;
    status: 401;
};

export type createCollegiumResponseSuccess = createCollegiumResponse200 & {
    headers: Headers;
};
export type createCollegiumResponseError = (
    | createCollegiumResponse400
    | createCollegiumResponse401
) & {
    headers: Headers;
};

export const getCreateCollegiumUrl = () => {
    return `/api/collegia`;
};

/**
 * @summary Create a collegium; the creator becomes its first admin
 */
export const createCollegium = async (
    createCollegiumRequest: CreateCollegiumRequest,
    options?: Parameters<typeof customFetch>[1],
): Promise<createCollegiumResponseSuccess> => {
    return customFetch<createCollegiumResponseSuccess>(
        getCreateCollegiumUrl(),
        {
            ...options,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(createCollegiumRequest),
        },
    );
};

export const getCreateCollegiumMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof createCollegium>>,
        TError,
        { data: CreateCollegiumRequest },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof createCollegium>>,
    TError,
    { data: CreateCollegiumRequest },
    TContext
> => {
    const mutationKey = ["createCollegium"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof createCollegium>>,
        { data: CreateCollegiumRequest }
    > = (props) => {
        const { data } = props ?? {};

        return createCollegium(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type CreateCollegiumMutationResult = NonNullable<
    Awaited<ReturnType<typeof createCollegium>>
>;
export type CreateCollegiumMutationBody = CreateCollegiumRequest;
export type CreateCollegiumMutationError = void;

/**
 * @summary Create a collegium; the creator becomes its first admin
 */
export const useCreateCollegium = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof createCollegium>>,
            TError,
            { data: CreateCollegiumRequest },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof createCollegium>>,
    TError,
    { data: CreateCollegiumRequest },
    TContext
> => {
    return useMutation(getCreateCollegiumMutationOptions(options), queryClient);
};
export type joinByTokenResponse200 = {
    data: JoinByTokenResponse;
    status: 200;
};

export type joinByTokenResponse401 = {
    data: void;
    status: 401;
};

export type joinByTokenResponse404 = {
    data: void;
    status: 404;
};

export type joinByTokenResponseSuccess = joinByTokenResponse200 & {
    headers: Headers;
};
export type joinByTokenResponseError = (
    | joinByTokenResponse401
    | joinByTokenResponse404
) & {
    headers: Headers;
};

export const getJoinByTokenUrl = (token: string) => {
    return `/api/collegia/join/${token}`;
};

/**
 * @summary Join a collegium via an invite link
 */
export const joinByToken = async (
    token: string,
    options?: Parameters<typeof customFetch>[1],
): Promise<joinByTokenResponseSuccess> => {
    return customFetch<joinByTokenResponseSuccess>(getJoinByTokenUrl(token), {
        ...options,
        method: "POST",
    });
};

export const getJoinByTokenMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof joinByToken>>,
        TError,
        { token: string },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof joinByToken>>,
    TError,
    { token: string },
    TContext
> => {
    const mutationKey = ["joinByToken"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof joinByToken>>,
        { token: string }
    > = (props) => {
        const { token } = props ?? {};

        return joinByToken(token, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type JoinByTokenMutationResult = NonNullable<
    Awaited<ReturnType<typeof joinByToken>>
>;

export type JoinByTokenMutationError = void;

/**
 * @summary Join a collegium via an invite link
 */
export const useJoinByToken = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof joinByToken>>,
            TError,
            { token: string },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof joinByToken>>,
    TError,
    { token: string },
    TContext
> => {
    return useMutation(getJoinByTokenMutationOptions(options), queryClient);
};
export type getCollegiumResponse200 = {
    data: CollegiumDetailResponse;
    status: 200;
};

export type getCollegiumResponse401 = {
    data: void;
    status: 401;
};

export type getCollegiumResponse404 = {
    data: void;
    status: 404;
};

export type getCollegiumResponseSuccess = getCollegiumResponse200 & {
    headers: Headers;
};
export type getCollegiumResponseError = (
    | getCollegiumResponse401
    | getCollegiumResponse404
) & {
    headers: Headers;
};

export const getGetCollegiumUrl = (slug: string) => {
    return `/api/collegia/${slug}`;
};

/**
 * @summary Get a collegium's page (member list for members, steward fields for stewards)
 */
export const getCollegium = async (
    slug: string,
    options?: Parameters<typeof customFetch>[1],
): Promise<getCollegiumResponseSuccess> => {
    return customFetch<getCollegiumResponseSuccess>(getGetCollegiumUrl(slug), {
        ...options,
        method: "GET",
    });
};

export const getGetCollegiumQueryKey = (slug: string) => {
    return [`/api/collegia/${slug}`] as const;
};

export const getGetCollegiumQueryOptions = <
    TData = Awaited<ReturnType<typeof getCollegium>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCollegium>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetCollegiumQueryKey(slug);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCollegium>>> = ({
        signal,
    }) => getCollegium(slug, { signal, ...requestOptions });

    return {
        queryKey,
        queryFn,
        enabled: slug !== null && slug !== undefined,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getCollegium>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCollegiumQueryResult = NonNullable<
    Awaited<ReturnType<typeof getCollegium>>
>;
export type GetCollegiumQueryError = void;

export function useGetCollegium<
    TData = Awaited<ReturnType<typeof getCollegium>>,
    TError = void,
>(
    slug: string,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCollegium>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getCollegium>>,
                    TError,
                    Awaited<ReturnType<typeof getCollegium>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCollegium<
    TData = Awaited<ReturnType<typeof getCollegium>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCollegium>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getCollegium>>,
                    TError,
                    Awaited<ReturnType<typeof getCollegium>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCollegium<
    TData = Awaited<ReturnType<typeof getCollegium>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCollegium>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a collegium's page (member list for members, steward fields for stewards)
 */

export function useGetCollegium<
    TData = Awaited<ReturnType<typeof getCollegium>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCollegium>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetCollegiumQueryOptions(slug, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return withQueryKey(query, queryOptions.queryKey);
}

export const getGetCollegiumSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof getCollegium>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof getCollegium>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetCollegiumQueryKey(slug);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCollegium>>> = ({
        signal,
    }) => getCollegium(slug, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCollegium>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCollegiumSuspenseQueryResult = NonNullable<
    Awaited<ReturnType<typeof getCollegium>>
>;
export type GetCollegiumSuspenseQueryError = void;

export function useGetCollegiumSuspense<
    TData = Awaited<ReturnType<typeof getCollegium>>,
    TError = void,
>(
    slug: string,
    options: {
        query: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof getCollegium>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCollegiumSuspense<
    TData = Awaited<ReturnType<typeof getCollegium>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof getCollegium>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCollegiumSuspense<
    TData = Awaited<ReturnType<typeof getCollegium>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof getCollegium>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a collegium's page (member list for members, steward fields for stewards)
 */

export function useGetCollegiumSuspense<
    TData = Awaited<ReturnType<typeof getCollegium>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof getCollegium>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetCollegiumSuspenseQueryOptions(slug, options);

    const query = useSuspenseQuery(
        queryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return withQueryKey(query, queryOptions.queryKey);
}

export type updateCollegiumResponse200 = {
    data: CollegiumDetailResponse;
    status: 200;
};

export type updateCollegiumResponse400 = {
    data: void;
    status: 400;
};

export type updateCollegiumResponse403 = {
    data: void;
    status: 403;
};

export type updateCollegiumResponse404 = {
    data: void;
    status: 404;
};

export type updateCollegiumResponseSuccess = updateCollegiumResponse200 & {
    headers: Headers;
};
export type updateCollegiumResponseError = (
    | updateCollegiumResponse400
    | updateCollegiumResponse403
    | updateCollegiumResponse404
) & {
    headers: Headers;
};

export const getUpdateCollegiumUrl = (slug: string) => {
    return `/api/collegia/${slug}`;
};

/**
 * @summary Update collegium metadata (name, description, privacy) — collegium stewards only
 */
export const updateCollegium = async (
    slug: string,
    updateCollegiumRequest: UpdateCollegiumRequest,
    options?: Parameters<typeof customFetch>[1],
): Promise<updateCollegiumResponseSuccess> => {
    return customFetch<updateCollegiumResponseSuccess>(
        getUpdateCollegiumUrl(slug),
        {
            ...options,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(updateCollegiumRequest),
        },
    );
};

export const getUpdateCollegiumMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof updateCollegium>>,
        TError,
        { slug: string; data: UpdateCollegiumRequest },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof updateCollegium>>,
    TError,
    { slug: string; data: UpdateCollegiumRequest },
    TContext
> => {
    const mutationKey = ["updateCollegium"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof updateCollegium>>,
        { slug: string; data: UpdateCollegiumRequest }
    > = (props) => {
        const { slug, data } = props ?? {};

        return updateCollegium(slug, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type UpdateCollegiumMutationResult = NonNullable<
    Awaited<ReturnType<typeof updateCollegium>>
>;
export type UpdateCollegiumMutationBody = UpdateCollegiumRequest;
export type UpdateCollegiumMutationError = void;

/**
 * @summary Update collegium metadata (name, description, privacy) — collegium stewards only
 */
export const useUpdateCollegium = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof updateCollegium>>,
            TError,
            { slug: string; data: UpdateCollegiumRequest },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof updateCollegium>>,
    TError,
    { slug: string; data: UpdateCollegiumRequest },
    TContext
> => {
    return useMutation(getUpdateCollegiumMutationOptions(options), queryClient);
};
export type rotateInviteTokenResponse200 = {
    data: InviteTokenResponse;
    status: 200;
};

export type rotateInviteTokenResponse403 = {
    data: void;
    status: 403;
};

export type rotateInviteTokenResponse404 = {
    data: void;
    status: 404;
};

export type rotateInviteTokenResponseSuccess = rotateInviteTokenResponse200 & {
    headers: Headers;
};
export type rotateInviteTokenResponseError = (
    | rotateInviteTokenResponse403
    | rotateInviteTokenResponse404
) & {
    headers: Headers;
};

export const getRotateInviteTokenUrl = (slug: string) => {
    return `/api/collegia/${slug}/invite-token`;
};

/**
 * @summary Generate or rotate the collegium's invite link token — collegium stewards only
 */
export const rotateInviteToken = async (
    slug: string,
    options?: Parameters<typeof customFetch>[1],
): Promise<rotateInviteTokenResponseSuccess> => {
    return customFetch<rotateInviteTokenResponseSuccess>(
        getRotateInviteTokenUrl(slug),
        {
            ...options,
            method: "POST",
        },
    );
};

export const getRotateInviteTokenMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof rotateInviteToken>>,
        TError,
        { slug: string },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof rotateInviteToken>>,
    TError,
    { slug: string },
    TContext
> => {
    const mutationKey = ["rotateInviteToken"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof rotateInviteToken>>,
        { slug: string }
    > = (props) => {
        const { slug } = props ?? {};

        return rotateInviteToken(slug, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type RotateInviteTokenMutationResult = NonNullable<
    Awaited<ReturnType<typeof rotateInviteToken>>
>;

export type RotateInviteTokenMutationError = void;

/**
 * @summary Generate or rotate the collegium's invite link token — collegium stewards only
 */
export const useRotateInviteToken = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof rotateInviteToken>>,
            TError,
            { slug: string },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof rotateInviteToken>>,
    TError,
    { slug: string },
    TContext
> => {
    return useMutation(
        getRotateInviteTokenMutationOptions(options),
        queryClient,
    );
};
export type disableInviteTokenResponse200 = {
    data: InviteTokenResponse;
    status: 200;
};

export type disableInviteTokenResponse403 = {
    data: void;
    status: 403;
};

export type disableInviteTokenResponse404 = {
    data: void;
    status: 404;
};

export type disableInviteTokenResponseSuccess =
    disableInviteTokenResponse200 & {
        headers: Headers;
    };
export type disableInviteTokenResponseError = (
    | disableInviteTokenResponse403
    | disableInviteTokenResponse404
) & {
    headers: Headers;
};

export const getDisableInviteTokenUrl = (slug: string) => {
    return `/api/collegia/${slug}/invite-token`;
};

/**
 * @summary Disable the collegium's invite link — collegium stewards only
 */
export const disableInviteToken = async (
    slug: string,
    options?: Parameters<typeof customFetch>[1],
): Promise<disableInviteTokenResponseSuccess> => {
    return customFetch<disableInviteTokenResponseSuccess>(
        getDisableInviteTokenUrl(slug),
        {
            ...options,
            method: "DELETE",
        },
    );
};

export const getDisableInviteTokenMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof disableInviteToken>>,
        TError,
        { slug: string },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof disableInviteToken>>,
    TError,
    { slug: string },
    TContext
> => {
    const mutationKey = ["disableInviteToken"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof disableInviteToken>>,
        { slug: string }
    > = (props) => {
        const { slug } = props ?? {};

        return disableInviteToken(slug, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type DisableInviteTokenMutationResult = NonNullable<
    Awaited<ReturnType<typeof disableInviteToken>>
>;

export type DisableInviteTokenMutationError = void;

/**
 * @summary Disable the collegium's invite link — collegium stewards only
 */
export const useDisableInviteToken = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof disableInviteToken>>,
            TError,
            { slug: string },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof disableInviteToken>>,
    TError,
    { slug: string },
    TContext
> => {
    return useMutation(
        getDisableInviteTokenMutationOptions(options),
        queryClient,
    );
};
export type listJoinRequestsResponse200 = {
    data: JoinRequestListResponse;
    status: 200;
};

export type listJoinRequestsResponse403 = {
    data: void;
    status: 403;
};

export type listJoinRequestsResponse404 = {
    data: void;
    status: 404;
};

export type listJoinRequestsResponseSuccess = listJoinRequestsResponse200 & {
    headers: Headers;
};
export type listJoinRequestsResponseError = (
    | listJoinRequestsResponse403
    | listJoinRequestsResponse404
) & {
    headers: Headers;
};

export const getListJoinRequestsUrl = (slug: string) => {
    return `/api/collegia/${slug}/join-requests`;
};

/**
 * @summary List pending join requests — collegium stewards only
 */
export const listJoinRequests = async (
    slug: string,
    options?: Parameters<typeof customFetch>[1],
): Promise<listJoinRequestsResponseSuccess> => {
    return customFetch<listJoinRequestsResponseSuccess>(
        getListJoinRequestsUrl(slug),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getListJoinRequestsQueryKey = (slug: string) => {
    return [`/api/collegia/${slug}/join-requests`] as const;
};

export const getListJoinRequestsQueryOptions = <
    TData = Awaited<ReturnType<typeof listJoinRequests>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listJoinRequests>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getListJoinRequestsQueryKey(slug);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof listJoinRequests>>
    > = ({ signal }) => listJoinRequests(slug, { signal, ...requestOptions });

    return {
        queryKey,
        queryFn,
        enabled: slug !== null && slug !== undefined,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof listJoinRequests>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListJoinRequestsQueryResult = NonNullable<
    Awaited<ReturnType<typeof listJoinRequests>>
>;
export type ListJoinRequestsQueryError = void;

export function useListJoinRequests<
    TData = Awaited<ReturnType<typeof listJoinRequests>>,
    TError = void,
>(
    slug: string,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listJoinRequests>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listJoinRequests>>,
                    TError,
                    Awaited<ReturnType<typeof listJoinRequests>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListJoinRequests<
    TData = Awaited<ReturnType<typeof listJoinRequests>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listJoinRequests>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listJoinRequests>>,
                    TError,
                    Awaited<ReturnType<typeof listJoinRequests>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListJoinRequests<
    TData = Awaited<ReturnType<typeof listJoinRequests>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listJoinRequests>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List pending join requests — collegium stewards only
 */

export function useListJoinRequests<
    TData = Awaited<ReturnType<typeof listJoinRequests>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listJoinRequests>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListJoinRequestsQueryOptions(slug, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return withQueryKey(query, queryOptions.queryKey);
}

export const getListJoinRequestsSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof listJoinRequests>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listJoinRequests>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getListJoinRequestsQueryKey(slug);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof listJoinRequests>>
    > = ({ signal }) => listJoinRequests(slug, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listJoinRequests>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListJoinRequestsSuspenseQueryResult = NonNullable<
    Awaited<ReturnType<typeof listJoinRequests>>
>;
export type ListJoinRequestsSuspenseQueryError = void;

export function useListJoinRequestsSuspense<
    TData = Awaited<ReturnType<typeof listJoinRequests>>,
    TError = void,
>(
    slug: string,
    options: {
        query: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listJoinRequests>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListJoinRequestsSuspense<
    TData = Awaited<ReturnType<typeof listJoinRequests>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listJoinRequests>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListJoinRequestsSuspense<
    TData = Awaited<ReturnType<typeof listJoinRequests>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listJoinRequests>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List pending join requests — collegium stewards only
 */

export function useListJoinRequestsSuspense<
    TData = Awaited<ReturnType<typeof listJoinRequests>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listJoinRequests>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListJoinRequestsSuspenseQueryOptions(slug, options);

    const query = useSuspenseQuery(
        queryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return withQueryKey(query, queryOptions.queryKey);
}

export type createJoinRequestResponse200 = {
    data: void;
    status: 200;
};

export type createJoinRequestResponse400 = {
    data: void;
    status: 400;
};

export type createJoinRequestResponse404 = {
    data: void;
    status: 404;
};

export type createJoinRequestResponse409 = {
    data: void;
    status: 409;
};

export type createJoinRequestResponseSuccess = createJoinRequestResponse200 & {
    headers: Headers;
};
export type createJoinRequestResponseError = (
    | createJoinRequestResponse400
    | createJoinRequestResponse404
    | createJoinRequestResponse409
) & {
    headers: Headers;
};

export const getCreateJoinRequestUrl = (slug: string) => {
    return `/api/collegia/${slug}/join-requests`;
};

/**
 * @summary Ask to join a public collegium
 */
export const createJoinRequest = async (
    slug: string,
    options?: Parameters<typeof customFetch>[1],
): Promise<createJoinRequestResponseSuccess> => {
    return customFetch<createJoinRequestResponseSuccess>(
        getCreateJoinRequestUrl(slug),
        {
            ...options,
            method: "POST",
        },
    );
};

export const getCreateJoinRequestMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof createJoinRequest>>,
        TError,
        { slug: string },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof createJoinRequest>>,
    TError,
    { slug: string },
    TContext
> => {
    const mutationKey = ["createJoinRequest"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof createJoinRequest>>,
        { slug: string }
    > = (props) => {
        const { slug } = props ?? {};

        return createJoinRequest(slug, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type CreateJoinRequestMutationResult = NonNullable<
    Awaited<ReturnType<typeof createJoinRequest>>
>;

export type CreateJoinRequestMutationError = void;

/**
 * @summary Ask to join a public collegium
 */
export const useCreateJoinRequest = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof createJoinRequest>>,
            TError,
            { slug: string },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof createJoinRequest>>,
    TError,
    { slug: string },
    TContext
> => {
    return useMutation(
        getCreateJoinRequestMutationOptions(options),
        queryClient,
    );
};
export type decideJoinRequestResponse200 = {
    data: void;
    status: 200;
};

export type decideJoinRequestResponse400 = {
    data: void;
    status: 400;
};

export type decideJoinRequestResponse403 = {
    data: void;
    status: 403;
};

export type decideJoinRequestResponse404 = {
    data: void;
    status: 404;
};

export type decideJoinRequestResponse409 = {
    data: void;
    status: 409;
};

export type decideJoinRequestResponseSuccess = decideJoinRequestResponse200 & {
    headers: Headers;
};
export type decideJoinRequestResponseError = (
    | decideJoinRequestResponse400
    | decideJoinRequestResponse403
    | decideJoinRequestResponse404
    | decideJoinRequestResponse409
) & {
    headers: Headers;
};

export const getDecideJoinRequestUrl = (slug: string, id: string) => {
    return `/api/collegia/${slug}/join-requests/${id}`;
};

/**
 * @summary Approve or reject a join request — collegium stewards only
 */
export const decideJoinRequest = async (
    slug: string,
    id: string,
    decideJoinRequestRequest: DecideJoinRequestRequest,
    options?: Parameters<typeof customFetch>[1],
): Promise<decideJoinRequestResponseSuccess> => {
    return customFetch<decideJoinRequestResponseSuccess>(
        getDecideJoinRequestUrl(slug, id),
        {
            ...options,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(decideJoinRequestRequest),
        },
    );
};

export const getDecideJoinRequestMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof decideJoinRequest>>,
        TError,
        { slug: string; id: string; data: DecideJoinRequestRequest },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof decideJoinRequest>>,
    TError,
    { slug: string; id: string; data: DecideJoinRequestRequest },
    TContext
> => {
    const mutationKey = ["decideJoinRequest"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof decideJoinRequest>>,
        { slug: string; id: string; data: DecideJoinRequestRequest }
    > = (props) => {
        const { slug, id, data } = props ?? {};

        return decideJoinRequest(slug, id, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type DecideJoinRequestMutationResult = NonNullable<
    Awaited<ReturnType<typeof decideJoinRequest>>
>;
export type DecideJoinRequestMutationBody = DecideJoinRequestRequest;
export type DecideJoinRequestMutationError = void;

/**
 * @summary Approve or reject a join request — collegium stewards only
 */
export const useDecideJoinRequest = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof decideJoinRequest>>,
            TError,
            { slug: string; id: string; data: DecideJoinRequestRequest },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof decideJoinRequest>>,
    TError,
    { slug: string; id: string; data: DecideJoinRequestRequest },
    TContext
> => {
    return useMutation(
        getDecideJoinRequestMutationOptions(options),
        queryClient,
    );
};
export type removeMemberResponse200 = {
    data: RemoveMemberResponse;
    status: 200;
};

export type removeMemberResponse400 = {
    data: void;
    status: 400;
};

export type removeMemberResponse403 = {
    data: void;
    status: 403;
};

export type removeMemberResponse404 = {
    data: void;
    status: 404;
};

export type removeMemberResponseSuccess = removeMemberResponse200 & {
    headers: Headers;
};
export type removeMemberResponseError = (
    | removeMemberResponse400
    | removeMemberResponse403
    | removeMemberResponse404
) & {
    headers: Headers;
};

export const getRemoveMemberUrl = (slug: string, userId: string) => {
    return `/api/collegia/${slug}/members/${userId}`;
};

/**
 * @summary Leave a collegium (self) or remove a member (collegium stewards)
 */
export const removeMember = async (
    slug: string,
    userId: string,
    options?: Parameters<typeof customFetch>[1],
): Promise<removeMemberResponseSuccess> => {
    return customFetch<removeMemberResponseSuccess>(
        getRemoveMemberUrl(slug, userId),
        {
            ...options,
            method: "DELETE",
        },
    );
};

export const getRemoveMemberMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof removeMember>>,
        TError,
        { slug: string; userId: string },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof removeMember>>,
    TError,
    { slug: string; userId: string },
    TContext
> => {
    const mutationKey = ["removeMember"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof removeMember>>,
        { slug: string; userId: string }
    > = (props) => {
        const { slug, userId } = props ?? {};

        return removeMember(slug, userId, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type RemoveMemberMutationResult = NonNullable<
    Awaited<ReturnType<typeof removeMember>>
>;

export type RemoveMemberMutationError = void;

/**
 * @summary Leave a collegium (self) or remove a member (collegium stewards)
 */
export const useRemoveMember = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof removeMember>>,
            TError,
            { slug: string; userId: string },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof removeMember>>,
    TError,
    { slug: string; userId: string },
    TContext
> => {
    return useMutation(getRemoveMemberMutationOptions(options), queryClient);
};
export type updateMemberRoleResponse200 = {
    data: void;
    status: 200;
};

export type updateMemberRoleResponse400 = {
    data: void;
    status: 400;
};

export type updateMemberRoleResponse403 = {
    data: void;
    status: 403;
};

export type updateMemberRoleResponse404 = {
    data: void;
    status: 404;
};

export type updateMemberRoleResponseSuccess = updateMemberRoleResponse200 & {
    headers: Headers;
};
export type updateMemberRoleResponseError = (
    | updateMemberRoleResponse400
    | updateMemberRoleResponse403
    | updateMemberRoleResponse404
) & {
    headers: Headers;
};

export const getUpdateMemberRoleUrl = (slug: string, userId: string) => {
    return `/api/collegia/${slug}/members/${userId}`;
};

/**
 * @summary Promote a member to admin, or step down as steward (self only)
 */
export const updateMemberRole = async (
    slug: string,
    userId: string,
    updateMemberRequest: UpdateMemberRequest,
    options?: Parameters<typeof customFetch>[1],
): Promise<updateMemberRoleResponseSuccess> => {
    return customFetch<updateMemberRoleResponseSuccess>(
        getUpdateMemberRoleUrl(slug, userId),
        {
            ...options,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(updateMemberRequest),
        },
    );
};

export const getUpdateMemberRoleMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof updateMemberRole>>,
        TError,
        { slug: string; userId: string; data: UpdateMemberRequest },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof updateMemberRole>>,
    TError,
    { slug: string; userId: string; data: UpdateMemberRequest },
    TContext
> => {
    const mutationKey = ["updateMemberRole"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof updateMemberRole>>,
        { slug: string; userId: string; data: UpdateMemberRequest }
    > = (props) => {
        const { slug, userId, data } = props ?? {};

        return updateMemberRole(slug, userId, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type UpdateMemberRoleMutationResult = NonNullable<
    Awaited<ReturnType<typeof updateMemberRole>>
>;
export type UpdateMemberRoleMutationBody = UpdateMemberRequest;
export type UpdateMemberRoleMutationError = void;

/**
 * @summary Promote a member to admin, or step down as steward (self only)
 */
export const useUpdateMemberRole = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof updateMemberRole>>,
            TError,
            { slug: string; userId: string; data: UpdateMemberRequest },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof updateMemberRole>>,
    TError,
    { slug: string; userId: string; data: UpdateMemberRequest },
    TContext
> => {
    return useMutation(
        getUpdateMemberRoleMutationOptions(options),
        queryClient,
    );
};
export type listMyCollegiaResponse200 = {
    data: MyCollegiaResponse;
    status: 200;
};

export type listMyCollegiaResponse401 = {
    data: void;
    status: 401;
};

export type listMyCollegiaResponseSuccess = listMyCollegiaResponse200 & {
    headers: Headers;
};
export type listMyCollegiaResponseError = listMyCollegiaResponse401 & {
    headers: Headers;
};

export const getListMyCollegiaUrl = () => {
    return `/api/user/collegia`;
};

/**
 * @summary List the collegiums the current user belongs to
 */
export const listMyCollegia = async (
    options?: Parameters<typeof customFetch>[1],
): Promise<listMyCollegiaResponseSuccess> => {
    return customFetch<listMyCollegiaResponseSuccess>(getListMyCollegiaUrl(), {
        ...options,
        method: "GET",
    });
};

export const getListMyCollegiaQueryKey = () => {
    return [`/api/user/collegia`] as const;
};

export const getListMyCollegiaQueryOptions = <
    TData = Awaited<ReturnType<typeof listMyCollegia>>,
    TError = void,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof listMyCollegia>>,
            TError,
            TData
        >
    >;
    request?: SecondParameter<typeof customFetch>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getListMyCollegiaQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof listMyCollegia>>
    > = ({ signal }) => listMyCollegia({ signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof listMyCollegia>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListMyCollegiaQueryResult = NonNullable<
    Awaited<ReturnType<typeof listMyCollegia>>
>;
export type ListMyCollegiaQueryError = void;

export function useListMyCollegia<
    TData = Awaited<ReturnType<typeof listMyCollegia>>,
    TError = void,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listMyCollegia>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listMyCollegia>>,
                    TError,
                    Awaited<ReturnType<typeof listMyCollegia>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListMyCollegia<
    TData = Awaited<ReturnType<typeof listMyCollegia>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listMyCollegia>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listMyCollegia>>,
                    TError,
                    Awaited<ReturnType<typeof listMyCollegia>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListMyCollegia<
    TData = Awaited<ReturnType<typeof listMyCollegia>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listMyCollegia>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List the collegiums the current user belongs to
 */

export function useListMyCollegia<
    TData = Awaited<ReturnType<typeof listMyCollegia>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listMyCollegia>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListMyCollegiaQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return withQueryKey(query, queryOptions.queryKey);
}

export const getListMyCollegiaSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof listMyCollegia>>,
    TError = void,
>(options?: {
    query?: Partial<
        UseSuspenseQueryOptions<
            Awaited<ReturnType<typeof listMyCollegia>>,
            TError,
            TData
        >
    >;
    request?: SecondParameter<typeof customFetch>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getListMyCollegiaQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof listMyCollegia>>
    > = ({ signal }) => listMyCollegia({ signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listMyCollegia>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListMyCollegiaSuspenseQueryResult = NonNullable<
    Awaited<ReturnType<typeof listMyCollegia>>
>;
export type ListMyCollegiaSuspenseQueryError = void;

export function useListMyCollegiaSuspense<
    TData = Awaited<ReturnType<typeof listMyCollegia>>,
    TError = void,
>(
    options: {
        query: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listMyCollegia>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListMyCollegiaSuspense<
    TData = Awaited<ReturnType<typeof listMyCollegia>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listMyCollegia>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListMyCollegiaSuspense<
    TData = Awaited<ReturnType<typeof listMyCollegia>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listMyCollegia>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List the collegiums the current user belongs to
 */

export function useListMyCollegiaSuspense<
    TData = Awaited<ReturnType<typeof listMyCollegia>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listMyCollegia>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListMyCollegiaSuspenseQueryOptions(options);

    const query = useSuspenseQuery(
        queryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return withQueryKey(query, queryOptions.queryKey);
}
