/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseInfiniteQueryResult,
    DefinedUseQueryResult,
    InfiniteData,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseInfiniteQueryOptions,
    UseInfiniteQueryResult,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
    UseSuspenseQueryOptions,
    UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
    useInfiniteQuery,
    useMutation,
    useQuery,
    useSuspenseQuery,
} from "@tanstack/react-query";
import { customFetch } from ".././fetcher";
import type {
    ApplyEditorialLabelRequest,
    ArticleDetailResponse,
    ArticleListResponse,
    CreateArticleRequest,
    EditorialLabelListResponse,
    EditorialLabelResponse,
    ListArticleReferencesParams,
    ListPublishedArticlesParams,
    ListUserArticlesParams,
    PassageArticleListResponse,
    PublishedArticleListResponse,
    UpdateArticleRequest,
} from "../model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type applyArticleLabelResponse200 = {
    data: EditorialLabelResponse;
    status: 200;
};

export type applyArticleLabelResponse400 = {
    data: void;
    status: 400;
};

export type applyArticleLabelResponse401 = {
    data: void;
    status: 401;
};

export type applyArticleLabelResponse403 = {
    data: void;
    status: 403;
};

export type applyArticleLabelResponse404 = {
    data: void;
    status: 404;
};

export type applyArticleLabelResponseSuccess = applyArticleLabelResponse200 & {
    headers: Headers;
};
export type applyArticleLabelResponseError = (
    | applyArticleLabelResponse400
    | applyArticleLabelResponse401
    | applyArticleLabelResponse403
    | applyArticleLabelResponse404
) & {
    headers: Headers;
};

export const getApplyArticleLabelUrl = (slug: string) => {
    return `/api/admin/articles/${slug}/labels`;
};

/**
 * @summary Apply an editorial label to a published article. Editor/admin only.
 */
export const applyArticleLabel = async (
    slug: string,
    applyEditorialLabelRequest: ApplyEditorialLabelRequest,
    options?: RequestInit,
): Promise<applyArticleLabelResponseSuccess> => {
    return customFetch<applyArticleLabelResponseSuccess>(
        getApplyArticleLabelUrl(slug),
        {
            ...options,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(applyEditorialLabelRequest),
        },
    );
};

export const getApplyArticleLabelMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof applyArticleLabel>>,
        TError,
        { slug: string; data: ApplyEditorialLabelRequest },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof applyArticleLabel>>,
    TError,
    { slug: string; data: ApplyEditorialLabelRequest },
    TContext
> => {
    const mutationKey = ["applyArticleLabel"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof applyArticleLabel>>,
        { slug: string; data: ApplyEditorialLabelRequest }
    > = (props) => {
        const { slug, data } = props ?? {};

        return applyArticleLabel(slug, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type ApplyArticleLabelMutationResult = NonNullable<
    Awaited<ReturnType<typeof applyArticleLabel>>
>;
export type ApplyArticleLabelMutationBody = ApplyEditorialLabelRequest;
export type ApplyArticleLabelMutationError = void;

/**
 * @summary Apply an editorial label to a published article. Editor/admin only.
 */
export const useApplyArticleLabel = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof applyArticleLabel>>,
            TError,
            { slug: string; data: ApplyEditorialLabelRequest },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof applyArticleLabel>>,
    TError,
    { slug: string; data: ApplyEditorialLabelRequest },
    TContext
> => {
    return useMutation(
        getApplyArticleLabelMutationOptions(options),
        queryClient,
    );
};
export type removeArticleLabelResponse200 = {
    data: void;
    status: 200;
};

export type removeArticleLabelResponse401 = {
    data: void;
    status: 401;
};

export type removeArticleLabelResponse403 = {
    data: void;
    status: 403;
};

export type removeArticleLabelResponseSuccess =
    removeArticleLabelResponse200 & {
        headers: Headers;
    };
export type removeArticleLabelResponseError = (
    | removeArticleLabelResponse401
    | removeArticleLabelResponse403
) & {
    headers: Headers;
};

export const getRemoveArticleLabelUrl = (slug: string, labelSlug: string) => {
    return `/api/admin/articles/${slug}/labels/${labelSlug}`;
};

/**
 * @summary Remove an editorial label from an article. Editor/admin only.
Idempotent — returns 200 even if the label wasn't applied.
 */
export const removeArticleLabel = async (
    slug: string,
    labelSlug: string,
    options?: RequestInit,
): Promise<removeArticleLabelResponseSuccess> => {
    return customFetch<removeArticleLabelResponseSuccess>(
        getRemoveArticleLabelUrl(slug, labelSlug),
        {
            ...options,
            method: "DELETE",
        },
    );
};

export const getRemoveArticleLabelMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof removeArticleLabel>>,
        TError,
        { slug: string; labelSlug: string },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof removeArticleLabel>>,
    TError,
    { slug: string; labelSlug: string },
    TContext
> => {
    const mutationKey = ["removeArticleLabel"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof removeArticleLabel>>,
        { slug: string; labelSlug: string }
    > = (props) => {
        const { slug, labelSlug } = props ?? {};

        return removeArticleLabel(slug, labelSlug, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type RemoveArticleLabelMutationResult = NonNullable<
    Awaited<ReturnType<typeof removeArticleLabel>>
>;

export type RemoveArticleLabelMutationError = void;

/**
 * @summary Remove an editorial label from an article. Editor/admin only.
Idempotent — returns 200 even if the label wasn't applied.
 */
export const useRemoveArticleLabel = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof removeArticleLabel>>,
            TError,
            { slug: string; labelSlug: string },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof removeArticleLabel>>,
    TError,
    { slug: string; labelSlug: string },
    TContext
> => {
    return useMutation(
        getRemoveArticleLabelMutationOptions(options),
        queryClient,
    );
};
export type listPublishedArticlesResponse200 = {
    data: PublishedArticleListResponse;
    status: 200;
};

export type listPublishedArticlesResponseSuccess =
    listPublishedArticlesResponse200 & {
        headers: Headers;
    };

export const getListPublishedArticlesUrl = (
    params?: ListPublishedArticlesParams,
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(
                key,
                value === null ? "null" : String(value),
            );
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/api/articles?${stringifiedParams}`
        : `/api/articles`;
};

/**
 * @summary List published articles
 */
export const listPublishedArticles = async (
    params?: ListPublishedArticlesParams,
    options?: RequestInit,
): Promise<listPublishedArticlesResponseSuccess> => {
    return customFetch<listPublishedArticlesResponseSuccess>(
        getListPublishedArticlesUrl(params),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getListPublishedArticlesQueryKey = (
    params?: ListPublishedArticlesParams,
) => {
    return [`/api/articles`, ...(params ? [params] : [])] as const;
};

export const getListPublishedArticlesQueryOptions = <
    TData = Awaited<ReturnType<typeof listPublishedArticles>>,
    TError = unknown,
>(
    params?: ListPublishedArticlesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listPublishedArticles>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getListPublishedArticlesQueryKey(params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof listPublishedArticles>>
    > = ({ signal }) =>
        listPublishedArticles(params, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof listPublishedArticles>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListPublishedArticlesQueryResult = NonNullable<
    Awaited<ReturnType<typeof listPublishedArticles>>
>;
export type ListPublishedArticlesQueryError = unknown;

export function useListPublishedArticles<
    TData = Awaited<ReturnType<typeof listPublishedArticles>>,
    TError = unknown,
>(
    params: undefined | ListPublishedArticlesParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listPublishedArticles>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listPublishedArticles>>,
                    TError,
                    Awaited<ReturnType<typeof listPublishedArticles>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPublishedArticles<
    TData = Awaited<ReturnType<typeof listPublishedArticles>>,
    TError = unknown,
>(
    params?: ListPublishedArticlesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listPublishedArticles>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listPublishedArticles>>,
                    TError,
                    Awaited<ReturnType<typeof listPublishedArticles>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPublishedArticles<
    TData = Awaited<ReturnType<typeof listPublishedArticles>>,
    TError = unknown,
>(
    params?: ListPublishedArticlesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listPublishedArticles>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List published articles
 */

export function useListPublishedArticles<
    TData = Awaited<ReturnType<typeof listPublishedArticles>>,
    TError = unknown,
>(
    params?: ListPublishedArticlesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listPublishedArticles>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListPublishedArticlesQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}

export const getListPublishedArticlesSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof listPublishedArticles>>,
    TError = unknown,
>(
    params?: ListPublishedArticlesParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listPublishedArticles>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getListPublishedArticlesQueryKey(params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof listPublishedArticles>>
    > = ({ signal }) =>
        listPublishedArticles(params, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listPublishedArticles>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListPublishedArticlesSuspenseQueryResult = NonNullable<
    Awaited<ReturnType<typeof listPublishedArticles>>
>;
export type ListPublishedArticlesSuspenseQueryError = unknown;

export function useListPublishedArticlesSuspense<
    TData = Awaited<ReturnType<typeof listPublishedArticles>>,
    TError = unknown,
>(
    params: undefined | ListPublishedArticlesParams,
    options: {
        query: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listPublishedArticles>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPublishedArticlesSuspense<
    TData = Awaited<ReturnType<typeof listPublishedArticles>>,
    TError = unknown,
>(
    params?: ListPublishedArticlesParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listPublishedArticles>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPublishedArticlesSuspense<
    TData = Awaited<ReturnType<typeof listPublishedArticles>>,
    TError = unknown,
>(
    params?: ListPublishedArticlesParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listPublishedArticles>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List published articles
 */

export function useListPublishedArticlesSuspense<
    TData = Awaited<ReturnType<typeof listPublishedArticles>>,
    TError = unknown,
>(
    params?: ListPublishedArticlesParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listPublishedArticles>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListPublishedArticlesSuspenseQueryOptions(
        params,
        options,
    );

    const query = useSuspenseQuery(
        queryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return { ...query, queryKey: queryOptions.queryKey };
}

export type createArticleResponse200 = {
    data: ArticleDetailResponse;
    status: 200;
};

export type createArticleResponse400 = {
    data: void;
    status: 400;
};

export type createArticleResponse401 = {
    data: void;
    status: 401;
};

export type createArticleResponse403 = {
    data: void;
    status: 403;
};

export type createArticleResponseSuccess = createArticleResponse200 & {
    headers: Headers;
};
export type createArticleResponseError = (
    | createArticleResponse400
    | createArticleResponse401
    | createArticleResponse403
) & {
    headers: Headers;
};

export const getCreateArticleUrl = () => {
    return `/api/articles`;
};

/**
 * @summary Create a new article
 */
export const createArticle = async (
    createArticleRequest: CreateArticleRequest,
    options?: RequestInit,
): Promise<createArticleResponseSuccess> => {
    return customFetch<createArticleResponseSuccess>(getCreateArticleUrl(), {
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(createArticleRequest),
    });
};

export const getCreateArticleMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof createArticle>>,
        TError,
        { data: CreateArticleRequest },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof createArticle>>,
    TError,
    { data: CreateArticleRequest },
    TContext
> => {
    const mutationKey = ["createArticle"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof createArticle>>,
        { data: CreateArticleRequest }
    > = (props) => {
        const { data } = props ?? {};

        return createArticle(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type CreateArticleMutationResult = NonNullable<
    Awaited<ReturnType<typeof createArticle>>
>;
export type CreateArticleMutationBody = CreateArticleRequest;
export type CreateArticleMutationError = void;

/**
 * @summary Create a new article
 */
export const useCreateArticle = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof createArticle>>,
            TError,
            { data: CreateArticleRequest },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof createArticle>>,
    TError,
    { data: CreateArticleRequest },
    TContext
> => {
    return useMutation(getCreateArticleMutationOptions(options), queryClient);
};
export type getArticleByIdResponse200 = {
    data: ArticleDetailResponse;
    status: 200;
};

export type getArticleByIdResponse404 = {
    data: void;
    status: 404;
};

export type getArticleByIdResponseSuccess = getArticleByIdResponse200 & {
    headers: Headers;
};
export type getArticleByIdResponseError = getArticleByIdResponse404 & {
    headers: Headers;
};

export const getGetArticleByIdUrl = (id: string) => {
    return `/api/articles/by-id/${id}`;
};

/**
 * @summary Get a published/archived article by UUID (stable URL)
 */
export const getArticleById = async (
    id: string,
    options?: RequestInit,
): Promise<getArticleByIdResponseSuccess> => {
    return customFetch<getArticleByIdResponseSuccess>(
        getGetArticleByIdUrl(id),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getGetArticleByIdQueryKey = (id: string) => {
    return [`/api/articles/by-id/${id}`] as const;
};

export const getGetArticleByIdQueryOptions = <
    TData = Awaited<ReturnType<typeof getArticleById>>,
    TError = void,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getArticleById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetArticleByIdQueryKey(id);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getArticleById>>
    > = ({ signal }) => getArticleById(id, { signal, ...requestOptions });

    return {
        queryKey,
        queryFn,
        enabled: id !== null && id !== undefined,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getArticleById>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetArticleByIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof getArticleById>>
>;
export type GetArticleByIdQueryError = void;

export function useGetArticleById<
    TData = Awaited<ReturnType<typeof getArticleById>>,
    TError = void,
>(
    id: string,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getArticleById>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getArticleById>>,
                    TError,
                    Awaited<ReturnType<typeof getArticleById>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetArticleById<
    TData = Awaited<ReturnType<typeof getArticleById>>,
    TError = void,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getArticleById>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getArticleById>>,
                    TError,
                    Awaited<ReturnType<typeof getArticleById>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetArticleById<
    TData = Awaited<ReturnType<typeof getArticleById>>,
    TError = void,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getArticleById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a published/archived article by UUID (stable URL)
 */

export function useGetArticleById<
    TData = Awaited<ReturnType<typeof getArticleById>>,
    TError = void,
>(
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getArticleById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetArticleByIdQueryOptions(id, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetArticleByIdSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof getArticleById>>,
    TError = void,
>(
    id: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof getArticleById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetArticleByIdQueryKey(id);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getArticleById>>
    > = ({ signal }) => getArticleById(id, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getArticleById>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetArticleByIdSuspenseQueryResult = NonNullable<
    Awaited<ReturnType<typeof getArticleById>>
>;
export type GetArticleByIdSuspenseQueryError = void;

export function useGetArticleByIdSuspense<
    TData = Awaited<ReturnType<typeof getArticleById>>,
    TError = void,
>(
    id: string,
    options: {
        query: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof getArticleById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetArticleByIdSuspense<
    TData = Awaited<ReturnType<typeof getArticleById>>,
    TError = void,
>(
    id: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof getArticleById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetArticleByIdSuspense<
    TData = Awaited<ReturnType<typeof getArticleById>>,
    TError = void,
>(
    id: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof getArticleById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a published/archived article by UUID (stable URL)
 */

export function useGetArticleByIdSuspense<
    TData = Awaited<ReturnType<typeof getArticleById>>,
    TError = void,
>(
    id: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof getArticleById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetArticleByIdSuspenseQueryOptions(id, options);

    const query = useSuspenseQuery(
        queryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return { ...query, queryKey: queryOptions.queryKey };
}

export type getPublishedArticleResponse200 = {
    data: ArticleDetailResponse;
    status: 200;
};

export type getPublishedArticleResponse404 = {
    data: void;
    status: 404;
};

export type getPublishedArticleResponseSuccess =
    getPublishedArticleResponse200 & {
        headers: Headers;
    };
export type getPublishedArticleResponseError =
    getPublishedArticleResponse404 & {
        headers: Headers;
    };

export const getGetPublishedArticleUrl = (slug: string) => {
    return `/api/articles/${slug}`;
};

/**
 * @summary Get a published article by slug
 */
export const getPublishedArticle = async (
    slug: string,
    options?: RequestInit,
): Promise<getPublishedArticleResponseSuccess> => {
    return customFetch<getPublishedArticleResponseSuccess>(
        getGetPublishedArticleUrl(slug),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getGetPublishedArticleQueryKey = (slug: string) => {
    return [`/api/articles/${slug}`] as const;
};

export const getGetPublishedArticleQueryOptions = <
    TData = Awaited<ReturnType<typeof getPublishedArticle>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getPublishedArticle>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getGetPublishedArticleQueryKey(slug);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getPublishedArticle>>
    > = ({ signal }) =>
        getPublishedArticle(slug, { signal, ...requestOptions });

    return {
        queryKey,
        queryFn,
        enabled: slug !== null && slug !== undefined,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getPublishedArticle>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPublishedArticleQueryResult = NonNullable<
    Awaited<ReturnType<typeof getPublishedArticle>>
>;
export type GetPublishedArticleQueryError = void;

export function useGetPublishedArticle<
    TData = Awaited<ReturnType<typeof getPublishedArticle>>,
    TError = void,
>(
    slug: string,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getPublishedArticle>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getPublishedArticle>>,
                    TError,
                    Awaited<ReturnType<typeof getPublishedArticle>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPublishedArticle<
    TData = Awaited<ReturnType<typeof getPublishedArticle>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getPublishedArticle>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getPublishedArticle>>,
                    TError,
                    Awaited<ReturnType<typeof getPublishedArticle>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPublishedArticle<
    TData = Awaited<ReturnType<typeof getPublishedArticle>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getPublishedArticle>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a published article by slug
 */

export function useGetPublishedArticle<
    TData = Awaited<ReturnType<typeof getPublishedArticle>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getPublishedArticle>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetPublishedArticleQueryOptions(slug, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetPublishedArticleSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof getPublishedArticle>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof getPublishedArticle>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getGetPublishedArticleQueryKey(slug);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getPublishedArticle>>
    > = ({ signal }) =>
        getPublishedArticle(slug, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getPublishedArticle>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPublishedArticleSuspenseQueryResult = NonNullable<
    Awaited<ReturnType<typeof getPublishedArticle>>
>;
export type GetPublishedArticleSuspenseQueryError = void;

export function useGetPublishedArticleSuspense<
    TData = Awaited<ReturnType<typeof getPublishedArticle>>,
    TError = void,
>(
    slug: string,
    options: {
        query: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof getPublishedArticle>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPublishedArticleSuspense<
    TData = Awaited<ReturnType<typeof getPublishedArticle>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof getPublishedArticle>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPublishedArticleSuspense<
    TData = Awaited<ReturnType<typeof getPublishedArticle>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof getPublishedArticle>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a published article by slug
 */

export function useGetPublishedArticleSuspense<
    TData = Awaited<ReturnType<typeof getPublishedArticle>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof getPublishedArticle>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetPublishedArticleSuspenseQueryOptions(
        slug,
        options,
    );

    const query = useSuspenseQuery(
        queryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return { ...query, queryKey: queryOptions.queryKey };
}

export type listArticleReferencesResponse200 = {
    data: PassageArticleListResponse;
    status: 200;
};

export type listArticleReferencesResponse404 = {
    data: void;
    status: 404;
};

export type listArticleReferencesResponseSuccess =
    listArticleReferencesResponse200 & {
        headers: Headers;
    };
export type listArticleReferencesResponseError =
    listArticleReferencesResponse404 & {
        headers: Headers;
    };

export const getListArticleReferencesUrl = (
    slug: string,
    params: ListArticleReferencesParams,
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(
                key,
                value === null ? "null" : String(value),
            );
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/api/books/${slug}/article-references?${stringifiedParams}`
        : `/api/books/${slug}/article-references`;
};

/**
 * @summary List published articles quoting a sentence range (public)
 */
export const listArticleReferences = async (
    slug: string,
    params: ListArticleReferencesParams,
    options?: RequestInit,
): Promise<listArticleReferencesResponseSuccess> => {
    return customFetch<listArticleReferencesResponseSuccess>(
        getListArticleReferencesUrl(slug, params),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getListArticleReferencesInfiniteQueryKey = (
    slug: string,
    params?: ListArticleReferencesParams,
) => {
    return [
        "infinite",
        `/api/books/${slug}/article-references`,
        ...(params ? [params] : []),
    ] as const;
};

export const getListArticleReferencesQueryKey = (
    slug: string,
    params?: ListArticleReferencesParams,
) => {
    return [
        `/api/books/${slug}/article-references`,
        ...(params ? [params] : []),
    ] as const;
};

export const getListArticleReferencesInfiniteQueryOptions = <
    TData = InfiniteData<
        Awaited<ReturnType<typeof listArticleReferences>>,
        ListArticleReferencesParams["offset"]
    >,
    TError = void,
>(
    slug: string,
    params: ListArticleReferencesParams,
    options?: {
        query?: Partial<
            UseInfiniteQueryOptions<
                Awaited<ReturnType<typeof listArticleReferences>>,
                TError,
                TData,
                QueryKey,
                ListArticleReferencesParams["offset"]
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ??
        getListArticleReferencesInfiniteQueryKey(slug, params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof listArticleReferences>>,
        QueryKey,
        ListArticleReferencesParams["offset"]
    > = ({ signal, pageParam }) =>
        listArticleReferences(
            slug,
            { ...params, offset: pageParam ?? params?.["offset"] },
            { signal, ...requestOptions },
        );

    return {
        queryKey,
        queryFn,
        enabled: slug !== null && slug !== undefined,
        ...queryOptions,
    } as UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof listArticleReferences>>,
        TError,
        TData,
        QueryKey,
        ListArticleReferencesParams["offset"]
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListArticleReferencesInfiniteQueryResult = NonNullable<
    Awaited<ReturnType<typeof listArticleReferences>>
>;
export type ListArticleReferencesInfiniteQueryError = void;

export function useListArticleReferencesInfinite<
    TData = InfiniteData<
        Awaited<ReturnType<typeof listArticleReferences>>,
        ListArticleReferencesParams["offset"]
    >,
    TError = void,
>(
    slug: string,
    params: ListArticleReferencesParams,
    options: {
        query: Partial<
            UseInfiniteQueryOptions<
                Awaited<ReturnType<typeof listArticleReferences>>,
                TError,
                TData,
                QueryKey,
                ListArticleReferencesParams["offset"]
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listArticleReferences>>,
                    TError,
                    Awaited<ReturnType<typeof listArticleReferences>>,
                    QueryKey
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListArticleReferencesInfinite<
    TData = InfiniteData<
        Awaited<ReturnType<typeof listArticleReferences>>,
        ListArticleReferencesParams["offset"]
    >,
    TError = void,
>(
    slug: string,
    params: ListArticleReferencesParams,
    options?: {
        query?: Partial<
            UseInfiniteQueryOptions<
                Awaited<ReturnType<typeof listArticleReferences>>,
                TError,
                TData,
                QueryKey,
                ListArticleReferencesParams["offset"]
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listArticleReferences>>,
                    TError,
                    Awaited<ReturnType<typeof listArticleReferences>>,
                    QueryKey
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListArticleReferencesInfinite<
    TData = InfiniteData<
        Awaited<ReturnType<typeof listArticleReferences>>,
        ListArticleReferencesParams["offset"]
    >,
    TError = void,
>(
    slug: string,
    params: ListArticleReferencesParams,
    options?: {
        query?: Partial<
            UseInfiniteQueryOptions<
                Awaited<ReturnType<typeof listArticleReferences>>,
                TError,
                TData,
                QueryKey,
                ListArticleReferencesParams["offset"]
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List published articles quoting a sentence range (public)
 */

export function useListArticleReferencesInfinite<
    TData = InfiniteData<
        Awaited<ReturnType<typeof listArticleReferences>>,
        ListArticleReferencesParams["offset"]
    >,
    TError = void,
>(
    slug: string,
    params: ListArticleReferencesParams,
    options?: {
        query?: Partial<
            UseInfiniteQueryOptions<
                Awaited<ReturnType<typeof listArticleReferences>>,
                TError,
                TData,
                QueryKey,
                ListArticleReferencesParams["offset"]
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListArticleReferencesInfiniteQueryOptions(
        slug,
        params,
        options,
    );

    const query = useInfiniteQuery(
        queryOptions,
        queryClient,
    ) as UseInfiniteQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return { ...query, queryKey: queryOptions.queryKey };
}

export const getListArticleReferencesQueryOptions = <
    TData = Awaited<ReturnType<typeof listArticleReferences>>,
    TError = void,
>(
    slug: string,
    params: ListArticleReferencesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listArticleReferences>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ??
        getListArticleReferencesQueryKey(slug, params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof listArticleReferences>>
    > = ({ signal }) =>
        listArticleReferences(slug, params, { signal, ...requestOptions });

    return {
        queryKey,
        queryFn,
        enabled: slug !== null && slug !== undefined,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof listArticleReferences>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListArticleReferencesQueryResult = NonNullable<
    Awaited<ReturnType<typeof listArticleReferences>>
>;
export type ListArticleReferencesQueryError = void;

export function useListArticleReferences<
    TData = Awaited<ReturnType<typeof listArticleReferences>>,
    TError = void,
>(
    slug: string,
    params: ListArticleReferencesParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listArticleReferences>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listArticleReferences>>,
                    TError,
                    Awaited<ReturnType<typeof listArticleReferences>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListArticleReferences<
    TData = Awaited<ReturnType<typeof listArticleReferences>>,
    TError = void,
>(
    slug: string,
    params: ListArticleReferencesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listArticleReferences>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listArticleReferences>>,
                    TError,
                    Awaited<ReturnType<typeof listArticleReferences>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListArticleReferences<
    TData = Awaited<ReturnType<typeof listArticleReferences>>,
    TError = void,
>(
    slug: string,
    params: ListArticleReferencesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listArticleReferences>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List published articles quoting a sentence range (public)
 */

export function useListArticleReferences<
    TData = Awaited<ReturnType<typeof listArticleReferences>>,
    TError = void,
>(
    slug: string,
    params: ListArticleReferencesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listArticleReferences>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListArticleReferencesQueryOptions(
        slug,
        params,
        options,
    );

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}

export const getListArticleReferencesSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof listArticleReferences>>,
    TError = void,
>(
    slug: string,
    params: ListArticleReferencesParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listArticleReferences>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ??
        getListArticleReferencesQueryKey(slug, params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof listArticleReferences>>
    > = ({ signal }) =>
        listArticleReferences(slug, params, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listArticleReferences>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListArticleReferencesSuspenseQueryResult = NonNullable<
    Awaited<ReturnType<typeof listArticleReferences>>
>;
export type ListArticleReferencesSuspenseQueryError = void;

export function useListArticleReferencesSuspense<
    TData = Awaited<ReturnType<typeof listArticleReferences>>,
    TError = void,
>(
    slug: string,
    params: ListArticleReferencesParams,
    options: {
        query: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listArticleReferences>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListArticleReferencesSuspense<
    TData = Awaited<ReturnType<typeof listArticleReferences>>,
    TError = void,
>(
    slug: string,
    params: ListArticleReferencesParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listArticleReferences>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListArticleReferencesSuspense<
    TData = Awaited<ReturnType<typeof listArticleReferences>>,
    TError = void,
>(
    slug: string,
    params: ListArticleReferencesParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listArticleReferences>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List published articles quoting a sentence range (public)
 */

export function useListArticleReferencesSuspense<
    TData = Awaited<ReturnType<typeof listArticleReferences>>,
    TError = void,
>(
    slug: string,
    params: ListArticleReferencesParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listArticleReferences>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListArticleReferencesSuspenseQueryOptions(
        slug,
        params,
        options,
    );

    const query = useSuspenseQuery(
        queryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return { ...query, queryKey: queryOptions.queryKey };
}

export type listEditorialLabelsResponse200 = {
    data: EditorialLabelListResponse;
    status: 200;
};

export type listEditorialLabelsResponseSuccess =
    listEditorialLabelsResponse200 & {
        headers: Headers;
    };

export const getListEditorialLabelsUrl = () => {
    return `/api/editorial-labels`;
};

/**
 * @summary List all editorial labels. Public — readers see chip metadata so the
frontend can render names/slugs without a separate lookup, and editors
use the same endpoint to populate the manage-labels modal.
 */
export const listEditorialLabels = async (
    options?: RequestInit,
): Promise<listEditorialLabelsResponseSuccess> => {
    return customFetch<listEditorialLabelsResponseSuccess>(
        getListEditorialLabelsUrl(),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getListEditorialLabelsQueryKey = () => {
    return [`/api/editorial-labels`] as const;
};

export const getListEditorialLabelsQueryOptions = <
    TData = Awaited<ReturnType<typeof listEditorialLabels>>,
    TError = unknown,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof listEditorialLabels>>,
            TError,
            TData
        >
    >;
    request?: SecondParameter<typeof customFetch>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getListEditorialLabelsQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof listEditorialLabels>>
    > = ({ signal }) => listEditorialLabels({ signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof listEditorialLabels>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListEditorialLabelsQueryResult = NonNullable<
    Awaited<ReturnType<typeof listEditorialLabels>>
>;
export type ListEditorialLabelsQueryError = unknown;

export function useListEditorialLabels<
    TData = Awaited<ReturnType<typeof listEditorialLabels>>,
    TError = unknown,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listEditorialLabels>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listEditorialLabels>>,
                    TError,
                    Awaited<ReturnType<typeof listEditorialLabels>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListEditorialLabels<
    TData = Awaited<ReturnType<typeof listEditorialLabels>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listEditorialLabels>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listEditorialLabels>>,
                    TError,
                    Awaited<ReturnType<typeof listEditorialLabels>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListEditorialLabels<
    TData = Awaited<ReturnType<typeof listEditorialLabels>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listEditorialLabels>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List all editorial labels. Public — readers see chip metadata so the
frontend can render names/slugs without a separate lookup, and editors
use the same endpoint to populate the manage-labels modal.
 */

export function useListEditorialLabels<
    TData = Awaited<ReturnType<typeof listEditorialLabels>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listEditorialLabels>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListEditorialLabelsQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}

export const getListEditorialLabelsSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof listEditorialLabels>>,
    TError = unknown,
>(options?: {
    query?: Partial<
        UseSuspenseQueryOptions<
            Awaited<ReturnType<typeof listEditorialLabels>>,
            TError,
            TData
        >
    >;
    request?: SecondParameter<typeof customFetch>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getListEditorialLabelsQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof listEditorialLabels>>
    > = ({ signal }) => listEditorialLabels({ signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listEditorialLabels>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListEditorialLabelsSuspenseQueryResult = NonNullable<
    Awaited<ReturnType<typeof listEditorialLabels>>
>;
export type ListEditorialLabelsSuspenseQueryError = unknown;

export function useListEditorialLabelsSuspense<
    TData = Awaited<ReturnType<typeof listEditorialLabels>>,
    TError = unknown,
>(
    options: {
        query: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listEditorialLabels>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListEditorialLabelsSuspense<
    TData = Awaited<ReturnType<typeof listEditorialLabels>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listEditorialLabels>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListEditorialLabelsSuspense<
    TData = Awaited<ReturnType<typeof listEditorialLabels>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listEditorialLabels>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List all editorial labels. Public — readers see chip metadata so the
frontend can render names/slugs without a separate lookup, and editors
use the same endpoint to populate the manage-labels modal.
 */

export function useListEditorialLabelsSuspense<
    TData = Awaited<ReturnType<typeof listEditorialLabels>>,
    TError = unknown,
>(
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listEditorialLabels>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListEditorialLabelsSuspenseQueryOptions(options);

    const query = useSuspenseQuery(
        queryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return { ...query, queryKey: queryOptions.queryKey };
}

export type listUserArticlesResponse200 = {
    data: ArticleListResponse;
    status: 200;
};

export type listUserArticlesResponse401 = {
    data: void;
    status: 401;
};

export type listUserArticlesResponseSuccess = listUserArticlesResponse200 & {
    headers: Headers;
};
export type listUserArticlesResponseError = listUserArticlesResponse401 & {
    headers: Headers;
};

export const getListUserArticlesUrl = (params?: ListUserArticlesParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(
                key,
                value === null ? "null" : String(value),
            );
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/api/user/articles?${stringifiedParams}`
        : `/api/user/articles`;
};

/**
 * @summary List current user's articles
 */
export const listUserArticles = async (
    params?: ListUserArticlesParams,
    options?: RequestInit,
): Promise<listUserArticlesResponseSuccess> => {
    return customFetch<listUserArticlesResponseSuccess>(
        getListUserArticlesUrl(params),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getListUserArticlesQueryKey = (
    params?: ListUserArticlesParams,
) => {
    return [`/api/user/articles`, ...(params ? [params] : [])] as const;
};

export const getListUserArticlesQueryOptions = <
    TData = Awaited<ReturnType<typeof listUserArticles>>,
    TError = void,
>(
    params?: ListUserArticlesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listUserArticles>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getListUserArticlesQueryKey(params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof listUserArticles>>
    > = ({ signal }) => listUserArticles(params, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof listUserArticles>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListUserArticlesQueryResult = NonNullable<
    Awaited<ReturnType<typeof listUserArticles>>
>;
export type ListUserArticlesQueryError = void;

export function useListUserArticles<
    TData = Awaited<ReturnType<typeof listUserArticles>>,
    TError = void,
>(
    params: undefined | ListUserArticlesParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listUserArticles>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listUserArticles>>,
                    TError,
                    Awaited<ReturnType<typeof listUserArticles>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListUserArticles<
    TData = Awaited<ReturnType<typeof listUserArticles>>,
    TError = void,
>(
    params?: ListUserArticlesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listUserArticles>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listUserArticles>>,
                    TError,
                    Awaited<ReturnType<typeof listUserArticles>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListUserArticles<
    TData = Awaited<ReturnType<typeof listUserArticles>>,
    TError = void,
>(
    params?: ListUserArticlesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listUserArticles>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List current user's articles
 */

export function useListUserArticles<
    TData = Awaited<ReturnType<typeof listUserArticles>>,
    TError = void,
>(
    params?: ListUserArticlesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listUserArticles>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListUserArticlesQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}

export const getListUserArticlesSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof listUserArticles>>,
    TError = void,
>(
    params?: ListUserArticlesParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listUserArticles>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getListUserArticlesQueryKey(params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof listUserArticles>>
    > = ({ signal }) => listUserArticles(params, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listUserArticles>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListUserArticlesSuspenseQueryResult = NonNullable<
    Awaited<ReturnType<typeof listUserArticles>>
>;
export type ListUserArticlesSuspenseQueryError = void;

export function useListUserArticlesSuspense<
    TData = Awaited<ReturnType<typeof listUserArticles>>,
    TError = void,
>(
    params: undefined | ListUserArticlesParams,
    options: {
        query: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listUserArticles>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListUserArticlesSuspense<
    TData = Awaited<ReturnType<typeof listUserArticles>>,
    TError = void,
>(
    params?: ListUserArticlesParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listUserArticles>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListUserArticlesSuspense<
    TData = Awaited<ReturnType<typeof listUserArticles>>,
    TError = void,
>(
    params?: ListUserArticlesParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listUserArticles>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List current user's articles
 */

export function useListUserArticlesSuspense<
    TData = Awaited<ReturnType<typeof listUserArticles>>,
    TError = void,
>(
    params?: ListUserArticlesParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listUserArticles>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListUserArticlesSuspenseQueryOptions(
        params,
        options,
    );

    const query = useSuspenseQuery(
        queryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return { ...query, queryKey: queryOptions.queryKey };
}

export type getUserArticleResponse200 = {
    data: ArticleDetailResponse;
    status: 200;
};

export type getUserArticleResponse401 = {
    data: void;
    status: 401;
};

export type getUserArticleResponse404 = {
    data: void;
    status: 404;
};

export type getUserArticleResponseSuccess = getUserArticleResponse200 & {
    headers: Headers;
};
export type getUserArticleResponseError = (
    | getUserArticleResponse401
    | getUserArticleResponse404
) & {
    headers: Headers;
};

export const getGetUserArticleUrl = (slug: string) => {
    return `/api/user/articles/${slug}`;
};

/**
 * @summary Get a specific article for editing (owner only)
 */
export const getUserArticle = async (
    slug: string,
    options?: RequestInit,
): Promise<getUserArticleResponseSuccess> => {
    return customFetch<getUserArticleResponseSuccess>(
        getGetUserArticleUrl(slug),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getGetUserArticleQueryKey = (slug: string) => {
    return [`/api/user/articles/${slug}`] as const;
};

export const getGetUserArticleQueryOptions = <
    TData = Awaited<ReturnType<typeof getUserArticle>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getUserArticle>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetUserArticleQueryKey(slug);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getUserArticle>>
    > = ({ signal }) => getUserArticle(slug, { signal, ...requestOptions });

    return {
        queryKey,
        queryFn,
        enabled: slug !== null && slug !== undefined,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getUserArticle>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserArticleQueryResult = NonNullable<
    Awaited<ReturnType<typeof getUserArticle>>
>;
export type GetUserArticleQueryError = void;

export function useGetUserArticle<
    TData = Awaited<ReturnType<typeof getUserArticle>>,
    TError = void,
>(
    slug: string,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getUserArticle>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getUserArticle>>,
                    TError,
                    Awaited<ReturnType<typeof getUserArticle>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserArticle<
    TData = Awaited<ReturnType<typeof getUserArticle>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getUserArticle>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getUserArticle>>,
                    TError,
                    Awaited<ReturnType<typeof getUserArticle>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserArticle<
    TData = Awaited<ReturnType<typeof getUserArticle>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getUserArticle>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a specific article for editing (owner only)
 */

export function useGetUserArticle<
    TData = Awaited<ReturnType<typeof getUserArticle>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getUserArticle>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetUserArticleQueryOptions(slug, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetUserArticleSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof getUserArticle>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof getUserArticle>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetUserArticleQueryKey(slug);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getUserArticle>>
    > = ({ signal }) => getUserArticle(slug, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUserArticle>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserArticleSuspenseQueryResult = NonNullable<
    Awaited<ReturnType<typeof getUserArticle>>
>;
export type GetUserArticleSuspenseQueryError = void;

export function useGetUserArticleSuspense<
    TData = Awaited<ReturnType<typeof getUserArticle>>,
    TError = void,
>(
    slug: string,
    options: {
        query: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof getUserArticle>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserArticleSuspense<
    TData = Awaited<ReturnType<typeof getUserArticle>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof getUserArticle>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserArticleSuspense<
    TData = Awaited<ReturnType<typeof getUserArticle>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof getUserArticle>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a specific article for editing (owner only)
 */

export function useGetUserArticleSuspense<
    TData = Awaited<ReturnType<typeof getUserArticle>>,
    TError = void,
>(
    slug: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof getUserArticle>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetUserArticleSuspenseQueryOptions(slug, options);

    const query = useSuspenseQuery(
        queryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return { ...query, queryKey: queryOptions.queryKey };
}

export type updateArticleResponse200 = {
    data: ArticleDetailResponse;
    status: 200;
};

export type updateArticleResponse400 = {
    data: void;
    status: 400;
};

export type updateArticleResponse401 = {
    data: void;
    status: 401;
};

export type updateArticleResponse404 = {
    data: void;
    status: 404;
};

export type updateArticleResponseSuccess = updateArticleResponse200 & {
    headers: Headers;
};
export type updateArticleResponseError = (
    | updateArticleResponse400
    | updateArticleResponse401
    | updateArticleResponse404
) & {
    headers: Headers;
};

export const getUpdateArticleUrl = (slug: string) => {
    return `/api/user/articles/${slug}`;
};

/**
 * @summary Update an article (owner only)
 */
export const updateArticle = async (
    slug: string,
    updateArticleRequest: UpdateArticleRequest,
    options?: RequestInit,
): Promise<updateArticleResponseSuccess> => {
    return customFetch<updateArticleResponseSuccess>(
        getUpdateArticleUrl(slug),
        {
            ...options,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(updateArticleRequest),
        },
    );
};

export const getUpdateArticleMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof updateArticle>>,
        TError,
        { slug: string; data: UpdateArticleRequest },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof updateArticle>>,
    TError,
    { slug: string; data: UpdateArticleRequest },
    TContext
> => {
    const mutationKey = ["updateArticle"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof updateArticle>>,
        { slug: string; data: UpdateArticleRequest }
    > = (props) => {
        const { slug, data } = props ?? {};

        return updateArticle(slug, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type UpdateArticleMutationResult = NonNullable<
    Awaited<ReturnType<typeof updateArticle>>
>;
export type UpdateArticleMutationBody = UpdateArticleRequest;
export type UpdateArticleMutationError = void;

/**
 * @summary Update an article (owner only)
 */
export const useUpdateArticle = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof updateArticle>>,
            TError,
            { slug: string; data: UpdateArticleRequest },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof updateArticle>>,
    TError,
    { slug: string; data: UpdateArticleRequest },
    TContext
> => {
    return useMutation(getUpdateArticleMutationOptions(options), queryClient);
};
export type archiveArticleResponse200 = {
    data: void;
    status: 200;
};

export type archiveArticleResponse401 = {
    data: void;
    status: 401;
};

export type archiveArticleResponse404 = {
    data: void;
    status: 404;
};

export type archiveArticleResponseSuccess = archiveArticleResponse200 & {
    headers: Headers;
};
export type archiveArticleResponseError = (
    | archiveArticleResponse401
    | archiveArticleResponse404
) & {
    headers: Headers;
};

export const getArchiveArticleUrl = (slug: string) => {
    return `/api/user/articles/${slug}/archive`;
};

/**
 * @summary Archive an article (one-way from published)
 */
export const archiveArticle = async (
    slug: string,
    options?: RequestInit,
): Promise<archiveArticleResponseSuccess> => {
    return customFetch<archiveArticleResponseSuccess>(
        getArchiveArticleUrl(slug),
        {
            ...options,
            method: "POST",
        },
    );
};

export const getArchiveArticleMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof archiveArticle>>,
        TError,
        { slug: string },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof archiveArticle>>,
    TError,
    { slug: string },
    TContext
> => {
    const mutationKey = ["archiveArticle"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof archiveArticle>>,
        { slug: string }
    > = (props) => {
        const { slug } = props ?? {};

        return archiveArticle(slug, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type ArchiveArticleMutationResult = NonNullable<
    Awaited<ReturnType<typeof archiveArticle>>
>;

export type ArchiveArticleMutationError = void;

/**
 * @summary Archive an article (one-way from published)
 */
export const useArchiveArticle = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof archiveArticle>>,
            TError,
            { slug: string },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof archiveArticle>>,
    TError,
    { slug: string },
    TContext
> => {
    return useMutation(getArchiveArticleMutationOptions(options), queryClient);
};
export type publishArticleResponse200 = {
    data: void;
    status: 200;
};

export type publishArticleResponse400 = {
    data: void;
    status: 400;
};

export type publishArticleResponse401 = {
    data: void;
    status: 401;
};

export type publishArticleResponse404 = {
    data: void;
    status: 404;
};

export type publishArticleResponseSuccess = publishArticleResponse200 & {
    headers: Headers;
};
export type publishArticleResponseError = (
    | publishArticleResponse400
    | publishArticleResponse401
    | publishArticleResponse404
) & {
    headers: Headers;
};

export const getPublishArticleUrl = (slug: string) => {
    return `/api/user/articles/${slug}/publish`;
};

/**
 * @summary Publish an article
 */
export const publishArticle = async (
    slug: string,
    options?: RequestInit,
): Promise<publishArticleResponseSuccess> => {
    return customFetch<publishArticleResponseSuccess>(
        getPublishArticleUrl(slug),
        {
            ...options,
            method: "POST",
        },
    );
};

export const getPublishArticleMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof publishArticle>>,
        TError,
        { slug: string },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof publishArticle>>,
    TError,
    { slug: string },
    TContext
> => {
    const mutationKey = ["publishArticle"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof publishArticle>>,
        { slug: string }
    > = (props) => {
        const { slug } = props ?? {};

        return publishArticle(slug, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PublishArticleMutationResult = NonNullable<
    Awaited<ReturnType<typeof publishArticle>>
>;

export type PublishArticleMutationError = void;

/**
 * @summary Publish an article
 */
export const usePublishArticle = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof publishArticle>>,
            TError,
            { slug: string },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof publishArticle>>,
    TError,
    { slug: string },
    TContext
> => {
    return useMutation(getPublishArticleMutationOptions(options), queryClient);
};
