/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
    UseSuspenseQueryOptions,
    UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import { customFetch } from ".././fetcher";
import type {
    CreateNoteRequest,
    CreateQuotationRequest,
    CreateQuotationResponse,
    ListAllNotesParams,
    ListAllQuotationsParams,
    ListQuotationsParams,
    NoteListResponse,
    NoteResponse,
    NoteWithContextListResponse,
    QuotationListResponse,
    UnifiedQuotationListResponse,
    UpdateNoteRequest,
} from "../model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type listQuotationsResponse200 = {
    data: QuotationListResponse;
    status: 200;
};

export type listQuotationsResponse400 = {
    data: void;
    status: 400;
};

export type listQuotationsResponse401 = {
    data: void;
    status: 401;
};

export type listQuotationsResponse404 = {
    data: void;
    status: 404;
};

export type listQuotationsResponseSuccess = listQuotationsResponse200 & {
    headers: Headers;
};
export type listQuotationsResponseError = (
    | listQuotationsResponse400
    | listQuotationsResponse401
    | listQuotationsResponse404
) & {
    headers: Headers;
};

export const getListQuotationsUrl = (
    slug: string,
    params: ListQuotationsParams,
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(
                key,
                value === null ? "null" : String(value),
            );
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/api/books/${slug}/quotations?${stringifiedParams}`
        : `/api/books/${slug}/quotations`;
};

/**
 * @summary List quotations for a node (authenticated user only)
 */
export const listQuotations = async (
    slug: string,
    params: ListQuotationsParams,
    options?: RequestInit,
): Promise<listQuotationsResponseSuccess> => {
    return customFetch<listQuotationsResponseSuccess>(
        getListQuotationsUrl(slug, params),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getListQuotationsQueryKey = (
    slug: string,
    params?: ListQuotationsParams,
) => {
    return [
        `/api/books/${slug}/quotations`,
        ...(params ? [params] : []),
    ] as const;
};

export const getListQuotationsQueryOptions = <
    TData = Awaited<ReturnType<typeof listQuotations>>,
    TError = void,
>(
    slug: string,
    params: ListQuotationsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listQuotations>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getListQuotationsQueryKey(slug, params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof listQuotations>>
    > = ({ signal }) =>
        listQuotations(slug, params, { signal, ...requestOptions });

    return {
        queryKey,
        queryFn,
        enabled: slug !== null && slug !== undefined,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof listQuotations>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListQuotationsQueryResult = NonNullable<
    Awaited<ReturnType<typeof listQuotations>>
>;
export type ListQuotationsQueryError = void;

export function useListQuotations<
    TData = Awaited<ReturnType<typeof listQuotations>>,
    TError = void,
>(
    slug: string,
    params: ListQuotationsParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listQuotations>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listQuotations>>,
                    TError,
                    Awaited<ReturnType<typeof listQuotations>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListQuotations<
    TData = Awaited<ReturnType<typeof listQuotations>>,
    TError = void,
>(
    slug: string,
    params: ListQuotationsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listQuotations>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listQuotations>>,
                    TError,
                    Awaited<ReturnType<typeof listQuotations>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListQuotations<
    TData = Awaited<ReturnType<typeof listQuotations>>,
    TError = void,
>(
    slug: string,
    params: ListQuotationsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listQuotations>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List quotations for a node (authenticated user only)
 */

export function useListQuotations<
    TData = Awaited<ReturnType<typeof listQuotations>>,
    TError = void,
>(
    slug: string,
    params: ListQuotationsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listQuotations>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListQuotationsQueryOptions(slug, params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}

export const getListQuotationsSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof listQuotations>>,
    TError = void,
>(
    slug: string,
    params: ListQuotationsParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listQuotations>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getListQuotationsQueryKey(slug, params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof listQuotations>>
    > = ({ signal }) =>
        listQuotations(slug, params, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listQuotations>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListQuotationsSuspenseQueryResult = NonNullable<
    Awaited<ReturnType<typeof listQuotations>>
>;
export type ListQuotationsSuspenseQueryError = void;

export function useListQuotationsSuspense<
    TData = Awaited<ReturnType<typeof listQuotations>>,
    TError = void,
>(
    slug: string,
    params: ListQuotationsParams,
    options: {
        query: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listQuotations>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListQuotationsSuspense<
    TData = Awaited<ReturnType<typeof listQuotations>>,
    TError = void,
>(
    slug: string,
    params: ListQuotationsParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listQuotations>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListQuotationsSuspense<
    TData = Awaited<ReturnType<typeof listQuotations>>,
    TError = void,
>(
    slug: string,
    params: ListQuotationsParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listQuotations>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List quotations for a node (authenticated user only)
 */

export function useListQuotationsSuspense<
    TData = Awaited<ReturnType<typeof listQuotations>>,
    TError = void,
>(
    slug: string,
    params: ListQuotationsParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listQuotations>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListQuotationsSuspenseQueryOptions(
        slug,
        params,
        options,
    );

    const query = useSuspenseQuery(
        queryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return { ...query, queryKey: queryOptions.queryKey };
}

export type createQuotationResponse200 = {
    data: CreateQuotationResponse;
    status: 200;
};

export type createQuotationResponse400 = {
    data: void;
    status: 400;
};

export type createQuotationResponse401 = {
    data: void;
    status: 401;
};

export type createQuotationResponse404 = {
    data: void;
    status: 404;
};

export type createQuotationResponseSuccess = createQuotationResponse200 & {
    headers: Headers;
};
export type createQuotationResponseError = (
    | createQuotationResponse400
    | createQuotationResponse401
    | createQuotationResponse404
) & {
    headers: Headers;
};

export const getCreateQuotationUrl = (slug: string) => {
    return `/api/books/${slug}/quotations`;
};

/**
 * @summary Save a quotation (returns existing if duplicate)
 */
export const createQuotation = async (
    slug: string,
    createQuotationRequest: CreateQuotationRequest,
    options?: RequestInit,
): Promise<createQuotationResponseSuccess> => {
    return customFetch<createQuotationResponseSuccess>(
        getCreateQuotationUrl(slug),
        {
            ...options,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(createQuotationRequest),
        },
    );
};

export const getCreateQuotationMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof createQuotation>>,
        TError,
        { slug: string; data: CreateQuotationRequest },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof createQuotation>>,
    TError,
    { slug: string; data: CreateQuotationRequest },
    TContext
> => {
    const mutationKey = ["createQuotation"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof createQuotation>>,
        { slug: string; data: CreateQuotationRequest }
    > = (props) => {
        const { slug, data } = props ?? {};

        return createQuotation(slug, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type CreateQuotationMutationResult = NonNullable<
    Awaited<ReturnType<typeof createQuotation>>
>;
export type CreateQuotationMutationBody = CreateQuotationRequest;
export type CreateQuotationMutationError = void;

/**
 * @summary Save a quotation (returns existing if duplicate)
 */
export const useCreateQuotation = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof createQuotation>>,
            TError,
            { slug: string; data: CreateQuotationRequest },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof createQuotation>>,
    TError,
    { slug: string; data: CreateQuotationRequest },
    TContext
> => {
    return useMutation(getCreateQuotationMutationOptions(options), queryClient);
};
export type deleteQuotationResponse200 = {
    data: void;
    status: 200;
};

export type deleteQuotationResponse400 = {
    data: void;
    status: 400;
};

export type deleteQuotationResponse401 = {
    data: void;
    status: 401;
};

export type deleteQuotationResponse404 = {
    data: void;
    status: 404;
};

export type deleteQuotationResponseSuccess = deleteQuotationResponse200 & {
    headers: Headers;
};
export type deleteQuotationResponseError = (
    | deleteQuotationResponse400
    | deleteQuotationResponse401
    | deleteQuotationResponse404
) & {
    headers: Headers;
};

export const getDeleteQuotationUrl = (slug: string, id: string) => {
    return `/api/books/${slug}/quotations/${id}`;
};

/**
 * @summary Delete a quotation (cascade-deletes notes)
 */
export const deleteQuotation = async (
    slug: string,
    id: string,
    options?: RequestInit,
): Promise<deleteQuotationResponseSuccess> => {
    return customFetch<deleteQuotationResponseSuccess>(
        getDeleteQuotationUrl(slug, id),
        {
            ...options,
            method: "DELETE",
        },
    );
};

export const getDeleteQuotationMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof deleteQuotation>>,
        TError,
        { slug: string; id: string },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof deleteQuotation>>,
    TError,
    { slug: string; id: string },
    TContext
> => {
    const mutationKey = ["deleteQuotation"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof deleteQuotation>>,
        { slug: string; id: string }
    > = (props) => {
        const { slug, id } = props ?? {};

        return deleteQuotation(slug, id, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type DeleteQuotationMutationResult = NonNullable<
    Awaited<ReturnType<typeof deleteQuotation>>
>;

export type DeleteQuotationMutationError = void;

/**
 * @summary Delete a quotation (cascade-deletes notes)
 */
export const useDeleteQuotation = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof deleteQuotation>>,
            TError,
            { slug: string; id: string },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof deleteQuotation>>,
    TError,
    { slug: string; id: string },
    TContext
> => {
    return useMutation(getDeleteQuotationMutationOptions(options), queryClient);
};
export type listNotesResponse200 = {
    data: NoteListResponse;
    status: 200;
};

export type listNotesResponse400 = {
    data: void;
    status: 400;
};

export type listNotesResponse401 = {
    data: void;
    status: 401;
};

export type listNotesResponse404 = {
    data: void;
    status: 404;
};

export type listNotesResponseSuccess = listNotesResponse200 & {
    headers: Headers;
};
export type listNotesResponseError = (
    | listNotesResponse400
    | listNotesResponse401
    | listNotesResponse404
) & {
    headers: Headers;
};

export const getListNotesUrl = (slug: string, id: string) => {
    return `/api/books/${slug}/quotations/${id}/notes`;
};

/**
 * @summary List notes for a quotation
 */
export const listNotes = async (
    slug: string,
    id: string,
    options?: RequestInit,
): Promise<listNotesResponseSuccess> => {
    return customFetch<listNotesResponseSuccess>(getListNotesUrl(slug, id), {
        ...options,
        method: "GET",
    });
};

export const getListNotesQueryKey = (slug: string, id: string) => {
    return [`/api/books/${slug}/quotations/${id}/notes`] as const;
};

export const getListNotesQueryOptions = <
    TData = Awaited<ReturnType<typeof listNotes>>,
    TError = void,
>(
    slug: string,
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listNotes>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getListNotesQueryKey(slug, id);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listNotes>>> = ({
        signal,
    }) => listNotes(slug, id, { signal, ...requestOptions });

    return {
        queryKey,
        queryFn,
        enabled:
            slug !== null &&
            slug !== undefined &&
            id !== null &&
            id !== undefined,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof listNotes>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListNotesQueryResult = NonNullable<
    Awaited<ReturnType<typeof listNotes>>
>;
export type ListNotesQueryError = void;

export function useListNotes<
    TData = Awaited<ReturnType<typeof listNotes>>,
    TError = void,
>(
    slug: string,
    id: string,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listNotes>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listNotes>>,
                    TError,
                    Awaited<ReturnType<typeof listNotes>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListNotes<
    TData = Awaited<ReturnType<typeof listNotes>>,
    TError = void,
>(
    slug: string,
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listNotes>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listNotes>>,
                    TError,
                    Awaited<ReturnType<typeof listNotes>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListNotes<
    TData = Awaited<ReturnType<typeof listNotes>>,
    TError = void,
>(
    slug: string,
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listNotes>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List notes for a quotation
 */

export function useListNotes<
    TData = Awaited<ReturnType<typeof listNotes>>,
    TError = void,
>(
    slug: string,
    id: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listNotes>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListNotesQueryOptions(slug, id, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}

export const getListNotesSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof listNotes>>,
    TError = void,
>(
    slug: string,
    id: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listNotes>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getListNotesQueryKey(slug, id);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listNotes>>> = ({
        signal,
    }) => listNotes(slug, id, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listNotes>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListNotesSuspenseQueryResult = NonNullable<
    Awaited<ReturnType<typeof listNotes>>
>;
export type ListNotesSuspenseQueryError = void;

export function useListNotesSuspense<
    TData = Awaited<ReturnType<typeof listNotes>>,
    TError = void,
>(
    slug: string,
    id: string,
    options: {
        query: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listNotes>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListNotesSuspense<
    TData = Awaited<ReturnType<typeof listNotes>>,
    TError = void,
>(
    slug: string,
    id: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listNotes>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListNotesSuspense<
    TData = Awaited<ReturnType<typeof listNotes>>,
    TError = void,
>(
    slug: string,
    id: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listNotes>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List notes for a quotation
 */

export function useListNotesSuspense<
    TData = Awaited<ReturnType<typeof listNotes>>,
    TError = void,
>(
    slug: string,
    id: string,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listNotes>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListNotesSuspenseQueryOptions(slug, id, options);

    const query = useSuspenseQuery(
        queryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return { ...query, queryKey: queryOptions.queryKey };
}

export type createNoteResponse200 = {
    data: NoteResponse;
    status: 200;
};

export type createNoteResponse400 = {
    data: void;
    status: 400;
};

export type createNoteResponse401 = {
    data: void;
    status: 401;
};

export type createNoteResponse404 = {
    data: void;
    status: 404;
};

export type createNoteResponseSuccess = createNoteResponse200 & {
    headers: Headers;
};
export type createNoteResponseError = (
    | createNoteResponse400
    | createNoteResponse401
    | createNoteResponse404
) & {
    headers: Headers;
};

export const getCreateNoteUrl = (slug: string, id: string) => {
    return `/api/books/${slug}/quotations/${id}/notes`;
};

/**
 * @summary Create a note on a quotation
 */
export const createNote = async (
    slug: string,
    id: string,
    createNoteRequest: CreateNoteRequest,
    options?: RequestInit,
): Promise<createNoteResponseSuccess> => {
    return customFetch<createNoteResponseSuccess>(getCreateNoteUrl(slug, id), {
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(createNoteRequest),
    });
};

export const getCreateNoteMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof createNote>>,
        TError,
        { slug: string; id: string; data: CreateNoteRequest },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof createNote>>,
    TError,
    { slug: string; id: string; data: CreateNoteRequest },
    TContext
> => {
    const mutationKey = ["createNote"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof createNote>>,
        { slug: string; id: string; data: CreateNoteRequest }
    > = (props) => {
        const { slug, id, data } = props ?? {};

        return createNote(slug, id, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type CreateNoteMutationResult = NonNullable<
    Awaited<ReturnType<typeof createNote>>
>;
export type CreateNoteMutationBody = CreateNoteRequest;
export type CreateNoteMutationError = void;

/**
 * @summary Create a note on a quotation
 */
export const useCreateNote = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof createNote>>,
            TError,
            { slug: string; id: string; data: CreateNoteRequest },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof createNote>>,
    TError,
    { slug: string; id: string; data: CreateNoteRequest },
    TContext
> => {
    return useMutation(getCreateNoteMutationOptions(options), queryClient);
};
export type updateNoteResponse200 = {
    data: void;
    status: 200;
};

export type updateNoteResponse400 = {
    data: void;
    status: 400;
};

export type updateNoteResponse401 = {
    data: void;
    status: 401;
};

export type updateNoteResponse403 = {
    data: void;
    status: 403;
};

export type updateNoteResponse404 = {
    data: void;
    status: 404;
};

export type updateNoteResponseSuccess = updateNoteResponse200 & {
    headers: Headers;
};
export type updateNoteResponseError = (
    | updateNoteResponse400
    | updateNoteResponse401
    | updateNoteResponse403
    | updateNoteResponse404
) & {
    headers: Headers;
};

export const getUpdateNoteUrl = (slug: string, id: string, noteId: string) => {
    return `/api/books/${slug}/quotations/${id}/notes/${noteId}`;
};

/**
 * @summary Update a note
 */
export const updateNote = async (
    slug: string,
    id: string,
    noteId: string,
    updateNoteRequest: UpdateNoteRequest,
    options?: RequestInit,
): Promise<updateNoteResponseSuccess> => {
    return customFetch<updateNoteResponseSuccess>(
        getUpdateNoteUrl(slug, id, noteId),
        {
            ...options,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(updateNoteRequest),
        },
    );
};

export const getUpdateNoteMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof updateNote>>,
        TError,
        { slug: string; id: string; noteId: string; data: UpdateNoteRequest },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof updateNote>>,
    TError,
    { slug: string; id: string; noteId: string; data: UpdateNoteRequest },
    TContext
> => {
    const mutationKey = ["updateNote"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof updateNote>>,
        { slug: string; id: string; noteId: string; data: UpdateNoteRequest }
    > = (props) => {
        const { slug, id, noteId, data } = props ?? {};

        return updateNote(slug, id, noteId, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type UpdateNoteMutationResult = NonNullable<
    Awaited<ReturnType<typeof updateNote>>
>;
export type UpdateNoteMutationBody = UpdateNoteRequest;
export type UpdateNoteMutationError = void;

/**
 * @summary Update a note
 */
export const useUpdateNote = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof updateNote>>,
            TError,
            {
                slug: string;
                id: string;
                noteId: string;
                data: UpdateNoteRequest;
            },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof updateNote>>,
    TError,
    { slug: string; id: string; noteId: string; data: UpdateNoteRequest },
    TContext
> => {
    return useMutation(getUpdateNoteMutationOptions(options), queryClient);
};
export type deleteNoteResponse200 = {
    data: void;
    status: 200;
};

export type deleteNoteResponse400 = {
    data: void;
    status: 400;
};

export type deleteNoteResponse401 = {
    data: void;
    status: 401;
};

export type deleteNoteResponse404 = {
    data: void;
    status: 404;
};

export type deleteNoteResponseSuccess = deleteNoteResponse200 & {
    headers: Headers;
};
export type deleteNoteResponseError = (
    | deleteNoteResponse400
    | deleteNoteResponse401
    | deleteNoteResponse404
) & {
    headers: Headers;
};

export const getDeleteNoteUrl = (slug: string, id: string, noteId: string) => {
    return `/api/books/${slug}/quotations/${id}/notes/${noteId}`;
};

/**
 * @summary Delete a note
 */
export const deleteNote = async (
    slug: string,
    id: string,
    noteId: string,
    options?: RequestInit,
): Promise<deleteNoteResponseSuccess> => {
    return customFetch<deleteNoteResponseSuccess>(
        getDeleteNoteUrl(slug, id, noteId),
        {
            ...options,
            method: "DELETE",
        },
    );
};

export const getDeleteNoteMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof deleteNote>>,
        TError,
        { slug: string; id: string; noteId: string },
        TContext
    >;
    request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof deleteNote>>,
    TError,
    { slug: string; id: string; noteId: string },
    TContext
> => {
    const mutationKey = ["deleteNote"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof deleteNote>>,
        { slug: string; id: string; noteId: string }
    > = (props) => {
        const { slug, id, noteId } = props ?? {};

        return deleteNote(slug, id, noteId, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type DeleteNoteMutationResult = NonNullable<
    Awaited<ReturnType<typeof deleteNote>>
>;

export type DeleteNoteMutationError = void;

/**
 * @summary Delete a note
 */
export const useDeleteNote = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof deleteNote>>,
            TError,
            { slug: string; id: string; noteId: string },
            TContext
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof deleteNote>>,
    TError,
    { slug: string; id: string; noteId: string },
    TContext
> => {
    return useMutation(getDeleteNoteMutationOptions(options), queryClient);
};
export type listAllNotesResponse200 = {
    data: NoteWithContextListResponse;
    status: 200;
};

export type listAllNotesResponse401 = {
    data: void;
    status: 401;
};

export type listAllNotesResponseSuccess = listAllNotesResponse200 & {
    headers: Headers;
};
export type listAllNotesResponseError = listAllNotesResponse401 & {
    headers: Headers;
};

export const getListAllNotesUrl = (params?: ListAllNotesParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(
                key,
                value === null ? "null" : String(value),
            );
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/api/notes?${stringifiedParams}`
        : `/api/notes`;
};

/**
 * @summary List all notes for the authenticated user (across all books)
 */
export const listAllNotes = async (
    params?: ListAllNotesParams,
    options?: RequestInit,
): Promise<listAllNotesResponseSuccess> => {
    return customFetch<listAllNotesResponseSuccess>(
        getListAllNotesUrl(params),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getListAllNotesQueryKey = (params?: ListAllNotesParams) => {
    return [`/api/notes`, ...(params ? [params] : [])] as const;
};

export const getListAllNotesQueryOptions = <
    TData = Awaited<ReturnType<typeof listAllNotes>>,
    TError = void,
>(
    params?: ListAllNotesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listAllNotes>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getListAllNotesQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAllNotes>>> = ({
        signal,
    }) => listAllNotes(params, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof listAllNotes>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListAllNotesQueryResult = NonNullable<
    Awaited<ReturnType<typeof listAllNotes>>
>;
export type ListAllNotesQueryError = void;

export function useListAllNotes<
    TData = Awaited<ReturnType<typeof listAllNotes>>,
    TError = void,
>(
    params: undefined | ListAllNotesParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listAllNotes>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listAllNotes>>,
                    TError,
                    Awaited<ReturnType<typeof listAllNotes>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAllNotes<
    TData = Awaited<ReturnType<typeof listAllNotes>>,
    TError = void,
>(
    params?: ListAllNotesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listAllNotes>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listAllNotes>>,
                    TError,
                    Awaited<ReturnType<typeof listAllNotes>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAllNotes<
    TData = Awaited<ReturnType<typeof listAllNotes>>,
    TError = void,
>(
    params?: ListAllNotesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listAllNotes>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List all notes for the authenticated user (across all books)
 */

export function useListAllNotes<
    TData = Awaited<ReturnType<typeof listAllNotes>>,
    TError = void,
>(
    params?: ListAllNotesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listAllNotes>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListAllNotesQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}

export const getListAllNotesSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof listAllNotes>>,
    TError = void,
>(
    params?: ListAllNotesParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listAllNotes>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getListAllNotesQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAllNotes>>> = ({
        signal,
    }) => listAllNotes(params, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listAllNotes>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListAllNotesSuspenseQueryResult = NonNullable<
    Awaited<ReturnType<typeof listAllNotes>>
>;
export type ListAllNotesSuspenseQueryError = void;

export function useListAllNotesSuspense<
    TData = Awaited<ReturnType<typeof listAllNotes>>,
    TError = void,
>(
    params: undefined | ListAllNotesParams,
    options: {
        query: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listAllNotes>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAllNotesSuspense<
    TData = Awaited<ReturnType<typeof listAllNotes>>,
    TError = void,
>(
    params?: ListAllNotesParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listAllNotes>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAllNotesSuspense<
    TData = Awaited<ReturnType<typeof listAllNotes>>,
    TError = void,
>(
    params?: ListAllNotesParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listAllNotes>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List all notes for the authenticated user (across all books)
 */

export function useListAllNotesSuspense<
    TData = Awaited<ReturnType<typeof listAllNotes>>,
    TError = void,
>(
    params?: ListAllNotesParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listAllNotes>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListAllNotesSuspenseQueryOptions(params, options);

    const query = useSuspenseQuery(
        queryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return { ...query, queryKey: queryOptions.queryKey };
}

export type listAllQuotationsResponse200 = {
    data: UnifiedQuotationListResponse;
    status: 200;
};

export type listAllQuotationsResponse401 = {
    data: void;
    status: 401;
};

export type listAllQuotationsResponseSuccess = listAllQuotationsResponse200 & {
    headers: Headers;
};
export type listAllQuotationsResponseError = listAllQuotationsResponse401 & {
    headers: Headers;
};

export const getListAllQuotationsUrl = (params?: ListAllQuotationsParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(
                key,
                value === null ? "null" : String(value),
            );
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/api/quotations?${stringifiedParams}`
        : `/api/quotations`;
};

/**
 * @summary List all quotations for the authenticated user (books + articles, unified)
 */
export const listAllQuotations = async (
    params?: ListAllQuotationsParams,
    options?: RequestInit,
): Promise<listAllQuotationsResponseSuccess> => {
    return customFetch<listAllQuotationsResponseSuccess>(
        getListAllQuotationsUrl(params),
        {
            ...options,
            method: "GET",
        },
    );
};

export const getListAllQuotationsQueryKey = (
    params?: ListAllQuotationsParams,
) => {
    return [`/api/quotations`, ...(params ? [params] : [])] as const;
};

export const getListAllQuotationsQueryOptions = <
    TData = Awaited<ReturnType<typeof listAllQuotations>>,
    TError = void,
>(
    params?: ListAllQuotationsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listAllQuotations>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getListAllQuotationsQueryKey(params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof listAllQuotations>>
    > = ({ signal }) =>
        listAllQuotations(params, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof listAllQuotations>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListAllQuotationsQueryResult = NonNullable<
    Awaited<ReturnType<typeof listAllQuotations>>
>;
export type ListAllQuotationsQueryError = void;

export function useListAllQuotations<
    TData = Awaited<ReturnType<typeof listAllQuotations>>,
    TError = void,
>(
    params: undefined | ListAllQuotationsParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listAllQuotations>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listAllQuotations>>,
                    TError,
                    Awaited<ReturnType<typeof listAllQuotations>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAllQuotations<
    TData = Awaited<ReturnType<typeof listAllQuotations>>,
    TError = void,
>(
    params?: ListAllQuotationsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listAllQuotations>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof listAllQuotations>>,
                    TError,
                    Awaited<ReturnType<typeof listAllQuotations>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAllQuotations<
    TData = Awaited<ReturnType<typeof listAllQuotations>>,
    TError = void,
>(
    params?: ListAllQuotationsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listAllQuotations>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List all quotations for the authenticated user (books + articles, unified)
 */

export function useListAllQuotations<
    TData = Awaited<ReturnType<typeof listAllQuotations>>,
    TError = void,
>(
    params?: ListAllQuotationsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof listAllQuotations>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListAllQuotationsQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}

export const getListAllQuotationsSuspenseQueryOptions = <
    TData = Awaited<ReturnType<typeof listAllQuotations>>,
    TError = void,
>(
    params?: ListAllQuotationsParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listAllQuotations>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getListAllQuotationsQueryKey(params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof listAllQuotations>>
    > = ({ signal }) =>
        listAllQuotations(params, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof listAllQuotations>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListAllQuotationsSuspenseQueryResult = NonNullable<
    Awaited<ReturnType<typeof listAllQuotations>>
>;
export type ListAllQuotationsSuspenseQueryError = void;

export function useListAllQuotationsSuspense<
    TData = Awaited<ReturnType<typeof listAllQuotations>>,
    TError = void,
>(
    params: undefined | ListAllQuotationsParams,
    options: {
        query: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listAllQuotations>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAllQuotationsSuspense<
    TData = Awaited<ReturnType<typeof listAllQuotations>>,
    TError = void,
>(
    params?: ListAllQuotationsParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listAllQuotations>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListAllQuotationsSuspense<
    TData = Awaited<ReturnType<typeof listAllQuotations>>,
    TError = void,
>(
    params?: ListAllQuotationsParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listAllQuotations>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List all quotations for the authenticated user (books + articles, unified)
 */

export function useListAllQuotationsSuspense<
    TData = Awaited<ReturnType<typeof listAllQuotations>>,
    TError = void,
>(
    params?: ListAllQuotationsParams,
    options?: {
        query?: Partial<
            UseSuspenseQueryOptions<
                Awaited<ReturnType<typeof listAllQuotations>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof customFetch>;
    },
    queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getListAllQuotationsSuspenseQueryOptions(
        params,
        options,
    );

    const query = useSuspenseQuery(
        queryOptions,
        queryClient,
    ) as UseSuspenseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    return { ...query, queryKey: queryOptions.queryKey };
}
