/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */
import type { TopicResponse } from "./topicResponse";

export interface ArticleResponse {
    author_display_name: string;
    created_at: string;
    /** @nullable */
    description?: string | null;
    id: string;
    /** @nullable */
    published_at?: string | null;
    slug: string;
    status: string;
    title: string;
    topics: TopicResponse[];
    updated_at: string;
}
