/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export interface AuthResponse {
    /** @nullable */
    avatar_url?: string | null;
    display_name: string;
    email: string;
    id: string;
    roles: string[];
}
