/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */
import type { BatchSentenceRequest } from "./batchSentenceRequest";

export interface BatchSentencesRequest {
    items: BatchSentenceRequest[];
}
