/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export interface CreateQuotationRequest {
    /** @nullable */
    sentence_end?: number | null;
    sentence_kind: string;
    sentence_start: number;
}
