/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Prospero API
 * OpenAPI spec version: 0.1.0
 */
import type { FootnoteSentenceResponse } from "./footnoteSentenceResponse";

export interface FootnoteResponse {
    id: string;
    number: number;
    sentences: FootnoteSentenceResponse[];
}
