/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Prospero API
 * OpenAPI spec version: 0.1.0
 */

export type GetNodePageParams = {
/**
 * play_order cursor — omit for first page
 * @nullable
 */
after?: number | null;
/**
 * page size, default 20, max 50
 * @nullable
 */
limit?: number | null;
};
