/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */
import type { LibraryWork } from "./libraryWork";

export interface LibraryAuthor {
    books: LibraryWork[];
    id: string;
    name: string;
    sort_name: string;
}
