/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */
import type { ContentBlockResponse } from "./contentBlockResponse";

export interface NodeDetail {
    blocks: ContentBlockResponse[];
    depth: number;
    id: string;
    label: string;
    slug: string;
    sort_order: number;
    /** @nullable */
    source_node_id?: string | null;
    source_ref: string;
}
