/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Prospero API
 * OpenAPI spec version: 0.1.0
 */
import type { NodeDetail } from "./nodeDetail";

export interface NodePage {
    has_more: boolean;
    has_previous: boolean;
    nodes: NodeDetail[];
}
