/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */
import type { TagResponse } from "./tagResponse";

export interface NoteWithContextResponse {
    /**
     * For footnote-kind anchors: the body sentence number the footnote is
  attached to. None for body-kind anchors.
     * @nullable
     */
    anchor_main_sentence_number?: number | null;
    /** @nullable */
    anchor_sentence_end_number?: number | null;
    anchor_sentence_start_number: number;
    body: string;
    book_slug: string;
    book_title: string;
    created_at: string;
    id: string;
    node_label: string;
    node_slug: string;
    quotation_id: string;
    sentence_kind: string;
    tags: TagResponse[];
    updated_at: string;
}
