/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */
import type { NoteWithContextResponse } from "./noteWithContextResponse";

export interface NoteWithContextListResponse {
    notes: NoteWithContextResponse[];
}
