/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export interface PageMarkerResponse {
    /** @nullable */
    char_offset?: number | null;
    ref_value: string;
    sort_order: number;
    system_slug: string;
}
