/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export interface QuotationWithContextResponse {
    /** @nullable */
    anchor_sentence_end_number?: number | null;
    anchor_sentence_start_number: number;
    book_slug: string;
    book_title: string;
    created_at: string;
    /** @nullable */
    end_text_snippet?: string | null;
    id: string;
    node_label: string;
    node_slug: string;
    note_count: number;
    sentence_kind: string;
    /** @nullable */
    start_text_snippet?: string | null;
}
