/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Prospero API
 * OpenAPI spec version: 0.1.0
 */

export interface QuotationResponse {
    /** @nullable */
    anchor_sentence_end_number?: number | null;
    anchor_sentence_start_number: number;
    created_at: string;
    id: string;
    note_count: number;
    sentence_kind: string;
}
