/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export interface SourcePersonResponse {
    name: string;
    person_id: string;
    position: number;
    role: string;
    /** @nullable */
    sort_name?: string | null;
}
