/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */
import type { TagResponse } from "./tagResponse";

export interface TagListResponse {
    tags: TagResponse[];
}
