/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Prospero API
 * OpenAPI spec version: 0.1.0
 */

export interface TocNodeResponse {
  children: TocNodeResponse[];
  depth: number;
  has_content: boolean;
  id: string;
  label: string;
  ncx_id: string;
  play_order: number;
  slug: string;
}
