/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Prospero API
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateSourceRequest {
    /** @nullable */
    doi?: string | null;
    /** @nullable */
    edition?: string | null;
    /** @nullable */
    isbn?: string[] | null;
    /** @nullable */
    journal_name?: string | null;
    /** @nullable */
    page_end?: number | null;
    /** @nullable */
    page_start?: number | null;
    /** @nullable */
    parent_source_id?: string | null;
    /** @nullable */
    publication_year?: number | null;
    /** @nullable */
    publisher?: string | null;
    /** @nullable */
    source_type?: string | null;
    /** @nullable */
    title?: string | null;
    /** @nullable */
    title_display?: string | null;
    /** @nullable */
    translation_of_id?: string | null;
    /** @nullable */
    url?: string | null;
    /** @nullable */
    volume?: string | null;
}
