/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateArticleRequest {
    /** @nullable */
    description?: string | null;
    /** @nullable */
    markdown?: string | null;
    /** @nullable */
    title?: string | null;
    /** @nullable */
    topic_ids?: string[] | null;
}
