/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Scholia API
 * OpenAPI spec version: 0.1.0
 */
import type { FeedbackStatus } from "./feedbackStatus";

export interface UpdateFeedbackRequest {
    /** @nullable */
    admin_notes?: string | null;
    status?: null | FeedbackStatus;
}
