# Replace the base's PLACEHOLDER hostname with dev.scholia.study.
# When we cut prod, the prod overlay will replace with scholia.study
# and additionally patch the cluster-issuer annotation to
# `letsencrypt-prod`.

- op: replace
  path: /spec/tls/0/hosts/0
  value: dev.scholia.study
- op: replace
  path: /spec/rules/0/host
  value: dev.scholia.study
