apiVersion: v1
kind: Secret
metadata:
    name: turnstile
    namespace: scholia
stringData:
    TURNSTILE_SECRET_KEY: ENC[AES256_GCM,data:p00QJgWxLY9AtuSRqPfyXJy41CxbTJL33o/fZufiDCtUc4I=,iv:H5OaJJwIyfw9yLRxpqAsup6njK748HOCjQTqBn7JJyo=,tag:meyuYhYEiWhphy79d/D8WA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzais4cnFnTlo0eGRMUTFU
            YksrOXlxM1pqUGJuU2tNL3VlQlMzMHgrL1dJCkducEFFSDk0bXdzOUFVMzJxQVhQ
            ZmlEQTlNTDNoOExOQnRVaFU5U0JzQmcKLS0tIEN5M1A5UnlPZkFmbUdZVFhIaUlp
            SnQ4K1BHVlV4YWpNRWUvMXY0Y3NraFUKoN3IwNz0SlY6b87E8B8Ml26deZCdLZhT
            3UMerHOZA72epBFwjW+m0M0dUTITwxd7ZKBqmUJteMbQq0+Tc+VitQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1da7lwg3mfe3wkgwk9xk9swzj65nh9q5fnttpgcsdfhdhepesyslsud4gn9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T15:40:25Z"
    mac: ENC[AES256_GCM,data:MbMMkLcdqT1A7yfxfFa9kyPy5ziToynfIvwHB6/QAZrqtjeMJCqICoDlnvR9YtNiOH+q6zfgzaUH10mWF8qtPrQrYfUgiJAfAQ5sT4EWOfI+mLL27vQ791zJAob/YEfC2v3LzKfY+zNIzjNuTlxLy2un6GDKcfS3ZR81L0GwAt0=,iv:nDGJbBl3YCpyDGfb2ezZ+ZHCvpT64mpHKTyAmfjIy7U=,tag:MEASyRcgViXqQKNRALN62w==,type:str]
    version: 3.13.0
