use utoipa::OpenApi;

pub mod auth;
pub mod config;
pub mod db;
pub mod email;
pub mod error;
pub mod handlers;
pub mod models;
pub mod state;

#[derive(OpenApi)]
#[openapi(
    info(title = "Prospero API", version = "0.1.0"),
    paths(
        handlers::books::list_books,
        handlers::books::get_book,
        handlers::toc::get_toc,
        handlers::nodes::get_node,
        handlers::page::get_node_page,
        handlers::auth::register,
        handlers::auth::login,
        handlers::auth::logout,
        handlers::auth::me,
        handlers::auth::forgot_password,
        handlers::auth::reset_password,
        handlers::auth::verify_email,
        handlers::auth::get_profile,
        handlers::auth::update_profile,
        handlers::auth::request_password_change,
        handlers::github::github_login,
        handlers::github::github_callback,
        handlers::resources::list_resources,
        handlers::resources::create_resource,
        handlers::resources::update_resource,
        handlers::resources::delete_resource,
        handlers::sources::search_sources,
        handlers::sources::create_source,
        handlers::sources::update_source,
        handlers::sources::add_source_person,
        handlers::sources::remove_source_person,
        handlers::sources::check_source_references,
        handlers::persons::search_persons,
        handlers::persons::create_person,
        handlers::persons::update_person,
        handlers::quotations::list_quotations,
        handlers::quotations::create_quotation,
        handlers::quotations::delete_quotation,
        handlers::quotations::list_notes,
        handlers::quotations::create_note,
        handlers::quotations::update_note,
        handlers::quotations::delete_note,
        handlers::quotations::list_tags,
    ),
    components(schemas(
        models::book::BookSummary,
        models::book::BookDetail,
        models::toc::TocNodeResponse,
        models::node::NodeDetail,
        models::node::ContentBlockResponse,
        models::node::SentenceResponse,
        models::node::PageMarkerResponse,
        models::node::FootnoteResponse,
        models::node::FootnoteSentenceResponse,
        models::page::NodePage,
        handlers::auth::RegisterRequest,
        handlers::auth::LoginRequest,
        handlers::auth::ForgotPasswordRequest,
        handlers::auth::ResetPasswordRequest,
        handlers::auth::AuthResponse,
        handlers::auth::MessageResponse,
        handlers::auth::ProfileResponse,
        handlers::auth::LinkedProvider,
        handlers::auth::UpdateProfileRequest,
        models::resource::ResourceResponse,
        models::resource::ResourceListResponse,
        models::resource::SourceResponse,
        models::resource::ParentSourceResponse,
        models::resource::SourcePersonResponse,
        models::resource::PersonResponse,
        models::resource::SourceSearchResponse,
        models::resource::CreateResourceRequest,
        models::resource::UpdateResourceRequest,
        models::resource::CreateSourceRequest,
        models::resource::UpdateSourceRequest,
        models::resource::CreatePersonRequest,
        models::resource::UpdatePersonRequest,
        models::resource::LinkSourcePersonRequest,
        models::resource::ReferenceCheckResponse,
        models::quotation::QuotationResponse,
        models::quotation::QuotationListResponse,
        models::quotation::CreateQuotationRequest,
        models::quotation::CreateQuotationResponse,
        models::quotation::NoteResponse,
        models::quotation::NoteListResponse,
        models::quotation::CreateNoteRequest,
        models::quotation::UpdateNoteRequest,
        models::quotation::TagResponse,
        models::quotation::TagListResponse,
    ))
)]
pub struct ApiDoc;
