# Prod environment overlay.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scholia

resources:
  - ../../base
  - ingest-jobs

generators:
  - secret-generator.yaml

images:
  - name: ghcr.io/scholia-study/scholia-api
    newTag: main-e2918ec
  - name: ghcr.io/scholia-study/scholia-web
    newTag: main-505d3c2
  - name: ghcr.io/scholia-study/scholia-proxy
    newTag: main-e2918ec

patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: scholia
  - path: web-env-patch.yaml
    target:
      kind: Deployment
      name: scholia-web
  - path: backup-env-patch.yaml
    target:
      kind: CronJob
      name: postgres-backup
