apiVersion: v1
kind: Service
metadata:
  name: scholia-web
  labels:
    app.kubernetes.io/name: scholia-web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: scholia-web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
